import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { currentActor } from "@/auth/current-actor";
import { can } from "@/auth/permissions";
import { ApplicationError } from "@/lib/errors";
import { InvoiceService } from "@/modules/invoices";
import { PaymentService } from "@/modules/payments";
import { issueInvoiceAction, postPaymentAction, reversePaymentAction, updateInvoiceAction, voidInvoiceAction } from "../actions";

const money=(value:number)=>`$${(value/100).toFixed(2)}`;
export default async function Page({params}:{params:Promise<{id:string}>}){
  const actor=await currentActor();if(!actor)redirect("/login");const{id}=await params;
  let detail;try{detail=await new InvoiceService().get(actor,id)}catch(error){if(error instanceof ApplicationError)notFound();throw error}
  const canReadPayments=can({role:actor.role},"payment.read"),canPost=can({role:actor.role},"payment.create"),canReverse=can({role:actor.role},"payment.reverse");
  const ledger=canReadPayments?await new PaymentService().listForInvoice(actor,id):[];
  const reversedIds=new Set(ledger.filter(entry=>entry.entryType==="reversal").map(entry=>entry.reversesPaymentId));
  const i=detail.invoice,billing=JSON.parse(i.billingSnapshot) as {name:string};
  return <main className="mx-auto max-w-4xl px-6 py-12"><p className="text-sm text-primary">{i.identifier}</p><h1 className="text-4xl font-semibold">{billing.name}</h1><p className="mt-2 text-muted-foreground">{i.status} · {i.source} · {i.currency} {money(i.totalCents)} · balance {money(i.balanceCents)}{i.isOverdue?" · overdue":""}</p>
    <section className="mt-8 rounded-xl border p-5"><h2 className="text-xl font-semibold">Lines</h2>{detail.lines.map(line=><div key={line.id} className="flex justify-between border-b py-2"><span>{line.description} · {(line.quantityMilli/1000).toFixed(3)} {line.unit}</span><span>{money(line.totalCents)}</span></div>)}<div className="mt-4 text-right"><p>Subtotal {money(i.subtotalCents)}</p><p>Tax {money(i.taxCents)}</p><p className="font-semibold">Total {money(i.totalCents)}</p></div></section>
    {i.status==="draft"?<form action={updateInvoiceAction.bind(null,id)} className="mt-8 grid gap-3 rounded-xl border p-5"><input type="hidden" name="expectedRowVersion" value={i.rowVersion}/><textarea name="notes" defaultValue={i.notes} placeholder="Notes" className="rounded-md border px-3 py-2"/><textarea name="terms" defaultValue={i.terms} placeholder="Terms" className="rounded-md border px-3 py-2"/><select name="paymentTerms" defaultValue={i.paymentTerms} className="rounded-md border px-3 py-2"><option value="due_on_receipt">Due on receipt</option><option value="net_15">Net 15</option><option value="net_30">Net 30</option><option value="net_60">Net 60</option><option value="custom">Custom</option></select><input type="date" name="dueDate" defaultValue={i.dueDate??""} className="rounded-md border px-3 py-2"/><button className="rounded-md border px-4 py-2">Save draft</button></form>:null}
    <div className="mt-8 flex flex-wrap gap-3">{i.status==="draft"?<form action={issueInvoiceAction.bind(null,id)}><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground">Issue Invoice</button></form>:null}<Link href={`/api/invoices/${id}/pdf`} className="rounded-md border px-4 py-2">View PDF</Link>{i.status!=="void"?<form action={voidInvoiceAction.bind(null,id)} className="flex gap-2"><input required name="reason" placeholder="Void reason" className="rounded-md border px-3"/><button className="rounded-md border border-destructive px-4 py-2">Void</button></form>:null}</div>
    {canReadPayments?<section className="mt-8 rounded-xl border p-5"><h2 className="text-xl font-semibold">Payment ledger</h2><p className="mt-1 text-sm text-muted-foreground">Effective paid {money(i.amountPaidCents)} · balance {money(i.balanceCents)}</p>{ledger.map(entry=><div key={entry.id} className="mt-3 border-t pt-3"><div className="flex flex-wrap items-center justify-between gap-2"><span>{entry.entryType==="reversal"?"Reversal":"Payment"} · {money(entry.amountCents)} · {entry.method.replaceAll("_"," ")}</span>{entry.entryType==="payment"?<Link className="text-sm underline" href={`/api/payments/${entry.id}/receipt`}>Receipt</Link>:null}</div>{entry.entryType==="payment"&&canReverse&&!reversedIds.has(entry.id)?<form action={reversePaymentAction.bind(null,id,entry.id)} className="mt-2 flex gap-2"><input required name="reason" placeholder="Reversal reason" className="rounded-md border px-3 py-1"/><button className="rounded-md border px-3 py-1 text-sm">Reverse</button></form>:null}</div>)}</section>:null}
    {canPost&&["issued","partially_paid"].includes(i.status)&&i.balanceCents>0?<form action={postPaymentAction.bind(null,id)} className="mt-8 grid gap-3 rounded-xl border p-5"><h2 className="text-xl font-semibold">Record payment</h2><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><input required type="number" name="amountCents" min="1" max={i.balanceCents} placeholder="Amount in cents" className="rounded-md border px-3 py-2"/><div className="grid gap-3 md:grid-cols-2"><select name="payerType" className="rounded-md border px-3 py-2"><option value="customer">Customer</option><option value="government">Government</option><option value="third_party">Third party</option></select><select name="method" className="rounded-md border px-3 py-2"><option value="cash">Cash</option><option value="check">Check</option><option value="credit_card">Credit card</option><option value="debit_card">Debit card</option><option value="e_transfer">E-transfer</option><option value="bank_transfer">Bank transfer</option><option value="financing">Financing</option><option value="other">Other</option></select></div><input name="externalReference" placeholder="Reference (optional)" className="rounded-md border px-3 py-2"/><input name="receivedBy" placeholder="Received by (optional)" className="rounded-md border px-3 py-2"/><textarea name="notes" placeholder="Internal notes" className="rounded-md border px-3 py-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground">Record immutable payment</button></form>:null}
  </main>;
}
