"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { currentActor } from "@/auth/current-actor";
import { InvoiceService } from "@/modules/invoices";
import { PaymentService } from "@/modules/payments";
export async function createManualInvoiceAction(data:FormData){const actor=await currentActor();if(!actor)redirect("/login");const invoice=await new InvoiceService().create(actor,{source:"manual",customerId:String(data.get("customerId")??""),paymentTerms:String(data.get("paymentTerms")??"due_on_receipt"),notes:String(data.get("notes")??""),terms:String(data.get("terms")??""),lines:[{description:String(data.get("description")??""),unit:String(data.get("unit")??"each"),category:"service",quantityMilli:Number(data.get("quantityMilli")??1000),unitPriceCents:Number(data.get("unitPriceCents")??0),taxable:data.get("taxable")==="on"}]});redirect(`/invoices/${invoice.id}`)}
export async function createContractInvoiceAction(data:FormData){const actor=await currentActor();if(!actor)redirect("/login");const invoice=await new InvoiceService().create(actor,{source:"contract",contractId:String(data.get("contractId")??""),paymentTerms:String(data.get("paymentTerms")??"due_on_receipt"),notes:"",terms:""});redirect(`/invoices/${invoice.id}`)}
export async function updateInvoiceAction(id:string,data:FormData){const actor=await currentActor();if(!actor)redirect("/login");await new InvoiceService().updateDraft(actor,id,{expectedRowVersion:Number(data.get("expectedRowVersion")),notes:String(data.get("notes")??""),terms:String(data.get("terms")??""),paymentTerms:String(data.get("paymentTerms")??"due_on_receipt"),dueDate:data.get("dueDate")?String(data.get("dueDate")):null});revalidatePath(`/invoices/${id}`)}
export async function issueInvoiceAction(id:string){const actor=await currentActor();if(!actor)redirect("/login");await new InvoiceService().issue(actor,id);revalidatePath(`/invoices/${id}`)}
export async function voidInvoiceAction(id:string,data:FormData){const actor=await currentActor();if(!actor)redirect("/login");await new InvoiceService().void(actor,id,{reason:String(data.get("reason")??"")});revalidatePath(`/invoices/${id}`)}
export async function postPaymentAction(id:string,data:FormData){const actor=await currentActor();if(!actor)redirect("/login");await new PaymentService().post(actor,id,{amountCents:Number(data.get("amountCents")),payerType:String(data.get("payerType")??"customer"),method:String(data.get("method")??"other"),source:"manual",externalReference:String(data.get("externalReference")??"")||undefined,idempotencyKey:String(data.get("idempotencyKey")??""),receivedBy:String(data.get("receivedBy")??""),notes:String(data.get("notes")??"")});revalidatePath(`/invoices/${id}`)}
export async function reversePaymentAction(invoiceId:string,paymentId:string,data:FormData){const actor=await currentActor();if(!actor)redirect("/login");await new PaymentService().reverse(actor,paymentId,{reason:String(data.get("reason")??"")});revalidatePath(`/invoices/${invoiceId}`)}
