/**
 * Phase 13 — E-Sign provider abstraction. Mirrors notification-providers.ts's
 * shape (`EmailProvider`/`SmsProvider` → `ProviderError`/`sanitizeErrorMessage`)
 * deliberately, since this codebase already has one proven pattern for
 * "abstract an external delivery mechanism, ship a real adapter behind it."
 *
 * Section 22's decision: no real paid E-Sign vendor is integrated this
 * phase (that would need its own architecture/security review and a
 * dependency the project doesn't have yet). `LocalEsignProvider` is the
 * only implementation — signing happens entirely in-process via
 * contracts.ts's own token-gated public routes, never a third-party
 * redirect. `createSignatureRequest()`/`getSigningUrl()` are pure local
 * operations (no network call); `getStatus()` reads contracts.ts's own
 * DB state; `cancelRequest()` is a local status flip; `fetchCompletedDocument()`
 * returns null (nothing external to fetch — the signed artifact already
 * lives in R2, written directly by contracts.ts); `verifyWebhook()` always
 * returns false (this provider never receives webhooks). A future real
 * adapter (e.g. a hosted E-Sign vendor) implements the same interface and
 * is swapped in at the single call site in contracts.ts — no caller
 * outside that one site needs to change.
 */

export interface CreateSignatureRequestInput {
  contractId: number;
  contractVersionId: number;
  signerId: number;
  signerEmail: string;
  signerName: string;
  expiresAt: string;
}

export interface CreateSignatureRequestResult {
  /** Raw, unhashed token — returned ONLY here, at creation time. Never
   *  persisted in plaintext (contracts.ts hashes it before storing) and
   *  never returned by any later read. */
  token: string;
  providerRequestId: string | null;
}

export type EsignStatus = "pending" | "sent" | "viewed" | "signed" | "declined" | "expired" | "cancelled";

export interface EsignProvider {
  createSignatureRequest(input: CreateSignatureRequestInput): Promise<CreateSignatureRequestResult>;
  getSigningUrl(token: string): string;
  getStatus(providerRequestId: string | null): Promise<EsignStatus | null>;
  cancelRequest(providerRequestId: string | null): Promise<void>;
  fetchCompletedDocument(providerRequestId: string | null): Promise<ArrayBuffer | null>;
  /** Always false for a provider with no real webhook source (e.g. Local). */
  verifyWebhook(payload: string, signatureHeader: string | null): boolean;
}

export class EsignProviderError extends Error {
  code: string;
  constructor(code: string, message: string) {
    super(message);
    this.code = code;
  }
}

/** Same secret-redaction discipline as notification-providers.ts's
 *  sanitizeErrorMessage — reused verbatim in spirit, kept local here since
 *  this module has no dependency on notifications.ts. */
export function sanitizeProviderErrorMessage(message: string): string {
  return message
    .replace(/Bearer\s+\S+/gi, "[redacted]")
    .replace(/Basic\s+\S+/gi, "[redacted]")
    .replace(/"?(api[_-]?key|auth[_-]?token|authorization|password|secret|token)"?\s*[:=]\s*"?[^\s",}]+/gi, "$1=[redacted]")
    .slice(0, 300);
}

/**
 * The only implementation this phase ships. Signing is entirely local —
 * "provider" here just means "the thing that knows how to build a signing
 * URL," not an external service. `getSigningUrl()` builds a public,
 * unauthenticated app route gated solely by the token itself (see
 * contracts.ts's public routes and PUBLIC_API_PATHS' new prefix exemption
 * in index.ts) — the raw token is never logged or stored.
 */
export class LocalEsignProvider implements EsignProvider {
  async createSignatureRequest(input: CreateSignatureRequestInput): Promise<CreateSignatureRequestResult> {
    void input; // nothing external to call — the token itself is generated by contracts.ts (crypto.getRandomValues), not here
    return { token: "", providerRequestId: null };
  }

  getSigningUrl(token: string): string {
    return `/sign/${token}`;
  }

  async getStatus(): Promise<EsignStatus | null> {
    return null; // local provider has no external state to poll — contracts.ts's own DB is authoritative
  }

  async cancelRequest(): Promise<void> {
    // no-op — local provider has nothing external to cancel
  }

  async fetchCompletedDocument(): Promise<ArrayBuffer | null> {
    return null; // nothing external to fetch — the signed artifact is written directly to R2 by contracts.ts
  }

  verifyWebhook(): boolean {
    return false; // local provider never receives webhooks
  }
}

export function getEsignProvider(): EsignProvider {
  return new LocalEsignProvider();
}
