import { createHash, createHmac, randomBytes } from "node:crypto";
import { authorize } from "@/auth/authorization";
import type { Role } from "@/auth/permissions";
import { getDb } from "@/db/client";
import { AuditRepository } from "@/modules/audit/audit.repository";
import { ConflictError, ForbiddenError, NotFoundError, UnauthorizedError, ValidationError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import type { RequestActor } from "@/modules/customers/customer.service";
import { JobService } from "@/modules/jobs/job.service";
import { JobRepository } from "@/modules/jobs/job.repository";
import { LeadService } from "@/modules/leads/lead.service";
import { TaskService } from "@/modules/interactions/task.service";
import { callFilterSchema, inboundCallSchema, outcomeSchema, outboundCallSchema, parseToolArguments, phoneNumberSchema, providerCredentialSchema, providerEventSchema, runtimeCredentialSchema, settingsSchema, toolInvocationSchema, transcriptSchema, updateCallSchema, voiceAgentSchema } from "./phone.schema";
import { assertCallTransition, hashPhonePayload, mapTwilioCallStatus, normalizePhone, PHONE_TOOLS, verifyTwilioSignature } from "./phone.rules";
import { PhoneRepository } from "./phone.repository";
import { phoneProtectorFromEnvironment, TwilioPhoneAdapter, type PhoneProviderAdapter, type SecretProtector } from "./phone.provider";

const nullable = (value?: string | null) => value?.trim() || null;
const baseUrl = () => process.env.APP_URL ?? "http://localhost:3000";
const startOfVancouverDay = (now = new Date()) => { const day = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Vancouver", year: "numeric", month: "2-digit", day: "2-digit" }).format(now); return new Date(`${day}T00:00:00-07:00`); };
const tokenHash = (value: string) => createHash("sha256").update(value).digest("hex");
const lazyProtector: SecretProtector = { protect: value => phoneProtectorFromEnvironment().protect(value), reveal: value => phoneProtectorFromEnvironment().reveal(value) };

export class PhoneOperationsService {
  constructor(private readonly adapter: PhoneProviderAdapter = new TwilioPhoneAdapter(), private readonly protector: SecretProtector = lazyProtector) {}
  async receiveProviderEventForm(url: string, params: Record<string, string>, signature: string) { const input = { providerCallId: params.CallSid ?? "", providerEventId: params.EventSid ?? `${params.CallSid}:${params.CallStatus}:${params.Timestamp}`, status: params.CallStatus ?? "", occurredAt: params.Timestamp ?? new Date().toISOString() }, call = await new PhoneRepository().callByProvider(input.providerCallId); if (!call) throw new UnauthorizedError("Invalid provider request"); const credential = await new PhoneRepository().credential(call.organizationId); if (!credential) throw new UnauthorizedError("Invalid provider request"); const token = this.protector.reveal({ ciphertext: credential.authTokenCiphertext, iv: credential.authTokenIv, tag: credential.authTokenTag }); if (!verifyTwilioSignature(token, url, params, signature)) throw new UnauthorizedError("Invalid provider request"); return this.receiveProviderEvent(url, input, this.signature(token, url, { CallSid: input.providerCallId, CallStatus: input.status, EventSid: input.providerEventId, Timestamp: input.occurredAt })); }
  private signature(token: string, url: string, params: Record<string, string>) { return createHmac("sha1", token).update(url + Object.keys(params).sort().map(k => `${k}${params[k]}`).join("")).digest("base64"); }
  async receiveInboundForm(url: string, params: Record<string, string>, signature: string) { const input = { providerCallId: params.CallSid ?? "", from: params.From ?? "", to: params.To ?? "" }, number = await new PhoneRepository().numberByE164(input.to); if (!number) return null; const credential = await new PhoneRepository().credential(number.organizationId); if (!credential) throw new UnauthorizedError("Invalid provider request"); const token = this.protector.reveal({ ciphertext: credential.authTokenCiphertext, iv: credential.authTokenIv, tag: credential.authTokenTag }); if (!verifyTwilioSignature(token, url, params, signature)) throw new UnauthorizedError("Invalid provider request"); return this.receiveInbound(url, input, this.signature(token, url, { CallSid: input.providerCallId, From: input.from, To: input.to })); }

  async getSettings(actor: RequestActor) { await authorize(actor, "phone.read"); const r = new PhoneRepository(); return await r.currentSettings(actor.organizationId) ?? { operatingMode: "disabled" as const, inboundEnabled: false, outboundEnabled: false, maxConcurrentCalls: 1, dailyCallCap: 25, voiceRuntimeUrl: null }; }
  async listSettingsHistory(actor: RequestActor) { await authorize(actor, "phone.settings.manage"); return new PhoneRepository().listSettings(actor.organizationId); }
  async saveSettings(actor: RequestActor, raw: unknown) { await authorize(actor, "phone.settings.manage"); const i = parseInput(settingsSchema, raw); return getDb().transaction(async tx => { const r = new PhoneRepository(tx), current = await r.currentSettings(actor.organizationId, true), now = new Date(); if (current) await r.closeSettings(actor.organizationId, now); const value = await r.createSettings({ organizationId: actor.organizationId, version: (current?.version ?? 0) + 1, ...i, voiceRuntimeUrl: nullable(i.voiceRuntimeUrl), effectiveFrom: now, createdBy: actor.userId }); await new AuditRepository(tx).record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "phone.settings_updated", entityType: "phone_settings", entityId: value.id, metadata: { version: value.version, operatingMode: value.operatingMode } }); return value; }); }

  async saveProviderCredential(actor: RequestActor, raw: unknown) { await authorize(actor, "phone.settings.manage"); const i = parseInput(providerCredentialSchema, raw), secret = this.protector.protect(i.authToken); return getDb().transaction(async tx => { const r = new PhoneRepository(tx), value = await r.saveCredential({ organizationId: actor.organizationId, provider: "twilio", accountSid: i.accountSid, authTokenCiphertext: secret.ciphertext, authTokenIv: secret.iv, authTokenTag: secret.tag, updatedBy: actor.userId }); await new AuditRepository(tx).record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "phone.provider_credentials_updated", entityType: "phone_provider_credentials", entityId: value.id, metadata: { provider: "twilio", accountSidSuffix: i.accountSid.slice(-4) } }); return { id: value.id, provider: value.provider, accountSidSuffix: value.accountSid.slice(-4), updatedAt: value.updatedAt }; }); }
  async issueRuntimeCredential(actor: RequestActor, raw: unknown) { await authorize(actor, "phone.settings.manage"); const i = parseInput(runtimeCredentialSchema, raw), token = `ofs_phone_${randomBytes(32).toString("base64url")}`; const value = await new PhoneRepository().createRuntimeCredential({ organizationId: actor.organizationId, name: i.name, tokenHash: tokenHash(token), tokenPrefix: token.slice(0, 14), createdBy: actor.userId }); return { credential: { id: value.id, name: value.name, tokenPrefix: value.tokenPrefix }, token }; }
  async listRuntimeCredentials(actor: RequestActor) { await authorize(actor, "phone.settings.manage"); return new PhoneRepository().listRuntimeCredentials(actor.organizationId); }
  async revokeRuntimeCredential(actor: RequestActor, id: string) { await authorize(actor, "phone.settings.manage"); const value = await new PhoneRepository().revokeRuntimeCredential(actor.organizationId, id); if (!value) throw new NotFoundError("Runtime credential not found"); return value; }

  async publishVoiceAgent(actor: RequestActor, raw: unknown) { await authorize(actor, "phone.settings.manage"); const i = parseInput(voiceAgentSchema, raw); return getDb().transaction(async tx => { const r = new PhoneRepository(tx); await r.closeAgent(actor.organizationId, i.logicalName); if (i.isDefault) await r.demoteDefault(actor.organizationId); const value = await r.publishAgent({ organizationId: actor.organizationId, logicalName: i.logicalName, version: await r.nextAgentVersion(actor.organizationId, i.logicalName), status: "active", isDefault: i.isDefault, prompt: i.prompt, voice: i.voice, toolPolicy: [...new Set(i.toolPolicy)], createdBy: actor.userId }); await new AuditRepository(tx).record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "phone.voice_agent_published", entityType: "voice_agent", entityId: value.id, metadata: { logicalName: value.logicalName, version: value.version, tools: value.toolPolicy } }); return value; }); }
  async listVoiceAgents(actor: RequestActor) { await authorize(actor, "phone.read"); return new PhoneRepository().listAgents(actor.organizationId); }
  async savePhoneNumber(actor: RequestActor, raw: unknown) { await authorize(actor, "phone.settings.manage"); const i = parseInput(phoneNumberSchema, raw); return getDb().transaction(async tx => { const r = new PhoneRepository(tx); if (i.voiceAgentId && !await r.currentAgent(actor.organizationId, i.voiceAgentId)) throw new NotFoundError("Voice agent not found"); const value = await r.saveNumber({ organizationId: actor.organizationId, provider: "twilio", providerNumberId: i.providerNumberId, e164: i.e164, label: nullable(i.label), inboundEnabled: i.inboundEnabled, outboundEnabled: i.outboundEnabled, voiceAgentId: i.voiceAgentId, createdBy: actor.userId, updatedBy: actor.userId }); if (value.organizationId !== actor.organizationId) throw new ConflictError("Phone number is already provisioned"); await new AuditRepository(tx).record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "phone.number_configured", entityType: "phone_number", entityId: value.id, metadata: { e164Suffix: value.e164.slice(-4) } }); return value; }); }
  async listPhoneNumbers(actor: RequestActor) { await authorize(actor, "phone.read"); return new PhoneRepository().listNumbers(actor.organizationId); }

  async listCalls(actor: RequestActor, raw: unknown = {}) { await authorize(actor, "phone.read"); const i = parseInput(callFilterSchema, raw); return { ...await new PhoneRepository().listCalls(actor.organizationId, { ...i, limit: i.pageSize, offset: (i.page - 1) * i.pageSize }), page: i.page, pageSize: i.pageSize }; }
  async getCall(actor: RequestActor, id: string) { await authorize(actor, "phone.read"); const r = new PhoneRepository(), call = await r.call(actor.organizationId, id); if (!call) throw new NotFoundError("Call not found"); return { call, events: await r.listCallEvents(actor.organizationId, id), transcript: await r.listCallTranscripts(actor.organizationId, id), outcome: await r.callOutcome(actor.organizationId, id) }; }
  async updateCall(actor: RequestActor, id: string, raw: unknown) { await authorize(actor, "phone.manage"); const i = parseInput(updateCallSchema, raw); if (i.assignedUserId !== undefined) await authorize(actor, "phone.assign"); return getDb().transaction(async tx => { const r = new PhoneRepository(tx), call = await r.call(actor.organizationId, id, true); if (!call) throw new NotFoundError("Call not found"); if (i.assignedUserId && !await r.member(actor.organizationId, i.assignedUserId)) throw new NotFoundError("Assignable member not found"); if (i.customerId && !await r.customer(actor.organizationId, i.customerId)) throw new NotFoundError("Customer not found"); if (i.leadId && !await r.lead(actor.organizationId, i.leadId)) throw new NotFoundError("Lead not found"); const manualLink = i.customerId !== undefined || i.leadId !== undefined; const value = await r.updateCall(actor.organizationId, id, { assignedUserId: i.assignedUserId, disposition: i.disposition === undefined ? undefined : nullable(i.disposition), notes: i.notes === undefined ? undefined : nullable(i.notes), customerId: i.customerId, leadId: i.leadId, matchConfidence: manualLink ? (i.customerId || i.leadId ? "manual" : "unknown") : undefined, matchSource: manualLink ? `user:${actor.userId}` : undefined }); await new AuditRepository(tx).record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "phone.call_updated", entityType: "phone_call", entityId: id, metadata: { assigned: i.assignedUserId !== undefined, disposition: i.disposition !== undefined, crmLink: manualLink } }); return value!; }); }

  async placeOutboundCall(actor: RequestActor, raw: unknown) {
    await authorize(actor, "phone.call"); const i = parseInput(outboundCallSchema, raw);
    const prepared = await getDb().transaction(async tx => {
      const r = new PhoneRepository(tx), settings = await r.currentSettings(actor.organizationId, true);
      if (!settings || settings.operatingMode !== "active" || !settings.outboundEnabled) throw new ConflictError("Outbound Phone Operations is not active");
      const number = await r.number(actor.organizationId, i.phoneNumberId);
      if (!number || number.status !== "active" || !number.outboundEnabled) throw new NotFoundError("Outbound phone number not found");
      if (i.customerId && !await r.customer(actor.organizationId, i.customerId)) throw new NotFoundError("Customer not found");
      if (await r.activeCallCount(actor.organizationId) >= settings.maxConcurrentCalls) throw new ConflictError("Concurrent call limit reached");
      if (await r.dailyCallCount(actor.organizationId, startOfVancouverDay()) >= settings.dailyCallCap) throw new ConflictError("Daily call limit reached");
      const credential = await r.credential(actor.organizationId); if (!credential) throw new ConflictError("Phone provider is not configured");
      const agent = await r.currentAgent(actor.organizationId, number.voiceAgentId);
      const created = await r.createCall({ organizationId: actor.organizationId, provider: "twilio", providerCallId: `request:${i.idempotencyKey}`, clientRequestId: i.idempotencyKey, direction: "outbound", status: "queued", phoneNumberId: number.id, normalizedFrom: normalizePhone(number.e164), normalizedTo: normalizePhone(i.destination), customerId: i.customerId, matchConfidence: i.customerId ? "manual" : "unknown", matchSource: i.customerId ? `user:${actor.userId}` : "outbound", agentSnapshot: agent ? { agentId: agent.id, version: agent.version, prompt: agent.prompt, voice: agent.voice, toolPolicy: agent.toolPolicy } : null });
      return { call: created ?? await r.callByRequest(actor.organizationId, i.idempotencyKey), settings, number, credential };
    });
    if (!prepared.call || prepared.call.organizationId !== actor.organizationId) throw new ConflictError("Outbound request identity was already used");
    if (!prepared.call.providerCallId.startsWith("request:")) return prepared.call;
    const claimed = await new PhoneRepository().claimPlacement(actor.organizationId, prepared.call.id);
    if (!claimed) return prepared.call;
    try {
      const result = await this.adapter.placeCall({ accountSid: prepared.credential.accountSid, authToken: this.protector.reveal({ ciphertext: prepared.credential.authTokenCiphertext, iv: prepared.credential.authTokenIv, tag: prepared.credential.authTokenTag }), from: prepared.number.e164, to: i.destination, voiceUrl: `${baseUrl()}/api/phone/twilio/voice`, statusCallbackUrl: `${baseUrl()}/api/phone/twilio/status` });
      return await new PhoneRepository().setProviderCallId(actor.organizationId, prepared.call.id, result.providerCallId);
    } catch { await new PhoneRepository().updateCall(actor.organizationId, prepared.call.id, { status: "failed", endedAt: new Date() }); throw new ConflictError("Phone provider could not place the call"); }
  }

  async receiveInbound(url: string, raw: unknown, signature: string) { const i = parseInput(inboundCallSchema, raw), r = new PhoneRepository(), number = await r.numberByE164(i.to); if (!number || !number.inboundEnabled) return null; const credential = await r.credential(number.organizationId); if (!credential || !verifyTwilioSignature(this.protector.reveal({ ciphertext: credential.authTokenCiphertext, iv: credential.authTokenIv, tag: credential.authTokenTag }), url, { CallSid: i.providerCallId, From: i.from, To: i.to }, signature)) throw new UnauthorizedError("Invalid provider request"); const settings = await r.currentSettings(number.organizationId); if (!settings || settings.operatingMode !== "active" || !settings.inboundEnabled) return null; const agent = await r.currentAgent(number.organizationId, number.voiceAgentId), normalized = normalizePhone(i.from), matches = await r.customerMatches(number.organizationId, normalized), customer = matches.length === 1 ? matches[0] : null; const call = await r.createCall({ organizationId: number.organizationId, provider: "twilio", providerCallId: i.providerCallId, direction: "inbound", status: "ringing", phoneNumberId: number.id, normalizedFrom: normalized, normalizedTo: normalizePhone(i.to), customerId: customer?.id, matchConfidence: customer ? "exact_phone" : "unknown", matchSource: customer ? "normalized_phone" : matches.length > 1 ? "ambiguous_phone" : "no_match", agentSnapshot: agent ? { agentId: agent.id, version: agent.version, prompt: agent.prompt, voice: agent.voice, toolPolicy: agent.toolPolicy } : null, startedAt: new Date() }); const resolved = call ?? await r.callByProvider(i.providerCallId); if (!resolved || resolved.organizationId !== number.organizationId) throw new ConflictError("Provider call identity collision"); return { call: resolved, voiceRuntimeUrl: settings.voiceRuntimeUrl }; }
  async receiveProviderEvent(url: string, raw: unknown, signature: string) { const i = parseInput(providerEventSchema, raw), existing = await new PhoneRepository().callByProvider(i.providerCallId); if (!existing) throw new UnauthorizedError("Invalid provider request"); const r = new PhoneRepository(), credential = await r.credential(existing.organizationId); if (!credential || !verifyTwilioSignature(this.protector.reveal({ ciphertext: credential.authTokenCiphertext, iv: credential.authTokenIv, tag: credential.authTokenTag }), url, { CallSid: i.providerCallId, CallStatus: i.status, EventSid: i.providerEventId, Timestamp: i.occurredAt }, signature)) throw new UnauthorizedError("Invalid provider request"); return getDb().transaction(async tx => { const repo = new PhoneRepository(tx), call = await repo.call(existing.organizationId, existing.id, true); if (!call) throw new UnauthorizedError("Invalid provider request"); const mapped = mapTwilioCallStatus(i.status); let accepted = true, reason: string | null = null; try { assertCallTransition(call.status, mapped); } catch { accepted = false; reason = "invalid_or_stale_transition"; } const event = await repo.addCallEvent({ organizationId: call.organizationId, callId: call.id, providerEventId: i.providerEventId, providerStatus: i.status, mappedStatus: mapped, providerOccurredAt: new Date(i.occurredAt), accepted, rejectionReason: reason, metadata: {} }); if (!event) return call; if (accepted && call.status !== mapped) return (await repo.updateCall(call.organizationId, call.id, { status: mapped, answeredAt: mapped === "in_progress" ? new Date(i.occurredAt) : call.answeredAt, endedAt: ["completed", "failed", "no_answer", "busy", "canceled"].includes(mapped) ? new Date(i.occurredAt) : null }))!; return call; }); }

  async authenticateRuntime(token: string) { const credential = await new PhoneRepository().runtimeCredential(tokenHash(token)); if (!credential || !credential.createdBy) throw new UnauthorizedError("Invalid runtime credential"); const member = await new PhoneRepository().member(credential.organizationId, credential.createdBy); if (!member) throw new UnauthorizedError("Runtime credential issuer is no longer active"); return { actor: { userId: credential.createdBy, organizationId: credential.organizationId, role: member.role as Role }, credentialId: credential.id }; }
  async addTranscript(runtimeToken: string, callId: string, raw: unknown) { const { actor } = await this.authenticateRuntime(runtimeToken), i = parseInput(transcriptSchema, raw), r = new PhoneRepository(), call = await r.call(actor.organizationId, callId); if (!call) throw new NotFoundError("Call not found"); return await r.addCallTranscript({ organizationId: actor.organizationId, callId, ...i, occurredAt: new Date(i.occurredAt) }) ?? (await r.listCallTranscripts(actor.organizationId, callId)).find(x => x.sequence === i.sequence)!; }
  async recordOutcome(runtimeToken: string, callId: string, raw: unknown) { const { actor } = await this.authenticateRuntime(runtimeToken), i = parseInput(outcomeSchema, raw), r = new PhoneRepository(), call = await r.call(actor.organizationId, callId); if (!call) throw new NotFoundError("Call not found"); return await r.createCallOutcome({ organizationId: actor.organizationId, callId, ...i, capturedBy: actor.userId }) ?? await r.callOutcome(actor.organizationId, callId); }

  async invokeTool(runtimeToken: string, callId: string, raw: unknown) { const { actor } = await this.authenticateRuntime(runtimeToken), i = parseInput(toolInvocationSchema, raw), payloadHash = hashPhonePayload(i.arguments), r = new PhoneRepository(), call = await r.call(actor.organizationId, callId); if (!call) throw new NotFoundError("Call not found"); if (!call.agentSnapshot?.toolPolicy.includes(i.toolName)) throw new ForbiddenError("Tool is not enabled for this call"); const claim = await r.claimToolInvocation({ organizationId: actor.organizationId, callId, idempotencyKey: i.idempotencyKey, toolName: i.toolName, payloadHash }); if (!claim) { const prior = await r.toolInvocation(actor.organizationId, callId, i.idempotencyKey); if (!prior || prior.toolName !== i.toolName || prior.payloadHash !== payloadHash) throw new ConflictError("Idempotency key was used for another invocation"); if (prior.status === "succeeded") return prior.result; throw new ConflictError("Tool invocation is already in progress"); } const result = await this.executeTool(actor, call, i.toolName, i.arguments); await r.finishToolInvocation(actor.organizationId, claim.id, result); return result; }

  private async resolveCallCrm(_actor: RequestActor, call: Awaited<ReturnType<PhoneRepository["call"]>>) { if (!call) throw new NotFoundError("Call not found"); if (call.customerId) return { targetType: "customer" as const, targetId: call.customerId }; if (call.leadId) return { targetType: "lead" as const, targetId: call.leadId }; throw new ConflictError("Call must be linked to a Customer or Lead"); }
  private async executeTool(actor: RequestActor, call: NonNullable<Awaited<ReturnType<PhoneRepository["call"]>>>, tool: typeof PHONE_TOOLS[number], args: Record<string, unknown>): Promise<Record<string, unknown>> {
    args = parseToolArguments(tool, args);
    if (tool === "find_customer_by_phone") { const phone = String(args.phone ?? call.normalizedFrom), matches = await new PhoneRepository().customerMatches(actor.organizationId, normalizePhone(phone)); return { match: matches.length === 1 ? matches[0] : null, ambiguous: matches.length > 1 }; }
    if (tool === "get_customer_service_context") { if (!call.customerId) throw new ConflictError("Call is not linked to a Customer"); const customer = await new PhoneRepository().customer(actor.organizationId, call.customerId); if (!customer) throw new NotFoundError("Customer not found"); const jobs = await new JobService().listJobs(actor, { customerId: customer.id, page: 1, pageSize: 20 }); return { customer: { id: customer.id, name: customer.name }, jobs: jobs.items.map(j => ({ id: j.id, identifier: j.identifier, status: j.status, scheduledDate: j.scheduledDate })) }; }
    if (tool === "get_job_status") { const job = await new JobService().getJob(actor, String(args.jobId ?? "")); if (job.job.customerId !== call.customerId) throw new NotFoundError("Job not found"); return { job: { id: job.job.id, identifier: job.job.identifier, status: job.job.status, scheduledDate: job.job.scheduledDate, scheduledTime: job.job.scheduledTime } }; }
    if (tool === "get_available_slots") { const technicianUserId = String(args.technicianUserId ?? ""), date = String(args.date ?? ""), time = String(args.time ?? ""), durationMinutes = Number(args.durationMinutes ?? 60); if (!/^[0-9a-f-]{36}$/i.test(technicianUserId) || !/^\d{4}-\d{2}-\d{2}$/.test(date) || !/^([01]\d|2[0-3]):[0-5]\d$/.test(time) || !Number.isInteger(durationMinutes) || durationMinutes < 1 || durationMinutes > 1440) throw new ValidationError("Invalid availability request"); if (!await new PhoneRepository().member(actor.organizationId, technicianUserId)) throw new NotFoundError("Technician not found"); const conflicts = await new JobRepository().conflicts(actor.organizationId, technicianUserId, date, time, durationMinutes); return { available: conflicts.length === 0 }; }
    if (tool === "create_lead_from_call") { if (call.customerId || call.leadId) throw new ConflictError("Call is already linked"); const lead = await new LeadService().createLead(actor, { name: String(args.name ?? "Unknown caller"), phone: String(args.phone ?? `+1${call.normalizedFrom}`), source: "phone", notes: typeof args.notes === "string" ? args.notes : "Created from inbound call" }); await new PhoneRepository().updateCall(actor.organizationId, call.id, { leadId: lead.id, matchConfidence: "manual", matchSource: "voice_tool:create_lead" }); return { leadId: lead.id, identifier: lead.identifier }; }
    if (tool === "create_follow_up") { const target = await this.resolveCallCrm(actor, call), task = await new TaskService().createTask(actor, { title: String(args.title ?? "Phone follow-up"), description: typeof args.description === "string" ? args.description : "", priority: "normal", dueAt: typeof args.dueAt === "string" ? args.dueAt : null, assigneeUserId: null, ...target }); await new PhoneRepository().linkTask(actor.organizationId, call.id, task.id); return { taskId: task.id }; }
    if (tool === "create_appointment_for_customer") { if (!call.customerId) throw new ConflictError("Appointment requires an existing linked Customer"); const customer = await new PhoneRepository().customer(actor.organizationId, call.customerId); if (!customer) throw new NotFoundError("Customer not found"); const job = await new JobService().createJob(actor, { customerId: customer.id, title: String(args.title ?? "Service appointment"), description: typeof args.description === "string" ? args.description : "Created from phone call", serviceAddress: String(args.serviceAddress ?? customer.addressLine1 ?? "Address to confirm"), scheduledDate: typeof args.scheduledDate === "string" ? args.scheduledDate : null, scheduledTime: typeof args.scheduledTime === "string" ? args.scheduledTime : null, technicianUserId: null, durationMinutes: typeof args.durationMinutes === "number" ? args.durationMinutes : 60 }); await new PhoneRepository().updateCall(actor.organizationId, call.id, { jobId: job.id }); return { jobId: job.id, identifier: job.identifier, assigned: false }; }
    throw new ValidationError("Unknown phone tool");
  }
}
