import { createHmac } from "node:crypto";
import { eq } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { getDb } from "@/db";
import { phoneCallEvents, phoneCallOutcomes, phoneCallTranscripts, phoneCalls, phoneProviderCredentials, phoneToolInvocations, tasks } from "@/db/schema";
import { ConflictError, ForbiddenError, NotFoundError, UnauthorizedError } from "@/lib/errors";
import { CustomerService } from "@/modules/customers/customer.service";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { AesGcmSecretProtector, type PhoneProviderAdapter } from "./phone.provider";
import { PhoneOperationsService } from "./phone.service";

describe.sequential("PostgreSQL Phone Operations and CRM integration", () => {
  const protector = new AesGcmSecretProtector("synthetic-integration-encryption-key-32-bytes");
  let providerCalls = 0;
  const adapter: PhoneProviderAdapter = { async placeCall() { providerCalls += 1; return { providerCallId: `CA${String(providerCalls).padStart(32, "0")}`, status: "queued" }; } };
  const service = new PhoneOperationsService(adapter, protector), url = "https://field.example.test/api/phone/twilio/voice", statusUrl = "https://field.example.test/api/phone/twilio/status", authToken = "synthetic-twilio-auth-token";
  let a: Awaited<ReturnType<OrganizationService["createOrganizationWithOwner"]>>, b: typeof a, customerA: Awaited<ReturnType<CustomerService["createCustomer"]>>, customerB: typeof customerA, manager: Awaited<ReturnType<UserService["createUserWithMembership"]>>, numberId: string, runtimeToken: string;
  const actor = () => ({ userId: a.user.id, organizationId: a.organization.id, role: "owner" as const }), foreign = () => ({ userId: b.user.id, organizationId: b.organization.id, role: "owner" as const }), dispatcher = () => ({ userId: manager.user.id, organizationId: a.organization.id, role: "manager" as const });
  const sign = (targetUrl: string, params: Record<string, string>, token = authToken) => createHmac("sha1", token).update(targetUrl + Object.keys(params).sort().map(k => `${k}${params[k]}`).join("")).digest("base64");
  const inbound = (callSid: string, from: string, to = "+16045550200") => { const params = { AccountSid: `AC${"a".repeat(32)}`, CallSid: callSid, CallStatus: "ringing", From: from, To: to }; return service.receiveInboundForm(url, params, sign(url, params)); };

  it("creates tenant fixtures and encrypted, versioned, RBAC-protected configuration", async () => { const orgs = new OrganizationService(); a = await orgs.createOrganizationWithOwner({ name: "Phone A", slug: `phone-a-${crypto.randomUUID()}` }, { name: "Owner A", email: `phone-a-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-123" }); b = await orgs.createOrganizationWithOwner({ name: "Phone B", slug: `phone-b-${crypto.randomUUID()}` }, { name: "Owner B", email: `phone-b-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-456" }); customerA = await new CustomerService().createCustomer(actor(), { name: "Exact Caller", phone: "+1 (604) 555-0100", addressLine1: "100 Alpha St" }); customerB = await new CustomerService().createCustomer(foreign(), { name: "Foreign Caller", phone: "+1 604 555 0100" }); manager = await new UserService().createUserWithMembership(actor(), { name: "Dispatcher", email: `dispatcher-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-789" }, "manager"); await service.saveSettings(actor(), { operatingMode: "active", inboundEnabled: true, outboundEnabled: true, maxConcurrentCalls: 10, dailyCallCap: 100, voiceRuntimeUrl: "wss://voice.example.test/connect" }); await service.saveProviderCredential(actor(), { accountSid: `AC${"a".repeat(32)}`, authToken }); await expect(service.saveSettings(dispatcher(), { operatingMode: "active", inboundEnabled: true, outboundEnabled: true, maxConcurrentCalls: 1, dailyCallCap: 1, voiceRuntimeUrl: "" })).rejects.toBeInstanceOf(ForbiddenError); const agent = await service.publishVoiceAgent(actor(), { logicalName: "dispatch", prompt: "Assist callers", voice: "alloy", isDefault: true, toolPolicy: ["create_lead_from_call", "create_follow_up", "create_appointment_for_customer"] }); const number = await service.savePhoneNumber(actor(), { providerNumberId: "PN-SYNTHETIC", e164: "+16045550200", label: "Dispatch", inboundEnabled: true, outboundEnabled: true, voiceAgentId: agent.id }); numberId = number.id; const issued = await service.issueRuntimeCredential(actor(), { name: "Synthetic voice runtime" }); runtimeToken = issued.token; const [stored] = await getDb().select().from(phoneProviderCredentials).where(eq(phoneProviderCredentials.organizationId, a.organization.id)); expect(JSON.stringify(stored)).not.toContain(authToken); expect((await service.listSettingsHistory(actor())).map(x => x.version)).toEqual([1]); });
  it("matches one normalized same-tenant Customer and never guesses unknown or ambiguous callers", async () => { const exact = await inbound("CA-INBOUND-EXACT", "+16045550100"); expect(exact?.call).toMatchObject({ customerId: customerA.id, matchConfidence: "exact_phone" }); const unknown = await inbound("CA-INBOUND-UNKNOWN", "+16045550999"); expect(unknown?.call).toMatchObject({ customerId: null, leadId: null, matchConfidence: "unknown" }); await new CustomerService().createCustomer(actor(), { name: "Ambiguous One", phone: "604-555-0123" }); await new CustomerService().createCustomer(actor(), { name: "Ambiguous Two", phone: "+1 604 555 0123" }); const ambiguous = await inbound("CA-INBOUND-AMBIGUOUS", "+16045550123"); expect(ambiguous?.call).toMatchObject({ customerId: null, matchConfidence: "unknown", matchSource: "ambiguous_phone" }); });
  it("rejects invalid signatures and provider tenant mismatch without an oracle", async () => { await expect(service.receiveInbound(url, { providerCallId: "CA-BAD", from: "+16045550100", to: "+16045550200" }, "bad")).rejects.toBeInstanceOf(UnauthorizedError); await service.saveSettings(foreign(), { operatingMode: "active", inboundEnabled: true, outboundEnabled: false, maxConcurrentCalls: 1, dailyCallCap: 10, voiceRuntimeUrl: "wss://foreign.example.test" }); await service.saveProviderCredential(foreign(), { accountSid: `AC${"b".repeat(32)}`, authToken: "foreign-synthetic-auth-token" }); await expect(service.savePhoneNumber(foreign(), { providerNumberId: "PN-FOREIGN", e164: "+16045550200", inboundEnabled: true, outboundEnabled: false })).rejects.toBeInstanceOf(ConflictError); expect((await service.listPhoneNumbers(foreign())).length).toBe(0); });
  it("deduplicates inbound delivery and orders provider lifecycle without terminal rewrites", async () => { const [first, second] = await Promise.all([inbound("CA-REPLAY", "+16045550100"), inbound("CA-REPLAY", "+16045550100")]); expect(first?.call.id).toBe(second?.call.id); const call = first!.call, progress = { providerCallId: "CA-REPLAY", providerEventId: "EV-PROGRESS", status: "in-progress", occurredAt: "2026-09-09T20:00:00Z" }, completed = { providerCallId: "CA-REPLAY", providerEventId: "EV-DONE", status: "completed", occurredAt: "2026-09-09T20:05:00Z" }; await Promise.all([service.receiveProviderEvent(statusUrl, progress, sign(statusUrl, { CallSid: progress.providerCallId, CallStatus: progress.status, EventSid: progress.providerEventId, Timestamp: progress.occurredAt })), service.receiveProviderEvent(statusUrl, progress, sign(statusUrl, { CallSid: progress.providerCallId, CallStatus: progress.status, EventSid: progress.providerEventId, Timestamp: progress.occurredAt }))]); expect((await service.receiveProviderEvent(statusUrl, completed, sign(statusUrl, { CallSid: completed.providerCallId, CallStatus: completed.status, EventSid: completed.providerEventId, Timestamp: completed.occurredAt }))).status).toBe("completed"); const stale = { ...progress, providerEventId: "EV-STALE", status: "ringing", occurredAt: "2026-09-09T19:59:00Z" }; expect((await service.receiveProviderEvent(statusUrl, stale, sign(statusUrl, { CallSid: stale.providerCallId, CallStatus: stale.status, EventSid: stale.providerEventId, Timestamp: stale.occurredAt }))).status).toBe("completed"); const events = await getDb().select().from(phoneCallEvents).where(eq(phoneCallEvents.callId, call.id)); expect(events).toHaveLength(3); expect(events.find(x => x.providerEventId === "EV-STALE")?.accepted).toBe(false); });
  it("blocks cross-tenant CRM/assignee injection and Technician access", async () => { const call = (await inbound("CA-MANUAL", "+16045550998"))!.call; await expect(service.updateCall(actor(), call.id, { customerId: customerB.id })).rejects.toBeInstanceOf(NotFoundError); await expect(service.updateCall(foreign(), call.id, { disposition: "breach" })).rejects.toBeInstanceOf(NotFoundError); await expect(service.updateCall(actor(), call.id, { assignedUserId: b.user.id })).rejects.toBeInstanceOf(NotFoundError); const member = await new UserService().createUserWithMembership(actor(), { name: "Tech", email: `phone-tech-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-000" }, "member"), tech = { userId: member.user.id, organizationId: a.organization.id, role: "member" as const }; await expect(service.listCalls(tech, {})).rejects.toBeInstanceOf(ForbiddenError); expect((await service.updateCall(dispatcher(), call.id, { customerId: customerA.id, disposition: "booked" })).matchConfidence).toBe("manual"); });
  it("places an outbound provider request once across lost-acknowledgement replay", async () => { const idempotencyKey = crypto.randomUUID(), raw = { phoneNumberId: numberId, destination: "+16045550300", customerId: customerA.id, idempotencyKey }; const first = await service.placeOutboundCall(dispatcher(), raw), second = await service.placeOutboundCall(dispatcher(), raw); expect(first?.id).toBe(second?.id); expect(providerCalls).toBe(1); expect(first?.providerCallId).toMatch(/^CA/); await expect(service.placeOutboundCall(dispatcher(), { ...raw, customerId: customerB.id, idempotencyKey: crypto.randomUUID() })).rejects.toBeInstanceOf(NotFoundError); });
  it("never redials after an ambiguous provider acknowledgement", async () => { let attempts = 0; const ambiguous = new PhoneOperationsService({ async placeCall() { attempts += 1; throw new Error("acknowledgement lost"); } }, protector), raw = { phoneNumberId: numberId, destination: "+16045550301", idempotencyKey: crypto.randomUUID() }; await expect(ambiguous.placeOutboundCall(dispatcher(), raw)).rejects.toBeInstanceOf(ConflictError); const replay = await ambiguous.placeOutboundCall(dispatcher(), raw); expect(attempts).toBe(1); expect(replay?.status).toBe("failed"); expect(replay?.placementStartedAt).toBeInstanceOf(Date); });
  it("freezes tool policy and executes Lead and canonical Task side effects exactly once", async () => { const call = (await inbound("CA-TOOLS", "+16045550888"))!.call, leadKey = crypto.randomUUID(); const [leadResult, replay] = await Promise.allSettled([service.invokeTool(runtimeToken, call.id, { idempotencyKey: leadKey, toolName: "create_lead_from_call", arguments: { name: "Phone Lead", phone: "+16045550888" } }), service.invokeTool(runtimeToken, call.id, { idempotencyKey: leadKey, toolName: "create_lead_from_call", arguments: { name: "Phone Lead", phone: "+16045550888" } })]); expect([leadResult, replay].filter(x => x.status === "fulfilled")).toHaveLength(1); const linked = (await getDb().select().from(phoneCalls).where(eq(phoneCalls.id, call.id)))[0]!; expect(linked.leadId).toBeTruthy(); const taskKey = crypto.randomUUID(), task = await service.invokeTool(runtimeToken, call.id, { idempotencyKey: taskKey, toolName: "create_follow_up", arguments: { title: "Return phone call" } }); expect(await service.invokeTool(runtimeToken, call.id, { idempotencyKey: taskKey, toolName: "create_follow_up", arguments: { title: "Return phone call" } })).toEqual(task); expect((await getDb().select().from(tasks).where(eq(tasks.id, String(task?.taskId))))).toHaveLength(1); expect((await getDb().select().from(phoneToolInvocations).where(eq(phoneToolInvocations.callId, call.id))).filter(x => x.status === "succeeded")).toHaveLength(2); });
  it("deduplicates private transcript/outcome writes and rejects foreign runtime credentials", async () => { const call = (await inbound("CA-RUNTIME", "+16045550100"))!.call, line = { sequence: 1, speaker: "customer", content: "Synthetic transcript", occurredAt: "2026-09-09T21:00:00Z" }; await Promise.all([service.addTranscript(runtimeToken, call.id, line), service.addTranscript(runtimeToken, call.id, line)]); await Promise.all([service.recordOutcome(runtimeToken, call.id, { summary: "Booked", disposition: "appointment" }), service.recordOutcome(runtimeToken, call.id, { summary: "Booked", disposition: "appointment" })]); expect(await getDb().select().from(phoneCallTranscripts).where(eq(phoneCallTranscripts.callId, call.id))).toHaveLength(1); expect(await getDb().select().from(phoneCallOutcomes).where(eq(phoneCallOutcomes.callId, call.id))).toHaveLength(1); const foreignIssued = await service.issueRuntimeCredential(foreign(), { name: "Foreign runtime" }); await expect(service.addTranscript(foreignIssued.token, call.id, { ...line, sequence: 2 })).rejects.toBeInstanceOf(NotFoundError); });
});
