import { and, asc, count, desc, eq, gte, ilike, isNull, or, sql } from "drizzle-orm";
import { getDb, type DatabaseExecutor } from "@/db/client";
import { activities, customers, jobs, leads, organizationMembers, phoneCallEvents, phoneCallOutcomes, phoneCalls, phoneCallTaskLinks, phoneCallTranscripts, phoneNumbers, phoneOperationSettings, phoneProviderCredentials, phoneRuntimeCredentials, phoneToolInvocations, tasks, voiceAgents } from "@/db/schema";

export class PhoneRepository {
  constructor(private readonly db: DatabaseExecutor = getDb()) {}
  currentSettings(org: string, lock = false) { const q = this.db.select().from(phoneOperationSettings).where(and(eq(phoneOperationSettings.organizationId, org), isNull(phoneOperationSettings.effectiveUntil))).limit(1); return lock ? q.for("update").then(x => x[0] ?? null) : q.then(x => x[0] ?? null); }
  async closeSettings(org: string, at: Date) { await this.db.update(phoneOperationSettings).set({ effectiveUntil: at }).where(and(eq(phoneOperationSettings.organizationId, org), isNull(phoneOperationSettings.effectiveUntil))); }
  async createSettings(input: typeof phoneOperationSettings.$inferInsert) { const [v] = await this.db.insert(phoneOperationSettings).values(input).returning(); return v; }
  listSettings(org: string) { return this.db.select().from(phoneOperationSettings).where(eq(phoneOperationSettings.organizationId, org)).orderBy(desc(phoneOperationSettings.version)); }
  async credential(org: string) { const [v] = await this.db.select().from(phoneProviderCredentials).where(and(eq(phoneProviderCredentials.organizationId, org), eq(phoneProviderCredentials.provider, "twilio"))).limit(1); return v ?? null; }
  async saveCredential(input: typeof phoneProviderCredentials.$inferInsert) { const [v] = await this.db.insert(phoneProviderCredentials).values(input).onConflictDoUpdate({ target: [phoneProviderCredentials.organizationId, phoneProviderCredentials.provider], set: { accountSid: input.accountSid, authTokenCiphertext: input.authTokenCiphertext, authTokenIv: input.authTokenIv, authTokenTag: input.authTokenTag, updatedBy: input.updatedBy, updatedAt: new Date() } }).returning(); return v; }
  async createRuntimeCredential(input: typeof phoneRuntimeCredentials.$inferInsert) { const [v] = await this.db.insert(phoneRuntimeCredentials).values(input).returning(); return v; }
  async runtimeCredential(hash: string) { const [v] = await this.db.select().from(phoneRuntimeCredentials).where(and(eq(phoneRuntimeCredentials.tokenHash, hash), isNull(phoneRuntimeCredentials.revokedAt))).limit(1); return v ?? null; }
  async revokeRuntimeCredential(org: string, id: string) { const [v] = await this.db.update(phoneRuntimeCredentials).set({ revokedAt: new Date() }).where(and(eq(phoneRuntimeCredentials.organizationId, org), eq(phoneRuntimeCredentials.id, id), isNull(phoneRuntimeCredentials.revokedAt))).returning(); return v ?? null; }
  listRuntimeCredentials(org: string) { return this.db.select({ id: phoneRuntimeCredentials.id, name: phoneRuntimeCredentials.name, tokenPrefix: phoneRuntimeCredentials.tokenPrefix, revokedAt: phoneRuntimeCredentials.revokedAt, createdAt: phoneRuntimeCredentials.createdAt }).from(phoneRuntimeCredentials).where(eq(phoneRuntimeCredentials.organizationId, org)).orderBy(desc(phoneRuntimeCredentials.createdAt)); }
  async currentAgent(org: string, id?: string | null) { const [v] = await this.db.select().from(voiceAgents).where(and(eq(voiceAgents.organizationId, org), isNull(voiceAgents.effectiveUntil), id ? eq(voiceAgents.id, id) : eq(voiceAgents.isDefault, true), eq(voiceAgents.status, "active"))).limit(1); return v ?? null; }
  async publishAgent(input: typeof voiceAgents.$inferInsert) { const [v] = await this.db.insert(voiceAgents).values(input).returning(); return v; }
  async closeAgent(org: string, logicalName: string) { await this.db.update(voiceAgents).set({ effectiveUntil: new Date() }).where(and(eq(voiceAgents.organizationId, org), eq(voiceAgents.logicalName, logicalName), isNull(voiceAgents.effectiveUntil))); }
  async demoteDefault(org: string) { await this.db.update(voiceAgents).set({ isDefault: false }).where(and(eq(voiceAgents.organizationId, org), isNull(voiceAgents.effectiveUntil), eq(voiceAgents.isDefault, true))); }
  async nextAgentVersion(org: string, name: string) { const [v] = await this.db.select({ value: sql<number>`coalesce(max(${voiceAgents.version}), 0) + 1` }).from(voiceAgents).where(and(eq(voiceAgents.organizationId, org), eq(voiceAgents.logicalName, name))); return Number(v.value); }
  listAgents(org: string) { return this.db.select().from(voiceAgents).where(and(eq(voiceAgents.organizationId, org), isNull(voiceAgents.effectiveUntil))).orderBy(asc(voiceAgents.logicalName)); }
  async number(org: string, id: string) { const [v] = await this.db.select().from(phoneNumbers).where(and(eq(phoneNumbers.organizationId, org), eq(phoneNumbers.id, id))).limit(1); return v ?? null; }
  async numberByE164(e164: string) { const [v] = await this.db.select().from(phoneNumbers).where(and(eq(phoneNumbers.provider, "twilio"), eq(phoneNumbers.e164, e164), eq(phoneNumbers.status, "active"))).limit(1); return v ?? null; }
  async saveNumber(input: typeof phoneNumbers.$inferInsert) { const [v] = await this.db.insert(phoneNumbers).values(input).onConflictDoUpdate({ target: [phoneNumbers.provider, phoneNumbers.e164], set: { providerNumberId: input.providerNumberId, label: input.label, inboundEnabled: input.inboundEnabled, outboundEnabled: input.outboundEnabled, voiceAgentId: input.voiceAgentId, updatedBy: input.updatedBy, updatedAt: new Date() } }).returning(); return v; }
  listNumbers(org: string) { return this.db.select().from(phoneNumbers).where(eq(phoneNumbers.organizationId, org)).orderBy(asc(phoneNumbers.e164)); }
  async call(org: string, id: string, lock = false) { const q = this.db.select().from(phoneCalls).where(and(eq(phoneCalls.organizationId, org), eq(phoneCalls.id, id))).limit(1); return lock ? q.for("update").then(x => x[0] ?? null) : q.then(x => x[0] ?? null); }
  async callByProvider(providerCallId: string) { const requestId = providerCallId.startsWith("request:") ? providerCallId.slice(8) : null; const [v] = await this.db.select().from(phoneCalls).where(and(eq(phoneCalls.provider, "twilio"), requestId ? eq(phoneCalls.clientRequestId, requestId) : eq(phoneCalls.providerCallId, providerCallId))).limit(1); return v ?? null; }
  async createCall(input: typeof phoneCalls.$inferInsert) { const clientRequestId = input.clientRequestId ?? (input.providerCallId?.startsWith("request:") ? input.providerCallId.slice(8) : null), query = this.db.insert(phoneCalls).values({ ...input, clientRequestId }); const [v] = await (clientRequestId ? query.onConflictDoNothing({ target: phoneCalls.clientRequestId }) : query.onConflictDoNothing({ target: [phoneCalls.provider, phoneCalls.providerCallId] })).returning(); return v ?? null; }
  async callByRequest(org: string, requestId: string) { const [v] = await this.db.select().from(phoneCalls).where(and(eq(phoneCalls.organizationId, org), eq(phoneCalls.clientRequestId, requestId))).limit(1); return v ?? null; }
  async updateCall(org: string, id: string, input: Partial<typeof phoneCalls.$inferInsert>) { const [v] = await this.db.update(phoneCalls).set({ ...input, id: undefined, organizationId: undefined, provider: undefined, providerCallId: undefined, direction: undefined, phoneNumberId: undefined, createdAt: undefined, updatedAt: new Date() }).where(and(eq(phoneCalls.organizationId, org), eq(phoneCalls.id, id))).returning(); return v ?? null; }
  async listCalls(org: string, q: { query?: string; status?: typeof phoneCalls.$inferSelect.status; direction?: typeof phoneCalls.$inferSelect.direction; limit: number; offset: number }) { const where = and(eq(phoneCalls.organizationId, org), q.query ? or(ilike(phoneCalls.normalizedFrom, `%${q.query}%`), ilike(phoneCalls.normalizedTo, `%${q.query}%`), ilike(phoneCalls.providerCallId, `%${q.query}%`)) : undefined, q.status ? eq(phoneCalls.status, q.status) : undefined, q.direction ? eq(phoneCalls.direction, q.direction) : undefined); const [items, [{ total }]] = await Promise.all([this.db.select().from(phoneCalls).where(where).orderBy(desc(phoneCalls.createdAt), desc(phoneCalls.id)).limit(q.limit).offset(q.offset), this.db.select({ total: count() }).from(phoneCalls).where(where)]); return { items, total: Number(total) }; }
  async customerMatches(org: string, normalized: string) { return this.db.select({ id: customers.id, name: customers.name }).from(customers).where(and(eq(customers.organizationId, org), eq(customers.status, "active"), isNull(customers.archivedAt), sql`case when length(regexp_replace(${customers.phone}, '[^0-9]', '', 'g')) = 11 and regexp_replace(${customers.phone}, '[^0-9]', '', 'g') like '1%' then substring(regexp_replace(${customers.phone}, '[^0-9]', '', 'g') from 2) else regexp_replace(${customers.phone}, '[^0-9]', '', 'g') end = ${normalized}`)).limit(2); }
  async customer(org: string, id: string) { const [v] = await this.db.select().from(customers).where(and(eq(customers.organizationId, org), eq(customers.id, id), eq(customers.status, "active"), isNull(customers.archivedAt))).limit(1); return v ?? null; }
  async lead(org: string, id: string) { const [v] = await this.db.select().from(leads).where(and(eq(leads.organizationId, org), eq(leads.id, id), isNull(leads.archivedAt))).limit(1); return v ?? null; }
  async job(org: string, id: string) { const [v] = await this.db.select().from(jobs).where(and(eq(jobs.organizationId, org), eq(jobs.id, id), isNull(jobs.archivedAt))).limit(1); return v ?? null; }
  async member(org: string, userId: string) { const [v] = await this.db.select().from(organizationMembers).where(and(eq(organizationMembers.organizationId, org), eq(organizationMembers.userId, userId))).limit(1); return v ?? null; }
  async addEvent(input: typeof phoneCallEvents.$inferInsert) { const [v] = await this.db.insert(phoneCallEvents).values(input).onConflictDoNothing({ target: [phoneCallEvents.organizationId, phoneCallEvents.providerEventId] }).returning(); return v ?? null; }
  listEvents(org: string, callId: string) { return this.db.select().from(phoneCallEvents).where(and(eq(phoneCallEvents.organizationId, org), eq(phoneCallEvents.callId, callId))).orderBy(asc(phoneCallEvents.providerOccurredAt), asc(phoneCallEvents.id)); }
  async addTranscript(input: typeof phoneCallTranscripts.$inferInsert) { const [v] = await this.db.insert(phoneCallTranscripts).values(input).onConflictDoNothing({ target: [phoneCallTranscripts.organizationId, phoneCallTranscripts.callId, phoneCallTranscripts.sequence] }).returning(); return v ?? null; }
  listTranscript(org: string, callId: string) { return this.db.select().from(phoneCallTranscripts).where(and(eq(phoneCallTranscripts.organizationId, org), eq(phoneCallTranscripts.callId, callId))).orderBy(asc(phoneCallTranscripts.sequence)); }
  async addOutcome(input: typeof phoneCallOutcomes.$inferInsert) { const [v] = await this.db.insert(phoneCallOutcomes).values(input).onConflictDoNothing({ target: [phoneCallOutcomes.organizationId, phoneCallOutcomes.callId] }).returning(); return v ?? null; }
  async outcome(org: string, callId: string) { const [v] = await this.db.select().from(phoneCallOutcomes).where(and(eq(phoneCallOutcomes.organizationId, org), eq(phoneCallOutcomes.callId, callId))).limit(1); return v ?? null; }
  async claimInvocation(input: typeof phoneToolInvocations.$inferInsert) { const [v] = await this.db.insert(phoneToolInvocations).values(input).onConflictDoNothing({ target: [phoneToolInvocations.organizationId, phoneToolInvocations.callId, phoneToolInvocations.idempotencyKey] }).returning(); return v ?? null; }
  async invocation(org: string, callId: string, key: string) { const [v] = await this.db.select().from(phoneToolInvocations).where(and(eq(phoneToolInvocations.organizationId, org), eq(phoneToolInvocations.callId, callId), eq(phoneToolInvocations.idempotencyKey, key))).limit(1); return v ?? null; }
  async finishInvocation(org: string, id: string, result: Record<string, unknown>) { const [v] = await this.db.update(phoneToolInvocations).set({ status: "succeeded", result, completedAt: new Date() }).where(and(eq(phoneToolInvocations.organizationId, org), eq(phoneToolInvocations.id, id), eq(phoneToolInvocations.status, "pending"))).returning(); return v ?? null; }
  async createTask(input: typeof tasks.$inferInsert) { const [v] = await this.db.insert(tasks).values(input).returning(); return v; }
  async linkTask(org: string, callId: string, taskId: string) { await this.db.insert(phoneCallTaskLinks).values({ organizationId: org, callId, taskId }); }
  async createActivity(input: typeof activities.$inferInsert) { const [v] = await this.db.insert(activities).values(input).returning(); return v; }
  listCallEvents(org: string, id: string) { return this.listEvents(org, id); }
  listCallTranscripts(org: string, id: string) { return this.listTranscript(org, id); }
  callOutcome(org: string, id: string) { return this.outcome(org, id); }
  addCallEvent(input: typeof phoneCallEvents.$inferInsert) { return this.addEvent(input); }
  addCallTranscript(input: typeof phoneCallTranscripts.$inferInsert) { return this.addTranscript(input); }
  createCallOutcome(input: typeof phoneCallOutcomes.$inferInsert) { return this.addOutcome(input); }
  claimToolInvocation(input: typeof phoneToolInvocations.$inferInsert) { return this.claimInvocation(input); }
  toolInvocation(org: string, callId: string, key: string) { return this.invocation(org, callId, key); }
  finishToolInvocation(org: string, id: string, result: Record<string, unknown>) { return this.finishInvocation(org, id, result); }
  async activeCallCount(org: string) { const [v] = await this.db.select({ total: count() }).from(phoneCalls).where(and(eq(phoneCalls.organizationId, org), sql`${phoneCalls.status} in ('queued','ringing','in_progress')`)); return Number(v.total); }
  async dailyCallCount(org: string, since: Date) { const [v] = await this.db.select({ total: count() }).from(phoneCalls).where(and(eq(phoneCalls.organizationId, org), gte(phoneCalls.createdAt, since))); return Number(v.total); }
  async setProviderCallId(org: string, id: string, providerCallId: string) { const [v] = await this.db.update(phoneCalls).set({ providerCallId, updatedAt: new Date() }).where(and(eq(phoneCalls.organizationId, org), eq(phoneCalls.id, id))).returning(); return v ?? null; }
  async claimPlacement(org: string, id: string) { const [v] = await this.db.update(phoneCalls).set({ placementStartedAt: new Date(), updatedAt: new Date() }).where(and(eq(phoneCalls.organizationId, org), eq(phoneCalls.id, id), isNull(phoneCalls.placementStartedAt))).returning(); return v ?? null; }
}
