"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { currentActor } from "@/auth/current-actor";
import { ApplicationError } from "@/lib/errors";
import { DealService } from "@/modules/deals/deal.service";
export interface DealActionState { error?: string; issues?: ReadonlyArray<{ path: string; message: string }> }
function failure(error: unknown): DealActionState { if (error instanceof ApplicationError) return { error: error.message, issues: "issues" in error ? error.issues as DealActionState["issues"] : undefined }; throw error; }
export async function createDealAction(_state: DealActionState, formData: FormData): Promise<DealActionState> { try { const actor = await currentActor(); const deal = await new DealService().createDeal(actor!, { name: String(formData.get("name") ?? ""), pipelineId: String(formData.get("pipelineId") ?? ""), stageId: String(formData.get("stageId") ?? ""), customerId: String(formData.get("customerId") ?? ""), amountCents: Number(formData.get("amountCents") ?? 0), currency: String(formData.get("currency") ?? "CAD"), expectedCloseDate: String(formData.get("expectedCloseDate") ?? "") || null, source: String(formData.get("source") ?? "") }); revalidatePath("/deals"); redirect(`/deals/${deal.id}`); } catch (error) { return failure(error); } }
export async function updateDealAction(id: string, _state: DealActionState, formData: FormData): Promise<DealActionState> { try { const actor = await currentActor(); await new DealService().updateDeal(actor!, id, { name: String(formData.get("name") ?? ""), amountCents: Number(formData.get("amountCents") ?? 0), expectedCloseDate: String(formData.get("expectedCloseDate") ?? "") || null }); revalidatePath(`/deals/${id}`); revalidatePath("/deals"); return {}; } catch (error) { return failure(error); } }
export async function moveDealAction(id: string, pipelineId: string, _state: DealActionState, formData: FormData): Promise<DealActionState> { try { const actor = await currentActor(); await new DealService().moveDeal(actor!, id, { pipelineId, stageId: String(formData.get("stageId") ?? ""), lostReason: String(formData.get("lostReason") ?? "") || undefined }); revalidatePath(`/deals/${id}`); revalidatePath("/deals"); return {}; } catch (error) { return failure(error); } }
export async function assignDealAction(id: string, _state: DealActionState, formData: FormData): Promise<DealActionState> { try { const actor = await currentActor(); await new DealService().assignDeal(actor!, id, { ownerUserId: String(formData.get("ownerUserId") ?? "") || null }); revalidatePath(`/deals/${id}`); return {}; } catch (error) { return failure(error); } }
