import Link from "next/link";
import { redirect } from "next/navigation";
import { can } from "@/auth/permissions";
import { currentActor } from "@/auth/current-actor";
import { CustomerService } from "@/modules/customers/customer.service";
import { DealService } from "@/modules/deals/deal.service";
import { PipelineService } from "@/modules/pipelines/pipeline.service";
import { DealForm, type DealPipelineChoice } from "./deal-form";
export default async function DealsPage({ searchParams }: { searchParams: Promise<{ query?: string; kind?: string; page?: string }> }) { const actor = await currentActor(); if (!actor) redirect("/login"); const query = await searchParams; const kind = ["open", "won", "lost"].includes(query.kind ?? "") ? query.kind as "open" | "won" | "lost" : undefined; const page = Math.max(1, Number.parseInt(query.page ?? "1", 10) || 1); const service = new DealService(); const result = await service.listDeals(actor, { query: query.query, kind, page, pageSize: 25 }); const pipelineService = new PipelineService(); const pipelineRows = await pipelineService.listPipelines(actor); const pipelineChoices: DealPipelineChoice[] = await Promise.all(pipelineRows.map(async (pipeline) => ({ id: pipeline.id, name: pipeline.name, stages: (await pipelineService.getPipeline(actor, pipeline.id)).stages.map(({ id, name, kind }) => ({ id, name, kind })) }))); const customers = (await new CustomerService().listCustomers(actor, { page: 1, pageSize: 100 })).items.map(({ id, name }) => ({ id, name })); return <main className="mx-auto max-w-6xl px-6 py-12"><header><p className="text-sm font-medium text-primary">CRM</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Deals</h1></header><form className="mt-8 flex gap-2"><input name="query" defaultValue={query.query} placeholder="Search identifier or name" className="min-w-0 flex-1 rounded-md border bg-background px-3 py-2" /><select name="kind" defaultValue={query.kind ?? ""} className="rounded-md border bg-background px-3 py-2"><option value="">All states</option><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select><button className="rounded-md border bg-card px-4 py-2">Filter</button></form><div className="mt-6 overflow-hidden rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="bg-muted text-muted-foreground"><tr><th className="px-4 py-3">Deal</th><th className="px-4 py-3">Value</th><th className="px-4 py-3">Expected close</th></tr></thead><tbody>{result.items.map((deal) => <tr className="border-t" key={deal.id}><td className="px-4 py-3"><Link href={`/deals/${deal.id}`} className="font-medium">{deal.name}</Link><div className="text-xs text-muted-foreground">{deal.identifier}</div></td><td className="px-4 py-3">{deal.amountCents} {deal.currency}</td><td className="px-4 py-3">{deal.expectedCloseDate || "—"}</td></tr>)}</tbody></table>{!result.items.length ? <p className="p-6 text-muted-foreground">No deals found.</p> : null}</div>{can(actor, "deal.create") ? <DealForm pipelines={pipelineChoices} customers={customers} /> : null}</main>; }
