import { describe, expect, it } from "vitest";
import { AuditRepository } from "@/modules/audit/audit.repository";
import { ConflictError, ForbiddenError, NotFoundError } from "@/lib/errors";
import type { ObjectStorage } from "@/lib/r2";
import { CustomerService } from "@/modules/customers/customer.service";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { NoteService } from "@/modules/interactions/note.service";
import { AttachmentService } from "./attachment.service";
class FakeStorage implements ObjectStorage { puts:{key:string;type:string;size:number}[]=[];deletes:string[]=[];failDelete=false;async put(key:string,body:Uint8Array,type:string){this.puts.push({key,type,size:body.byteLength});}async delete(key:string){if(this.failDelete)throw new Error("offline");this.deletes.push(key);}async signedDownloadUrl(key:string,expires=300){return `https://storage.example.test/${encodeURIComponent(key)}?ttl=${expires}`;} }
describe.sequential("PostgreSQL attachments with controlled storage",()=>{let a:Awaited<ReturnType<OrganizationService["createOrganizationWithOwner"]>>;let b:typeof a;let customerA:Awaited<ReturnType<CustomerService["createCustomer"]>>;let customerB:typeof customerA;const storage=new FakeStorage();const service=new AttachmentService(undefined,undefined,undefined,storage);const notes=new NoteService();const actorA=()=>({userId:a.user.id,organizationId:a.organization.id,role:"owner" as const});const actorB=()=>({userId:b.user.id,organizationId:b.organization.id,role:"owner" as const});const pdf=new TextEncoder().encode("%PDF-1.7 synthetic");
  it("creates tenant fixtures",async()=>{const orgs=new OrganizationService();a=await orgs.createOrganizationWithOwner({name:"File Alpha",slug:"file-alpha"},{name:"Owner A",email:"file-alpha@example.test",password:"Synthetic-Pass-123"});b=await orgs.createOrganizationWithOwner({name:"File Beta",slug:"file-beta"},{name:"Owner B",email:"file-beta@example.test",password:"Synthetic-Pass-456"});customerA=await new CustomerService().createCustomer(actorA(),{name:"Alpha Customer"});customerB=await new CustomerService().createCustomer(actorB(),{name:"Beta Customer"});});
  it("uploads metadata, scoped object and audit atomically",async()=>{const value=await service.uploadAttachment(actorA(),{filename:"../service-report.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"customer",targetId:customerA.id},pdf);expect(value.filename).toBe("service-report.pdf");expect(value.objectKey).toMatch(new RegExp(`^organizations/${a.organization.id}/customer/${customerA.id}/`));expect(storage.puts.at(-1)).toMatchObject({key:value.objectKey,type:"application/pdf",size:pdf.byteLength});expect((await new AuditRepository().listForEntity(a.organization.id,"attachment",value.id)).map(x=>x.action)).toEqual(["attachment.created"]);});
  it("authorizes bounded downloads only after tenant lookup",async()=>{const value=(await service.listAttachments(actorA(),{targetType:"customer",targetId:customerA.id}))[0];const result=await service.createDownloadUrl(actorA(),value.id,{expiresIn:120});expect(result.url).toContain("ttl=120");await expect(service.createDownloadUrl(actorB(),value.id,{})).rejects.toBeInstanceOf(NotFoundError);});
  it("rejects foreign targets and never writes storage",async()=>{const before=storage.puts.length;await expect(service.uploadAttachment(actorA(),{filename:"x.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"customer",targetId:customerB.id},pdf)).rejects.toBeInstanceOf(NotFoundError);expect(storage.puts).toHaveLength(before);});
  it("supports tenant-local Note attachments and blocks Note archive until cleanup",async()=>{const note=await notes.createNote(actorA(),{body:"Attach evidence",targetType:"customer",targetId:customerA.id});const file=await service.uploadAttachment(actorA(),{filename:"note.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"note",targetId:note.id},pdf);expect((await service.listAttachments(actorA(),{targetType:"note",targetId:note.id})).map(x=>x.id)).toEqual([file.id]);await expect(notes.archiveNote(actorA(),note.id)).rejects.toBeInstanceOf(ConflictError);await service.archiveAttachment(actorA(),file.id);await notes.archiveNote(actorA(),note.id);});
  it("archives before physical deletion and supports safe retry",async()=>{const file=await service.uploadAttachment(actorA(),{filename:"retry.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"customer",targetId:customerA.id},pdf);storage.failDelete=true;await expect(service.archiveAttachment(actorA(),file.id)).rejects.toBeInstanceOf(ConflictError);storage.failDelete=false;await service.archiveAttachment(actorA(),file.id);expect(storage.deletes).toContain(file.objectKey);await expect(service.getAttachment(actorA(),file.id)).rejects.toBeInstanceOf(NotFoundError);});
  it("enforces metadata isolation, delete isolation, bounded lists, and RBAC",async()=>{const foreign=await service.uploadAttachment(actorB(),{filename:"private.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"customer",targetId:customerB.id},pdf);await expect(service.getAttachment(actorA(),foreign.id)).rejects.toBeInstanceOf(NotFoundError);await expect(service.archiveAttachment(actorA(),foreign.id)).rejects.toBeInstanceOf(NotFoundError);expect((await service.listAttachments(actorA(),{targetType:"customer",targetId:customerA.id})).some(x=>x.id===foreign.id)).toBe(false);const viewerResult=await new UserService().createUserWithMembership(actorA(),{name:"Viewer",email:"file-viewer@example.test",password:"Synthetic-Pass-789"},"viewer");const viewer={userId:viewerResult.user.id,organizationId:a.organization.id,role:"viewer" as const};await service.listAttachments(viewer,{targetType:"customer",targetId:customerA.id});await expect(service.uploadAttachment(viewer,{filename:"denied.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"customer",targetId:customerA.id},pdf)).rejects.toBeInstanceOf(ForbiddenError);});
});
