import { authorize } from "@/auth/authorization";
import { NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { nullable, parseEntityId } from "@/modules/crm/crm.helpers";
import type { Authorizer, RequestActor } from "@/modules/customers/customer.service";
import { createActivitySchema, timelineFilterSchema, updateActivitySchema, type CreateActivityInput, type UpdateActivityInput } from "./interaction.schema";
import { DrizzleInteractionUnitOfWork, type InteractionUnitOfWork } from "./interaction.unit-of-work";
import { ActivityRepository } from "./activity.repository";
export class ActivityService { constructor(private readonly repository = new ActivityRepository(), private readonly authorizer: Authorizer = authorize, private readonly unitOfWork: InteractionUnitOfWork = new DrizzleInteractionUnitOfWork()) {}
  async getActivity(actor: RequestActor, id: string) { await this.authorizer(actor, "activity.read"); const value = await this.repository.findById(actor.organizationId, parseEntityId(id)); if (!value) throw new NotFoundError("Activity not found"); return value; }
  async listForTarget(actor: RequestActor, raw: unknown) { await this.authorizer(actor, "activity.read"); const i = parseInput(timelineFilterSchema, raw); if (!await this.unitOfWork.transaction((r) => r.relations.exists(actor.organizationId, i))) throw new NotFoundError("Related CRM record not found"); return this.repository.listForTarget(actor.organizationId, i.targetType, i.targetId, i.limit); }
  async createActivity(actor: RequestActor, raw: CreateActivityInput) { await this.authorizer(actor, "activity.create"); const i = parseInput(createActivitySchema, raw); return this.unitOfWork.transaction(async (r) => { if (!await r.relations.exists(actor.organizationId, i)) throw new NotFoundError("Related CRM record not found"); const value = await r.activities.create({ organizationId: actor.organizationId, ...i, details: nullable(i.details), occurredAt: new Date(i.occurredAt), actorUserId: actor.userId, createdBy: actor.userId, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "activity.created", entityType: "activity", entityId: value.id, metadata: { type: value.type, targetType: value.targetType, targetId: value.targetId } }); return value; }); }
  async updateActivity(actor: RequestActor, id: string, raw: UpdateActivityInput) { await this.authorizer(actor, "activity.update"); id = parseEntityId(id); const i = parseInput(updateActivitySchema, raw); return this.unitOfWork.transaction(async (r) => { if (!await r.activities.findById(actor.organizationId, id)) throw new NotFoundError("Activity not found"); const value = await r.activities.update(actor.organizationId, id, { ...i, details: nullable(i.details), occurredAt: i.occurredAt ? new Date(i.occurredAt) : undefined, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "activity.updated", entityType: "activity", entityId: id, metadata: {} }); return value!; }); }
  async archiveActivity(actor: RequestActor, id: string) { await this.authorizer(actor, "activity.delete"); id = parseEntityId(id); return this.unitOfWork.transaction(async (r) => { if (!await r.activities.findById(actor.organizationId, id)) throw new NotFoundError("Activity not found"); await r.activities.archive(actor.organizationId, id, actor.userId); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "activity.archived", entityType: "activity", entityId: id, metadata: {} }); }); }
}
