import { authorize } from "@/auth/authorization";
import { ConflictError, ForbiddenError, NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { parseEntityId } from "@/modules/crm/crm.helpers";
import type { Authorizer, RequestActor } from "@/modules/customers/customer.service";
import { createNoteSchema, timelineFilterSchema, updateNoteSchema, type CreateNoteInput, type UpdateNoteInput } from "./interaction.schema";
import { DrizzleInteractionUnitOfWork, type InteractionUnitOfWork } from "./interaction.unit-of-work";
import { NoteRepository } from "./note.repository";
export class NoteService { constructor(private readonly repository = new NoteRepository(), private readonly authorizer: Authorizer = authorize, private readonly unitOfWork: InteractionUnitOfWork = new DrizzleInteractionUnitOfWork()) {}
  async getNote(actor: RequestActor, id: string) { await this.authorizer(actor, "note.read"); const value = await this.repository.findById(actor.organizationId, parseEntityId(id)); if (!value) throw new NotFoundError("Note not found"); return value; }
  async listForTarget(actor: RequestActor, raw: unknown) { await this.authorizer(actor, "note.read"); const i = parseInput(timelineFilterSchema, raw); if (!await this.unitOfWork.transaction((r) => r.relations.exists(actor.organizationId, i))) throw new NotFoundError("Related CRM record not found"); return this.repository.listForTarget(actor.organizationId, i.targetType, i.targetId, i.limit); }
  async createNote(actor: RequestActor, raw: CreateNoteInput) { await this.authorizer(actor, "note.create"); const i = parseInput(createNoteSchema, raw); return this.unitOfWork.transaction(async (r) => { if (!await r.relations.exists(actor.organizationId, i)) throw new NotFoundError("Related CRM record not found"); const value = await r.notes.create({ organizationId: actor.organizationId, ...i, authorUserId: actor.userId, createdBy: actor.userId, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "note.created", entityType: "note", entityId: value.id, metadata: { targetType: value.targetType, targetId: value.targetId } }); return value; }); }
  async updateNote(actor: RequestActor, id: string, raw: UpdateNoteInput) { await this.authorizer(actor, "note.update"); id = parseEntityId(id); const i = parseInput(updateNoteSchema, raw); return this.unitOfWork.transaction(async (r) => { const current = await r.notes.findById(actor.organizationId, id); if (!current) throw new NotFoundError("Note not found"); if (current.authorUserId !== actor.userId && !["owner", "admin"].includes(actor.role)) throw new ForbiddenError("Only the author or an administrator may edit this note"); const value = await r.notes.update(actor.organizationId, id, { body: i.body, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "note.updated", entityType: "note", entityId: id, metadata: {} }); return value!; }); }
  async archiveNote(actor: RequestActor, id: string) { await this.authorizer(actor, "note.delete"); id = parseEntityId(id); return this.unitOfWork.transaction(async (r) => { if (!await r.notes.findById(actor.organizationId, id)) throw new NotFoundError("Note not found"); if(await r.attachments.countForTarget(actor.organizationId,"note",id))throw new ConflictError("Archive Note attachments before archiving the Note"); await r.notes.archive(actor.organizationId, id, actor.userId); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "note.archived", entityType: "note", entityId: id, metadata: {} }); }); }
}
