import { authorize } from "@/auth/authorization";
import { NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { nullable, parseEntityId } from "@/modules/crm/crm.helpers";
import type { Authorizer, RequestActor } from "@/modules/customers/customer.service";
import { assignTaskSchema, changeTaskStatusSchema, createTaskSchema, taskFilterSchema, updateTaskSchema, type CreateTaskInput, type TaskFilter, type UpdateTaskInput } from "./interaction.schema";
import { DrizzleInteractionUnitOfWork, type InteractionRepositories, type InteractionUnitOfWork } from "./interaction.unit-of-work";
import { TaskRepository } from "./task.repository";
import { assertTaskTransition } from "./task.rules";
export class TaskService {
  constructor(private readonly repository = new TaskRepository(), private readonly authorizer: Authorizer = authorize, private readonly unitOfWork: InteractionUnitOfWork = new DrizzleInteractionUnitOfWork()) {}
  async getTask(actor: RequestActor, id: string) { await this.authorizer(actor, "task.read"); const task = await this.repository.findById(actor.organizationId, parseEntityId(id)); if (!task) throw new NotFoundError("Task not found"); return task; }
  async listTasks(actor: RequestActor, raw: TaskFilter) { await this.authorizer(actor, "task.read"); const i = parseInput(taskFilterSchema, raw); return { ...(await this.repository.list(actor.organizationId, { ...i, dueBefore: i.dueBefore ? new Date(i.dueBefore) : undefined, limit: i.pageSize, offset: (i.page - 1) * i.pageSize })), page: i.page, pageSize: i.pageSize }; }
  async listAssignableMembers(actor: RequestActor) { await this.authorizer(actor, "task.read"); return this.unitOfWork.transaction((r) => r.memberships.list(actor.organizationId)); }
  async createTask(actor: RequestActor, raw: CreateTaskInput) { await this.authorizer(actor, "task.create"); const i = parseInput(createTaskSchema, raw); if (i.assigneeUserId) await this.authorizer(actor, "task.assign"); return this.unitOfWork.transaction(async (r) => { await this.requireTarget(r, actor.organizationId, i); if (i.assigneeUserId) await this.requireMember(r, actor.organizationId, i.assigneeUserId); const task = await r.tasks.create({ organizationId: actor.organizationId, title: i.title, description: nullable(i.description), priority: i.priority, dueAt: i.dueAt ? new Date(i.dueAt) : null, assigneeUserId: i.assigneeUserId, targetType: i.targetType, targetId: i.targetId, createdBy: actor.userId, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "task.created", entityType: "task", entityId: task.id, metadata: { targetType: task.targetType, targetId: task.targetId } }); return task; }); }
  async updateTask(actor: RequestActor, id: string, raw: UpdateTaskInput) { await this.authorizer(actor, "task.update"); id = parseEntityId(id); const i = parseInput(updateTaskSchema, raw); return this.unitOfWork.transaction(async (r) => { if (!await r.tasks.findByIdForUpdate(actor.organizationId, id)) throw new NotFoundError("Task not found"); const task = await r.tasks.update(actor.organizationId, id, { ...i, description: nullable(i.description), dueAt: i.dueAt ? new Date(i.dueAt) : i.dueAt === null ? null : undefined, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "task.updated", entityType: "task", entityId: id, metadata: {} }); return task!; }); }
  async assignTask(actor: RequestActor, id: string, raw: unknown) { await this.authorizer(actor, "task.assign"); id = parseEntityId(id); const i = parseInput(assignTaskSchema, raw); return this.unitOfWork.transaction(async (r) => { if (!await r.tasks.findByIdForUpdate(actor.organizationId, id)) throw new NotFoundError("Task not found"); if (i.assigneeUserId) await this.requireMember(r, actor.organizationId, i.assigneeUserId); const task = await r.tasks.update(actor.organizationId, id, { assigneeUserId: i.assigneeUserId, updatedBy: actor.userId }); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: i.assigneeUserId ? "task.assigned" : "task.unassigned", entityType: "task", entityId: id, metadata: { assigneeUserId: i.assigneeUserId } }); return task!; }); }
  async changeStatus(actor: RequestActor, id: string, raw: unknown) { await this.authorizer(actor, "task.update"); id = parseEntityId(id); const i = parseInput(changeTaskStatusSchema, raw); return this.unitOfWork.transaction(async (r) => { const current = await r.tasks.findByIdForUpdate(actor.organizationId, id); if (!current) throw new NotFoundError("Task not found"); assertTaskTransition(current.status, i.status); const completed = i.status === "completed"; const task = await r.tasks.update(actor.organizationId, id, { status: i.status, completedAt: completed ? new Date() : null, completedBy: completed ? actor.userId : null, updatedBy: actor.userId }); const action = completed ? "task.completed" : current.status === "completed" ? "task.reopened" : "task.updated"; await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action, entityType: "task", entityId: id, metadata: { from: current.status, to: i.status } }); return task!; }); }
  async archiveTask(actor: RequestActor, id: string) { await this.authorizer(actor, "task.delete"); id = parseEntityId(id); return this.unitOfWork.transaction(async (r) => { if (!await r.tasks.findByIdForUpdate(actor.organizationId, id)) throw new NotFoundError("Task not found"); await r.tasks.archive(actor.organizationId, id, actor.userId); await r.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "task.archived", entityType: "task", entityId: id, metadata: {} }); }); }
  private async requireTarget(r: InteractionRepositories, org: string, target: { targetType: "customer"|"contact"|"company"|"lead"|"deal"; targetId: string }) { if (!await r.relations.exists(org, target)) throw new NotFoundError("Related CRM record not found"); }
  private async requireMember(r: InteractionRepositories, org: string, userId: string) { if (!await r.memberships.find(org, userId)) throw new NotFoundError("Assignable member not found"); }
}
