"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { currentActor } from "@/auth/current-actor";
import { MaintenanceAutomationService, MaintenanceService } from "@/modules/maintenance";

export async function createMaintenancePlanAction(data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new MaintenanceService().createPlan(actor, { code: String(data.get("code") ?? ""), name: String(data.get("name") ?? ""), description: String(data.get("description") ?? ""), priceCents: Number(data.get("priceCents") ?? 0), currency: "CAD", visitEntitlementCount: data.get("visitEntitlementCount") ? Number(data.get("visitEntitlementCount")) : null, frequencyDescription: String(data.get("frequencyDescription") ?? ""), discountType: "none" }); revalidatePath("/maintenance"); }
export async function createMaintenanceAgreementAction(data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); const result = await new MaintenanceService().createAgreement(actor, { customerId: String(data.get("customerId") ?? ""), planId: String(data.get("planId") ?? ""), effectiveDate: String(data.get("effectiveDate") ?? ""), expiresOn: String(data.get("expiresOn") ?? ""), renewalPreference: String(data.get("renewalPreference") ?? "none"), termsSnapshot: String(data.get("termsSnapshot") ?? ""), serviceLocation: String(data.get("serviceLocation") ?? "") }); redirect(`/maintenance/${result.agreement.id}`); }
export async function sendMaintenanceAgreementAction(id: string, data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); const result = await new MaintenanceService().sendAgreement(actor, id, { signerName: String(data.get("signerName") ?? ""), signerEmail: String(data.get("signerEmail") ?? ""), expiresInDays: 14 }); redirect(`/maintenance/${id}?token=${encodeURIComponent(result.token)}`); }
export async function cancelMaintenanceAgreementAction(id: string, data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new MaintenanceService().cancelAgreement(actor, id, { reason: String(data.get("reason") ?? "") }); revalidatePath(`/maintenance/${id}`); }
export async function renewMaintenanceAgreementAction(id: string) { const actor = await currentActor(); if (!actor) redirect("/login"); const result = await new MaintenanceService().initiateRenewal(actor, id); redirect(`/maintenance/${result.agreement.id}`); }
export async function createMaintenanceScheduleAction(membershipId: string, agreementId: string, data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new MaintenanceService().createSchedule(actor, membershipId, { recurrence: String(data.get("recurrence") ?? "annual"), customIntervalDays: data.get("customIntervalDays") ? Number(data.get("customIntervalDays")) : null, startDate: String(data.get("startDate") ?? "") || undefined }); revalidatePath(`/maintenance/${agreementId}`); }
export async function setMaintenanceScheduleStatusAction(scheduleId: string, agreementId: string, data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new MaintenanceService().setScheduleStatus(actor, scheduleId, String(data.get("status")) as "active" | "paused" | "cancelled", String(data.get("reason") ?? "") || undefined); revalidatePath(`/maintenance/${agreementId}`); }
export async function runMaintenanceAutomationAction() { const actor = await currentActor(); if (!actor) redirect("/login"); await new MaintenanceAutomationService().runManual(actor); revalidatePath("/maintenance"); }
