import { describe, expect, it } from "vitest";
import { AuditRepository } from "@/modules/audit/audit.repository";
import { ContactService } from "@/modules/contacts/contact.service";
import { CustomerService } from "@/modules/customers/customer.service";
import { ConflictError, ForbiddenError, NotFoundError, ValidationError } from "@/lib/errors";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { PipelineService } from "@/modules/pipelines/pipeline.service";
import { DealService } from "./deal.service";

const organizations = new OrganizationService(); const pipelineService = new PipelineService(); const customerService = new CustomerService(); const contactService = new ContactService(); const deals = new DealService();
describe.sequential("PostgreSQL deals domain", () => {
  let orgA: Awaited<ReturnType<typeof organizations.createOrganizationWithOwner>>; let orgB: typeof orgA; let pipelineA: Awaited<ReturnType<typeof pipelineService.createPipeline>>; let pipelineB: typeof pipelineA; let customerA: Awaited<ReturnType<typeof customerService.createCustomer>>; let customerB: typeof customerA;
  const actorA = () => ({ userId: orgA.user.id, organizationId: orgA.organization.id, role: "owner" as const }); const actorB = () => ({ userId: orgB.user.id, organizationId: orgB.organization.id, role: "owner" as const });
  const stages = (prefix: string) => [{ name: `${prefix} Open`, kind: "open" as const, probability: 20 }, { name: `${prefix} Review`, kind: "open" as const, probability: 60 }, { name: `${prefix} Won`, kind: "won" as const, probability: 100 }, { name: `${prefix} Lost`, kind: "lost" as const, probability: 0 }];
  it("creates isolated Deal fixtures", async () => { orgA = await organizations.createOrganizationWithOwner({ name: "Deal Alpha", slug: "deal-alpha" }, { name: "Alpha Owner", email: "deal-alpha@example.test", password: "Synthetic-Pass-123" }); orgB = await organizations.createOrganizationWithOwner({ name: "Deal Beta", slug: "deal-beta" }, { name: "Beta Owner", email: "deal-beta@example.test", password: "Synthetic-Pass-456" }); pipelineA = await pipelineService.createPipeline(actorA(), { name: "Alpha Sales", stages: stages("Alpha") }); pipelineB = await pipelineService.createPipeline(actorB(), { name: "Beta Sales", stages: stages("Beta") }); customerA = await customerService.createCustomer(actorA(), { name: "Alpha Customer" }); customerB = await customerService.createCustomer(actorB(), { name: "Beta Customer" }); });

  it("creates, reads, updates, searches, filters, and records initial history", async () => { const deal = await deals.createDeal(actorA(), { name: "Synthetic Opportunity", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id, amountCents: 125050, currency: "cad", expectedCloseDate: "2026-12-15", source: "Website" }); expect(deal.identifier).toMatch(/^DEAL-[0-9A-F]{8}$/); expect(deal.amountCents).toBe(125050); expect((await deals.getDeal(actorA(), deal.id)).history).toHaveLength(1); expect((await deals.updateDeal(actorA(), deal.id, { name: "Updated Opportunity", amountCents: 200000 })).amountCents).toBe(200000); const result = await deals.listDeals(actorA(), { query: "Updated", pipelineId: pipelineA.pipeline.id, kind: "open", minAmountCents: 100000, page: 1, pageSize: 10 }); expect(result.items.map((item) => item.id)).toEqual([deal.id]); expect((await new AuditRepository().listForEntity(actorA().organizationId, "deal", deal.id)).map((event) => event.action)).toEqual(["deal.created", "deal.updated"]); });

  it("rejects foreign Pipeline, Stage, and cross-Pipeline Stage combinations", async () => { await expect(deals.createDeal(actorA(), { name: "Foreign Pipeline", pipelineId: pipelineB.pipeline.id, stageId: pipelineB.stages[0].id, customerId: customerA.id })).rejects.toBeInstanceOf(NotFoundError); await expect(deals.createDeal(actorA(), { name: "Foreign Stage", pipelineId: pipelineA.pipeline.id, stageId: pipelineB.stages[0].id, customerId: customerA.id })).rejects.toBeInstanceOf(NotFoundError); const second = await pipelineService.createPipeline(actorA(), { name: "Alpha Other", stages: stages("Other") }); await expect(deals.createDeal(actorA(), { name: "Wrong Pipeline Stage", pipelineId: pipelineA.pipeline.id, stageId: second.stages[0].id, customerId: customerA.id })).rejects.toBeInstanceOf(NotFoundError); });

  it("enforces Customer and Customer-linked Contact locality", async () => { await expect(deals.createDeal(actorA(), { name: "Foreign Customer", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerB.id })).rejects.toBeInstanceOf(NotFoundError); const localContact = await contactService.createContact(actorA(), { customerId: customerA.id, firstName: "Local", lastName: "Contact" }); const otherCustomer = await customerService.createCustomer(actorA(), { name: "Other Customer" }); const wrongContact = await contactService.createContact(actorA(), { customerId: otherCustomer.id, firstName: "Wrong", lastName: "Contact" }); const foreignContact = await contactService.createContact(actorB(), { customerId: customerB.id, firstName: "Foreign", lastName: "Contact" }); expect((await deals.createDeal(actorA(), { name: "Contact Deal", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id, contactId: localContact.id })).contactId).toBe(localContact.id); await expect(deals.createDeal(actorA(), { name: "Wrong Contact", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id, contactId: wrongContact.id })).rejects.toBeInstanceOf(NotFoundError); await expect(deals.createDeal(actorA(), { name: "Foreign Contact", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id, contactId: foreignContact.id })).rejects.toBeInstanceOf(NotFoundError); });

  it("accepts only same-tenant sales owners", async () => { const manager = await new UserService().createUserWithMembership(actorA(), { name: "Deal Manager", email: "deal-manager@example.test", password: "Synthetic-Pass-789" }, "manager"); const deal = await deals.createDeal(actorA(), { name: "Owned Deal", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id, ownerUserId: manager.user.id }); expect(deal.ownerUserId).toBe(manager.user.id); await expect(deals.assignDeal(actorA(), deal.id, { ownerUserId: orgB.user.id })).rejects.toBeInstanceOf(NotFoundError); });

  it("never exposes or mutates another tenant Deal", async () => { const foreign = await deals.createDeal(actorB(), { name: "Beta Private Deal", pipelineId: pipelineB.pipeline.id, stageId: pipelineB.stages[0].id, customerId: customerB.id }); await expect(deals.getDeal(actorA(), foreign.id)).rejects.toBeInstanceOf(NotFoundError); await expect(deals.updateDeal(actorA(), foreign.id, { name: "Breach" })).rejects.toBeInstanceOf(NotFoundError); await expect(deals.assignDeal(actorA(), foreign.id, { ownerUserId: orgA.user.id })).rejects.toBeInstanceOf(NotFoundError); await expect(deals.moveDeal(actorA(), foreign.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[1].id })).rejects.toBeInstanceOf(NotFoundError); await expect(deals.archiveDeal(actorA(), foreign.id)).rejects.toBeInstanceOf(NotFoundError); expect((await deals.listDeals(actorA(), { query: "Beta Private", page: 1, pageSize: 25 })).total).toBe(0); });

  it("moves open Deals, closes won/lost Deals, and preserves append-only history", async () => { const open = await deals.createDeal(actorA(), { name: "Lifecycle Deal", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id }); expect((await deals.moveDeal(actorA(), open.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[1].id, reason: "Qualified" })).closedAt).toBeNull(); await expect(deals.moveDeal(actorA(), open.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[3].id })).rejects.toBeInstanceOf(ValidationError); const lost = await deals.moveDeal(actorA(), open.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[3].id, lostReason: "Timing", lostReasonNote: "Revisit later" }); expect(lost.closedAt).toBeInstanceOf(Date); expect(lost.lostReason).toBe("Timing"); await expect(deals.moveDeal(actorA(), open.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id })).rejects.toBeInstanceOf(ConflictError); expect((await deals.getDeal(actorA(), open.id)).history).toHaveLength(3); const wonCandidate = await deals.createDeal(actorA(), { name: "Won Deal", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id }); expect((await deals.moveDeal(actorA(), wonCandidate.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[2].id })).closedAt).toBeInstanceOf(Date); });

  it("rejects cross-Pipeline moves atomically", async () => { const second = (await pipelineService.listPipelines(actorA())).find((pipeline) => pipeline.id !== pipelineA.pipeline.id)!; const destination = (await pipelineService.getPipeline(actorA(), second.id)).stages[0]; const deal = await deals.createDeal(actorA(), { name: "No Cross Move", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id }); await expect(deals.moveDeal(actorA(), deal.id, { pipelineId: second.id, stageId: destination.id })).rejects.toBeInstanceOf(ConflictError); expect((await deals.getDeal(actorA(), deal.id)).history).toHaveLength(1); });

  it("serializes competing terminal transitions", async () => { const deal = await deals.createDeal(actorA(), { name: "Concurrent Close", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id }); const results = await Promise.allSettled([deals.moveDeal(actorA(), deal.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[2].id }), deals.moveDeal(actorA(), deal.id, { pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[3].id, lostReason: "Competing request" })]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(results.filter((result) => result.status === "rejected")).toHaveLength(1); expect((await deals.getDeal(actorA(), deal.id)).history).toHaveLength(2); });

  it("blocks Pipeline and Stage archive while an active Deal references them", async () => { const protectedPipeline = await pipelineService.createPipeline(actorA(), { name: "Protected Pipeline", stages: stages("Protected") }); const replacement = (await pipelineService.listPipelines(actorA())).find((pipeline) => pipeline.id !== protectedPipeline.pipeline.id)!; const deal = await deals.createDeal(actorA(), { name: "Protected Deal", pipelineId: protectedPipeline.pipeline.id, stageId: protectedPipeline.stages[0].id, customerId: customerA.id }); await expect(pipelineService.archiveStage(actorA(), protectedPipeline.pipeline.id, protectedPipeline.stages[0].id)).rejects.toBeInstanceOf(ConflictError); await expect(pipelineService.archivePipeline(actorA(), protectedPipeline.pipeline.id, { replacementPipelineId: replacement.id })).rejects.toBeInstanceOf(ConflictError); await deals.archiveDeal(actorA(), deal.id); await pipelineService.archiveStage(actorA(), protectedPipeline.pipeline.id, protectedPipeline.stages[0].id); });

  it("counts archive references within the correct tenant only", async () => { const local = await pipelineService.createPipeline(actorA(), { name: "Tenant Count Local", stages: stages("Local Count") }); await deals.createDeal(actorB(), { name: "Foreign Count Deal", pipelineId: pipelineB.pipeline.id, stageId: pipelineB.stages[0].id, customerId: customerB.id }); await pipelineService.archiveStage(actorA(), local.pipeline.id, local.stages[0].id); expect((await pipelineService.getPipeline(actorA(), local.pipeline.id)).stages).toHaveLength(3); });

  it("enforces persisted read-only RBAC", async () => { const viewerResult = await new UserService().createUserWithMembership(actorA(), { name: "Deal Viewer", email: "deal-viewer@example.test", password: "Synthetic-Viewer-123" }, "viewer"); const viewer = { userId: viewerResult.user.id, organizationId: orgA.organization.id, role: "viewer" as const }; expect((await deals.listDeals(viewer, { page: 1, pageSize: 10 })).total).toBeGreaterThan(0); await expect(deals.createDeal(viewer, { name: "Denied", pipelineId: pipelineA.pipeline.id, stageId: pipelineA.stages[0].id, customerId: customerA.id })).rejects.toBeInstanceOf(ForbiddenError); });
});
