import "server-only";
import { and, asc, count, desc, eq, gte, ilike, isNull, lte, or } from "drizzle-orm";
import { getDb, type DatabaseExecutor } from "@/db";
import { deals, dealStageHistory, pipelineStages } from "@/db/schema";
import type { Deal, DealStageHistory, NewDeal } from "./deal.types";
import type { PipelineStageKind } from "@/modules/pipelines/pipeline.types";

export interface DealListInput { query?: string; pipelineId?: string; stageId?: string; ownerUserId?: string | null; customerId?: string; kind?: PipelineStageKind; minAmountCents?: number; maxAmountCents?: number; expectedCloseFrom?: string; expectedCloseTo?: string; limit: number; offset: number }
export class DealRepository {
  constructor(private readonly executor: DatabaseExecutor = getDb()) {}
  private active(organizationId: string) { return and(eq(deals.organizationId, organizationId), isNull(deals.archivedAt)); }
  async findById(organizationId: string, id: string): Promise<Deal | null> { const [value] = await this.executor.select().from(deals).where(and(this.active(organizationId), eq(deals.id, id))).limit(1); return value ?? null; }
  async findByIdForUpdate(organizationId: string, id: string): Promise<Deal | null> { const [value] = await this.executor.select().from(deals).where(and(this.active(organizationId), eq(deals.id, id))).for("update").limit(1); return value ?? null; }
  async list(organizationId: string, input: DealListInput) { const search = input.query ? or(ilike(deals.identifier, `%${input.query}%`), ilike(deals.name, `%${input.query}%`)) : undefined; const where = and(this.active(organizationId), search, input.pipelineId ? eq(deals.pipelineId, input.pipelineId) : undefined, input.stageId ? eq(deals.stageId, input.stageId) : undefined, input.ownerUserId === null ? isNull(deals.ownerUserId) : input.ownerUserId ? eq(deals.ownerUserId, input.ownerUserId) : undefined, input.customerId ? eq(deals.customerId, input.customerId) : undefined, input.kind ? eq(pipelineStages.kind, input.kind) : undefined, input.minAmountCents === undefined ? undefined : gte(deals.amountCents, input.minAmountCents), input.maxAmountCents === undefined ? undefined : lte(deals.amountCents, input.maxAmountCents), input.expectedCloseFrom ? gte(deals.expectedCloseDate, input.expectedCloseFrom) : undefined, input.expectedCloseTo ? lte(deals.expectedCloseDate, input.expectedCloseTo) : undefined);
    const [items, [{ total }]] = await Promise.all([this.executor.select({ deal: deals }).from(deals).innerJoin(pipelineStages, and(eq(pipelineStages.organizationId, deals.organizationId), eq(pipelineStages.pipelineId, deals.pipelineId), eq(pipelineStages.id, deals.stageId))).where(where).orderBy(desc(deals.createdAt), desc(deals.id)).limit(input.limit).offset(input.offset), this.executor.select({ total: count() }).from(deals).innerJoin(pipelineStages, and(eq(pipelineStages.organizationId, deals.organizationId), eq(pipelineStages.pipelineId, deals.pipelineId), eq(pipelineStages.id, deals.stageId))).where(where)]); return { items: items.map(({ deal }) => deal), total }; }
  async create(input: NewDeal): Promise<Deal> { const [value] = await this.executor.insert(deals).values(input).returning(); return value; }
  async update(organizationId: string, id: string, input: Partial<NewDeal>): Promise<Deal | null> { const [value] = await this.executor.update(deals).set({ ...input, id: undefined, organizationId: undefined, identifier: undefined, pipelineId: undefined, stageId: undefined, createdAt: undefined, createdBy: undefined, updatedAt: new Date() }).where(and(this.active(organizationId), eq(deals.id, id))).returning(); return value ?? null; }
  async move(organizationId: string, id: string, input: { pipelineId: string; stageId: string; closedAt: Date | null; lostReason: string | null; lostReasonNote: string | null; actorUserId: string }): Promise<Deal | null> { const [value] = await this.executor.update(deals).set({ pipelineId: input.pipelineId, stageId: input.stageId, closedAt: input.closedAt, lostReason: input.lostReason, lostReasonNote: input.lostReasonNote, updatedBy: input.actorUserId, updatedAt: new Date() }).where(and(this.active(organizationId), eq(deals.id, id))).returning(); return value ?? null; }
  async archive(organizationId: string, id: string, actorUserId: string): Promise<Deal | null> { const [value] = await this.executor.update(deals).set({ archivedAt: new Date(), updatedBy: actorUserId, updatedAt: new Date() }).where(and(this.active(organizationId), eq(deals.id, id))).returning(); return value ?? null; }
  async recordHistory(input: typeof dealStageHistory.$inferInsert): Promise<DealStageHistory> { const [value] = await this.executor.insert(dealStageHistory).values(input).returning(); return value; }
  async listHistory(organizationId: string, dealId: string): Promise<DealStageHistory[]> { return this.executor.select().from(dealStageHistory).where(and(eq(dealStageHistory.organizationId, organizationId), eq(dealStageHistory.dealId, dealId))).orderBy(asc(dealStageHistory.createdAt), asc(dealStageHistory.id)); }
  async countActiveForPipeline(organizationId: string, pipelineId: string): Promise<number> { const [{ value }] = await this.executor.select({ value: count() }).from(deals).where(and(this.active(organizationId), eq(deals.pipelineId, pipelineId))); return value; }
  async countActiveForStage(organizationId: string, pipelineId: string, stageId: string): Promise<number> { const [{ value }] = await this.executor.select({ value: count() }).from(deals).where(and(this.active(organizationId), eq(deals.pipelineId, pipelineId), eq(deals.stageId, stageId))); return value; }
}
