import { randomUUID } from "node:crypto";
import { authorize } from "@/auth/authorization";
import { ConflictError, NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { changedFields, nullable, parseEntityId } from "@/modules/crm/crm.helpers";
import type { Authorizer, RequestActor } from "@/modules/customers/customer.service";
import { archiveDealSchema, assignDealSchema, createDealSchema, dealFilterSchema, moveDealSchema, updateDealSchema, type AssignDealInput, type CreateDealInput, type DealFilter, type MoveDealInput, type UpdateDealInput } from "./deal.schema";
import { DealRepository } from "./deal.repository";
import { assertMove, assertOpenForMutation, isDatabaseConstraintError } from "./deal.rules";
import { DrizzleDealUnitOfWork, type DealRepositories, type DealUnitOfWork } from "./deal.unit-of-work";
import type { Deal } from "./deal.types";
import { MembershipRepository } from "@/modules/identity/membership.repository";

export class DealService {
  constructor(private readonly repository = new DealRepository(), private readonly authorizer: Authorizer = authorize, private readonly unitOfWork: DealUnitOfWork = new DrizzleDealUnitOfWork(), private readonly memberships = new MembershipRepository()) {}
  async getDeal(actor: RequestActor, id: string) { await this.authorizer(actor, "deal.read"); id = parseEntityId(id); const deal = await this.repository.findById(actor.organizationId, id); if (!deal) throw new NotFoundError("Deal not found"); return { deal, history: await this.repository.listHistory(actor.organizationId, id) }; }
  async listDeals(actor: RequestActor, raw: DealFilter) { await this.authorizer(actor, "deal.read"); const input = parseInput(dealFilterSchema, raw); const result = await this.repository.list(actor.organizationId, { ...input, limit: input.pageSize, offset: (input.page - 1) * input.pageSize }); return { ...result, page: input.page, pageSize: input.pageSize }; }
  async listAssignableOwners(actor: RequestActor) { await this.authorizer(actor, "deal.read"); return (await this.memberships.list(actor.organizationId)).filter((membership) => ["owner", "admin", "manager"].includes(membership.role)); }

  async createDeal(actor: RequestActor, raw: CreateDealInput): Promise<Deal> {
    await this.authorizer(actor, "deal.create"); const input = parseInput(createDealSchema, raw); if (input.ownerUserId) await this.authorizer(actor, "deal.assign");
    try { return await this.unitOfWork.transaction(async (repositories) => { const { pipeline, stage } = await this.requireDestination(repositories, actor.organizationId, input.pipelineId, input.stageId); if (stage.kind !== "open") throw new ConflictError("A new deal must start in an open stage"); await this.requireCustomerContact(repositories, actor.organizationId, input.customerId, input.contactId); if (input.ownerUserId) await this.requireDealOwner(repositories, actor.organizationId, input.ownerUserId); const deal = await repositories.deals.create({ organizationId: actor.organizationId, identifier: `DEAL-${randomUUID().slice(0, 8).toUpperCase()}`, name: input.name, pipelineId: pipeline.id, stageId: stage.id, customerId: input.customerId, contactId: input.contactId, ownerUserId: input.ownerUserId, amountCents: input.amountCents, currency: input.currency, expectedCloseDate: input.expectedCloseDate, source: nullable(input.source), createdBy: actor.userId, updatedBy: actor.userId }); await repositories.deals.recordHistory({ organizationId: actor.organizationId, dealId: deal.id, previousPipelineId: null, previousStageId: null, newPipelineId: pipeline.id, newStageId: stage.id, actorUserId: actor.userId, reason: "Deal created" }); await repositories.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "deal.created", entityType: "deal", entityId: deal.id, metadata: { pipelineId: pipeline.id, stageId: stage.id, customerId: deal.customerId, currency: deal.currency } }); return deal; }); } catch (error) { if (isDatabaseConstraintError(error)) throw new ConflictError("Deal relationships or identifier conflict with current data"); throw error; }
  }

  async updateDeal(actor: RequestActor, id: string, raw: UpdateDealInput): Promise<Deal> {
    await this.authorizer(actor, "deal.update"); id = parseEntityId(id); const input = parseInput(updateDealSchema, raw);
    try { return await this.unitOfWork.transaction(async (repositories) => { const current = await repositories.deals.findByIdForUpdate(actor.organizationId, id); if (!current) throw new NotFoundError("Deal not found"); const stage = await repositories.stages.findById(actor.organizationId, current.stageId); if (!stage) throw new ConflictError("Deal stage is unavailable"); assertOpenForMutation(stage.kind); await this.requireCustomerContact(repositories, actor.organizationId, current.customerId, input.contactId); const deal = await repositories.deals.update(actor.organizationId, id, { ...input, source: nullable(input.source), updatedBy: actor.userId }); if (!deal) throw new NotFoundError("Deal not found"); await repositories.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "deal.updated", entityType: "deal", entityId: id, metadata: { fields: changedFields(input) } }); return deal; }); } catch (error) { if (isDatabaseConstraintError(error)) throw new ConflictError("Deal relationship conflicts with current data"); throw error; }
  }

  async assignDeal(actor: RequestActor, id: string, raw: AssignDealInput): Promise<Deal> {
    await this.authorizer(actor, "deal.assign"); id = parseEntityId(id); const input = parseInput(assignDealSchema, raw);
    return this.unitOfWork.transaction(async (repositories) => { const current = await repositories.deals.findByIdForUpdate(actor.organizationId, id); if (!current) throw new NotFoundError("Deal not found"); const stage = await repositories.stages.findById(actor.organizationId, current.stageId); if (!stage) throw new ConflictError("Deal stage is unavailable"); assertOpenForMutation(stage.kind); if (input.ownerUserId) await this.requireDealOwner(repositories, actor.organizationId, input.ownerUserId); const deal = await repositories.deals.update(actor.organizationId, id, { ownerUserId: input.ownerUserId, updatedBy: actor.userId }); if (!deal) throw new NotFoundError("Deal not found"); await repositories.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: input.ownerUserId ? "deal.assigned" : "deal.unassigned", entityType: "deal", entityId: id, metadata: { ownerUserId: input.ownerUserId } }); return deal; });
  }

  async moveDeal(actor: RequestActor, id: string, raw: MoveDealInput): Promise<Deal> {
    await this.authorizer(actor, "deal.move"); id = parseEntityId(id); const input = parseInput(moveDealSchema, raw);
    return this.unitOfWork.transaction(async (repositories) => { const current = await repositories.deals.findByIdForUpdate(actor.organizationId, id); if (!current) throw new NotFoundError("Deal not found"); const currentStage = await repositories.stages.findById(actor.organizationId, current.stageId); if (!currentStage) throw new ConflictError("Current Deal stage is unavailable"); const { stage: destination } = await this.requireDestination(repositories, actor.organizationId, input.pipelineId, input.stageId); if (destination.kind !== "open") await this.authorizer(actor, "deal.close"); if (destination.id === current.stageId) throw new ConflictError("Deal is already in this stage"); assertMove(current.pipelineId, input.pipelineId, currentStage.kind, destination.kind, input.lostReason); const closedAt = destination.kind === "open" ? null : new Date(); const deal = await repositories.deals.move(actor.organizationId, id, { pipelineId: input.pipelineId, stageId: input.stageId, closedAt, lostReason: destination.kind === "lost" ? input.lostReason! : null, lostReasonNote: destination.kind === "lost" ? nullable(input.lostReasonNote) ?? null : null, actorUserId: actor.userId }); if (!deal) throw new ConflictError("Deal changed during stage movement"); const reason = destination.kind === "lost" ? input.lostReason : nullable(input.reason); await repositories.deals.recordHistory({ organizationId: actor.organizationId, dealId: id, previousPipelineId: current.pipelineId, previousStageId: current.stageId, newPipelineId: input.pipelineId, newStageId: input.stageId, actorUserId: actor.userId, reason }); const action = destination.kind === "won" ? "deal.won" : destination.kind === "lost" ? "deal.lost" : "deal.stage_changed"; await repositories.audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action, entityType: "deal", entityId: id, metadata: { previousStageId: current.stageId, stageId: destination.id, pipelineId: input.pipelineId } }); return deal; });
  }

  async archiveDeal(actor: RequestActor, id: string, raw: unknown = {}): Promise<void> { await this.authorizer(actor, "deal.delete"); id = parseEntityId(id); parseInput(archiveDealSchema, raw); await this.unitOfWork.transaction(async ({ deals, audit }) => { const current = await deals.findByIdForUpdate(actor.organizationId, id); if (!current) throw new NotFoundError("Deal not found"); const archived = await deals.archive(actor.organizationId, id, actor.userId); if (!archived) throw new NotFoundError("Deal not found"); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "deal.archived", entityType: "deal", entityId: id, metadata: { pipelineId: current.pipelineId, stageId: current.stageId } }); }); }

  private async requireDestination(repositories: DealRepositories, organizationId: string, pipelineId: string, stageId: string) { const pipeline = await repositories.pipelines.findByIdForUpdate(organizationId, pipelineId); if (!pipeline) throw new NotFoundError("Pipeline not found"); const stage = await repositories.stages.findById(organizationId, stageId); if (!stage || stage.pipelineId !== pipelineId) throw new NotFoundError("Pipeline stage not found"); return { pipeline, stage }; }
  private async requireCustomerContact(repositories: DealRepositories, organizationId: string, customerId: string, contactId?: string | null) { if (!await repositories.customers.findById(organizationId, customerId)) throw new NotFoundError("Customer not found"); if (contactId) { const contact = await repositories.contacts.findById(organizationId, contactId); if (!contact || contact.customerId !== customerId) throw new NotFoundError("Customer contact not found"); } }
  private async requireDealOwner(repositories: DealRepositories, organizationId: string, userId: string) { const membership = await repositories.memberships.find(organizationId, userId); if (!membership || !["owner", "admin", "manager"].includes(membership.role)) throw new NotFoundError("Assignable Deal owner not found"); }
}
