import { z } from "zod";
const date=z.iso.date();const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);const optionalText=(max:number)=>z.string().trim().max(max).optional().or(z.literal(""));
export const createJobSchema=z.strictObject({customerId:z.uuid(),contactId:z.uuid().nullable().optional(),title:z.string().trim().min(1).max(200),description:optionalText(5000),serviceAddress:z.string().trim().min(1).max(500),priority:z.enum(["low","normal","high","urgent"]).default("normal"),technicianUserId:z.uuid().nullable().optional(),scheduledDate:date.nullable().optional(),scheduledTime:time.nullable().optional(),durationMinutes:z.number().int().min(1).max(1440).default(60),timezone:z.string().default("America/Vancouver")}).refine(v=>(v.scheduledDate===null||v.scheduledDate===undefined)===(v.scheduledTime===null||v.scheduledTime===undefined),{message:"Scheduled date and time must be provided together",path:["scheduledTime"]});
export const updateJobSchema=z.strictObject({title:z.string().trim().min(1).max(200).optional(),description:optionalText(5000),serviceAddress:z.string().trim().min(1).max(500).optional(),priority:z.enum(["low","normal","high","urgent"]).optional(),contactId:z.uuid().nullable().optional()});
export const scheduleJobSchema=z.strictObject({technicianUserId:z.uuid().nullable(),scheduledDate:date.nullable(),scheduledTime:time.nullable(),durationMinutes:z.number().int().min(1).max(1440),timezone:z.string().default("America/Vancouver"),reason:optionalText(500)}).refine(v=>(v.scheduledDate===null)===(v.scheduledTime===null),{message:"Scheduled date and time must be provided together",path:["scheduledTime"]});
export const transitionJobSchema=z.strictObject({toStatus:z.enum(["scheduled","in_progress","completed","invoiced","cancelled"]),reason:optionalText(500)});
export const jobFilterSchema=z.strictObject({query:z.string().trim().max(200).optional(),status:z.enum(["scheduled","in_progress","completed","invoiced","cancelled"]).optional(),priority:z.enum(["low","normal","high","urgent"]).optional(),technicianUserId:z.uuid().nullable().optional(),customerId:z.uuid().optional(),dateFrom:date.optional(),dateTo:date.optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)});
export const createChecklistItemSchema=z.strictObject({label:z.string().trim().min(1).max(500)});export const setChecklistItemSchema=z.strictObject({completed:z.boolean()});export const createJobNoteSchema=z.strictObject({body:z.string().trim().min(1).max(10000)});
export type CreateJobInput=z.input<typeof createJobSchema>;export type UpdateJobInput=z.input<typeof updateJobSchema>;export type ScheduleJobInput=z.input<typeof scheduleJobSchema>;export type JobFilter=z.input<typeof jobFilterSchema>;
