"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { currentActor } from "@/auth/current-actor";
import { PhoneOperationsService } from "@/modules/phone-operations/phone.service";
export async function savePhoneSettingsAction(data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new PhoneOperationsService().saveSettings(actor, { operatingMode: String(data.get("operatingMode") ?? "disabled"), inboundEnabled: data.get("inboundEnabled") === "on", outboundEnabled: data.get("outboundEnabled") === "on", maxConcurrentCalls: Number(data.get("maxConcurrentCalls")), dailyCallCap: Number(data.get("dailyCallCap")), voiceRuntimeUrl: String(data.get("voiceRuntimeUrl") ?? "") }); revalidatePath("/settings/phone"); }
export async function saveProviderAction(data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new PhoneOperationsService().saveProviderCredential(actor, { accountSid: String(data.get("accountSid") ?? ""), authToken: String(data.get("authToken") ?? "") }); revalidatePath("/settings/phone"); }
export async function publishAgentAction(data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new PhoneOperationsService().publishVoiceAgent(actor, { logicalName: String(data.get("logicalName") ?? ""), prompt: String(data.get("prompt") ?? ""), voice: String(data.get("voice") ?? ""), isDefault: data.get("isDefault") === "on", toolPolicy: data.getAll("toolPolicy").map(String) }); revalidatePath("/settings/phone"); }
export async function saveNumberAction(data: FormData) { const actor = await currentActor(); if (!actor) redirect("/login"); await new PhoneOperationsService().savePhoneNumber(actor, { providerNumberId: String(data.get("providerNumberId") ?? ""), e164: String(data.get("e164") ?? ""), label: String(data.get("label") ?? ""), inboundEnabled: data.get("inboundEnabled") === "on", outboundEnabled: data.get("outboundEnabled") === "on", voiceAgentId: String(data.get("voiceAgentId") ?? "") || null }); revalidatePath("/settings/phone"); }
