import { renderToBuffer } from "@react-pdf/renderer";
import { describe, expect, it } from "vitest";
import { ConflictError, ValidationError } from "@/lib/errors";
import { InvoiceReport } from "@/reports/invoice-report";
import { createInvoiceSchema, reorderInvoiceLinesSchema } from "./invoice.schema";
import { calculateInvoice, dueDateFor, invoiceBalance, isInvoiceOverdue, lineTotalCents } from "./invoice.rules";

describe("Invoice domain rules",()=>{
  it("uses integer thousandths and exact inclusive/exclusive tax",()=>{expect(lineTotalCents(1500,999)).toBe(1499);const exclusive=calculateInvoice([{quantityMilli:1000,unitPriceCents:10000,taxable:true}],{enabled:true,pricesIncludeTax:false,components:[{code:"GST",name:"GST",rateBasisPoints:500},{code:"PST",name:"PST",rateBasisPoints:700}]});expect(exclusive).toMatchObject({subtotalCents:10000,taxCents:1200,totalCents:11200});const inclusive=calculateInvoice([{quantityMilli:1000,unitPriceCents:11200,taxable:true}],{enabled:true,pricesIncludeTax:true,components:[{code:"GST",name:"GST",rateBasisPoints:500},{code:"PST",name:"PST",rateBasisPoints:700}]});expect(inclusive).toMatchObject({subtotalCents:10000,taxCents:1200,totalCents:11200});expect(inclusive.tax.components.reduce((sum,x)=>sum+x.amountCents,0)).toBe(1200)});
  it("derives payment terms and overdue state without a stored overdue status",()=>{expect(dueDateFor("2026-09-08","net_30")).toBe("2026-10-08");expect(()=>dueDateFor("2026-09-08","custom")).toThrow(ValidationError);expect(isInvoiceOverdue("issued","2026-09-01",1,"2026-09-08")).toBe(true);expect(isInvoiceOverdue("paid","2026-09-01",0,"2026-09-08")).toBe(false)});
  it("keeps balance server-derived and rejects corrupt postings",()=>{expect(invoiceBalance(5000,1250)).toBe(3750);expect(()=>invoiceBalance(5000,5001)).toThrow(ConflictError)});
  it("rejects mass assignment and malformed complete ordering",()=>{expect(createInvoiceSchema.safeParse({source:"manual",organizationId:crypto.randomUUID(),customerId:crypto.randomUUID(),lines:[{description:"x",quantityMilli:1000,unitPriceCents:100}]}).success).toBe(false);expect(reorderInvoiceLinesSchema.safeParse({expectedRowVersion:0,lineIds:[crypto.randomUUID(),crypto.randomUUID()]}).success).toBe(true);const id=crypto.randomUUID();expect(reorderInvoiceLinesSchema.safeParse({expectedRowVersion:0,lineIds:[id,id]}).success).toBe(false)});
  it("renders a PDF from persisted invoice snapshots",async()=>{const bytes=await renderToBuffer(InvoiceReport({model:{identifier:"INV-1",status:"issued",issueDate:"2026-09-08",dueDate:"2026-10-08",currency:"CAD",customer:{name:"Synthetic Customer"},lines:[{id:crypto.randomUUID(),description:"Service",quantityMilli:1000,unit:"each",unitPriceCents:10000,totalCents:10000}],subtotalCents:10000,discountCents:0,taxCents:500,totalCents:10500,amountPaidCents:0,balanceCents:10500,notes:"",terms:"Net 30",tax:{components:[{name:"GST",rateBasisPoints:500,amountCents:500}]}}}));expect(new Uint8Array(bytes).slice(0,4).toString()).toBe("37,80,68,70")});
});
