import "server-only";
import { and, asc, desc, eq, ilike, inArray, lte, or, sql } from "drizzle-orm";
import { getDb, type DatabaseExecutor } from "@/db";
import { contracts, contractVersions, customers, invoiceLines, invoices, invoiceStatusHistory, jobs, organizations, pricebookItems } from "@/db/schema";

export class InvoiceRepository {
  constructor(readonly db: DatabaseExecutor = getDb()) {}
  async lockOrganization(id: string) { return (await this.db.select().from(organizations).where(eq(organizations.id, id)).for("update"))[0]; }
  async nextSequence(organizationId: string) { const [row] = await this.db.select({ value: sql<number>`coalesce(max(${invoices.sequenceNumber}),0)+1` }).from(invoices).where(eq(invoices.organizationId, organizationId)); return Number(row?.value ?? 1); }
  async find(organizationId: string, id: string, lock = false) { const query = this.db.select().from(invoices).where(and(eq(invoices.organizationId, organizationId), eq(invoices.id, id), sql`${invoices.archivedAt} is null`)); return lock ? (await query.for("update"))[0] : (await query)[0]; }
  async list(organizationId: string, input: { search?: string; status?: typeof invoices.$inferSelect.status; customerId?: string; contractId?: string; jobId?: string; dueBefore?: string; limit: number }) { const filters = [eq(invoices.organizationId, organizationId), sql`${invoices.archivedAt} is null`]; if(input.status)filters.push(eq(invoices.status,input.status)); if(input.customerId)filters.push(eq(invoices.customerId,input.customerId)); if(input.contractId)filters.push(eq(invoices.contractId,input.contractId)); if(input.jobId)filters.push(eq(invoices.jobId,input.jobId)); if(input.dueBefore)filters.push(lte(invoices.dueDate,input.dueBefore)); if(input.search)filters.push(or(ilike(invoices.identifier,`%${input.search}%`),ilike(customers.name,`%${input.search}%`))!); return this.db.select({invoice:invoices,customerName:customers.name}).from(invoices).innerJoin(customers,and(eq(customers.organizationId,invoices.organizationId),eq(customers.id,invoices.customerId))).where(and(...filters)).orderBy(desc(invoices.createdAt),desc(invoices.id)).limit(input.limit); }
  async customer(organizationId: string, id: string) { return this.db.query.customers.findFirst({ where: and(eq(customers.organizationId, organizationId), eq(customers.id, id), eq(customers.status, "active")) }); }
  async job(organizationId: string, id: string) { return this.db.query.jobs.findFirst({ where: and(eq(jobs.organizationId, organizationId), eq(jobs.id, id), sql`${jobs.archivedAt} is null`) }); }
  async contract(organizationId: string, id: string) { return this.db.query.contracts.findFirst({ where: and(eq(contracts.organizationId, organizationId), eq(contracts.id, id), sql`${contracts.archivedAt} is null`) }); }
  async contractVersion(organizationId: string, contractId: string, id: string) { return this.db.query.contractVersions.findFirst({ where: and(eq(contractVersions.organizationId, organizationId), eq(contractVersions.contractId, contractId), eq(contractVersions.id, id)) }); }
  async activeForContract(organizationId:string,contractId:string){return this.db.query.invoices.findFirst({where:and(eq(invoices.organizationId,organizationId),eq(invoices.contractId,contractId),sql`${invoices.status}<>'void'`,sql`${invoices.archivedAt} is null`)});}
  async activeForJob(organizationId:string,jobId:string){return this.db.query.invoices.findFirst({where:and(eq(invoices.organizationId,organizationId),eq(invoices.jobId,jobId),sql`${invoices.status}<>'void'`,sql`${invoices.archivedAt} is null`)});}
  async pricebookItem(organizationId:string,id:string){return this.db.query.pricebookItems.findFirst({where:and(eq(pricebookItems.organizationId,organizationId),eq(pricebookItems.id,id),eq(pricebookItems.status,"active"))});}
  async create(value: typeof invoices.$inferInsert) { return (await this.db.insert(invoices).values(value).returning())[0]!; }
  async insertLines(values: Array<typeof invoiceLines.$inferInsert>) { return values.length ? this.db.insert(invoiceLines).values(values).returning() : []; }
  async lines(organizationId: string, invoiceId: string) { return this.db.select().from(invoiceLines).where(and(eq(invoiceLines.organizationId, organizationId),eq(invoiceLines.invoiceId,invoiceId))).orderBy(asc(invoiceLines.sortOrder)); }
  async line(organizationId:string,invoiceId:string,id:string){return this.db.query.invoiceLines.findFirst({where:and(eq(invoiceLines.organizationId,organizationId),eq(invoiceLines.invoiceId,invoiceId),eq(invoiceLines.id,id))});}
  async claimVersion(organizationId:string,id:string,expected:number){return(await this.db.update(invoices).set({rowVersion:sql`${invoices.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(invoices.organizationId,organizationId),eq(invoices.id,id),eq(invoices.rowVersion,expected))).returning())[0];}
  async update(organizationId:string,id:string,value:Partial<typeof invoices.$inferInsert>){return(await this.db.update(invoices).set({...value,id:undefined,organizationId:undefined,sequenceNumber:undefined,identifier:undefined,source:undefined,customerId:undefined,jobId:undefined,contractId:undefined,contractVersionId:undefined,quoteId:undefined,quoteVersionId:undefined,quoteOptionId:undefined,billingSnapshot:undefined,taxSnapshot:undefined,subtotalCents:undefined,discountCents:undefined,taxCents:undefined,rebateCents:undefined,totalCents:undefined,createdBy:undefined,createdAt:undefined,updatedAt:new Date()}).where(and(eq(invoices.organizationId,organizationId),eq(invoices.id,id))).returning())[0];}
  async updateLine(organizationId:string,invoiceId:string,id:string,value:Partial<typeof invoiceLines.$inferInsert>){return(await this.db.update(invoiceLines).set({...value,id:undefined,organizationId:undefined,invoiceId:undefined}).where(and(eq(invoiceLines.organizationId,organizationId),eq(invoiceLines.invoiceId,invoiceId),eq(invoiceLines.id,id))).returning())[0];}
  async removeLine(organizationId:string,invoiceId:string,id:string){return(await this.db.delete(invoiceLines).where(and(eq(invoiceLines.organizationId,organizationId),eq(invoiceLines.invoiceId,invoiceId),eq(invoiceLines.id,id))).returning())[0];}
  async reorder(organizationId:string,invoiceId:string,ids:string[]){await this.db.update(invoiceLines).set({sortOrder:sql`${invoiceLines.sortOrder}+1000000`}).where(and(eq(invoiceLines.organizationId,organizationId),eq(invoiceLines.invoiceId,invoiceId),inArray(invoiceLines.id,ids)));for(let i=0;i<ids.length;i++)await this.db.update(invoiceLines).set({sortOrder:i}).where(and(eq(invoiceLines.organizationId,organizationId),eq(invoiceLines.invoiceId,invoiceId),eq(invoiceLines.id,ids[i]!)));}
  async replaceTotals(organizationId:string,id:string,value:Pick<typeof invoices.$inferInsert,"subtotalCents"|"discountCents"|"taxCents"|"totalCents"|"taxSnapshot"|"currency">){await this.db.update(invoices).set({...value,updatedAt:new Date()}).where(and(eq(invoices.organizationId,organizationId),eq(invoices.id,id)));}
  async transition(organizationId:string,id:string,from:typeof invoices.$inferSelect.status,value:Partial<typeof invoices.$inferInsert>){return(await this.db.update(invoices).set({...value,rowVersion:sql`${invoices.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(invoices.organizationId,organizationId),eq(invoices.id,id),eq(invoices.status,from))).returning())[0];}
  async history(value:typeof invoiceStatusHistory.$inferInsert){return(await this.db.insert(invoiceStatusHistory).values(value).returning())[0]!;}
  async hardDeleteDraft(organizationId:string,id:string){return(await this.db.delete(invoices).where(and(eq(invoices.organizationId,organizationId),eq(invoices.id,id),eq(invoices.status,"draft"))).returning())[0];}
}
