import { describe, expect, it } from "vitest";
import { getDb } from "@/db";
import { invoiceStatusHistory } from "@/db/schema";
import type { ObjectStorage } from "@/lib/r2";
import { ConflictError, ForbiddenError, NotFoundError } from "@/lib/errors";
import { AuditRepository } from "@/modules/audit/audit.repository";
import { ContractService } from "@/modules/contracts";
import { CustomerService } from "@/modules/customers/customer.service";
import { EstimateService } from "@/modules/estimates/estimate.service";
import { EstimateParityService } from "@/modules/estimates/parity.service";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { TaxService } from "@/modules/estimates/tax.service";
import { InvoiceService } from "./invoice.service";

class MemoryStorage implements ObjectStorage { objects=new Map<string,Uint8Array>();async put(key:string,body:Uint8Array){this.objects.set(key,body)}async get(key:string){const value=this.objects.get(key);if(!value)throw new Error("missing");return value}async delete(key:string){this.objects.delete(key)}async signedDownloadUrl(key:string){return `https://storage.example.test/${encodeURIComponent(key)}`}}

describe.sequential("PostgreSQL Invoices",()=>{let a:Awaited<ReturnType<OrganizationService["createOrganizationWithOwner"]>>,b:typeof a,customer:Awaited<ReturnType<CustomerService["createCustomer"]>>;const service=new InvoiceService(),actor=()=>({userId:a.user.id,organizationId:a.organization.id,role:"owner" as const}),foreign=()=>({userId:b.user.id,organizationId:b.organization.id,role:"owner" as const});const create=(overrides:Record<string,unknown>={})=>service.create(actor(),{source:"manual",customerId:customer.id,paymentTerms:"net_30",notes:"Synthetic",terms:"Test only",lines:[{description:"Diagnostic service",category:"service",unit:"each",quantityMilli:1500,unitPriceCents:10000,taxable:true}],...overrides});
  it("creates isolated fixtures",async()=>{const organizations=new OrganizationService();a=await organizations.createOrganizationWithOwner({name:"Invoice Tenant A",slug:`invoice-a-${crypto.randomUUID()}`},{name:"Owner A",email:`invoice-a-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-123"});b=await organizations.createOrganizationWithOwner({name:"Invoice Tenant B",slug:`invoice-b-${crypto.randomUUID()}`},{name:"Owner B",email:`invoice-b-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-456"});customer=await new CustomerService().createCustomer(actor(),{name:"Synthetic Invoice Customer",email:"billing@example.test",addressLine1:"100 Test Street"})});
  it("creates exact priced drafts with tenant numbering, snapshots and audit",async()=>{await new TaxService().publish(actor(),{enabled:true,countryCode:"CA",regionCode:"BC",currency:"CAD",pricesIncludeTax:false,defaultTaxable:true,components:[{code:"GST",name:"GST",rateBasisPoints:500},{code:"PST",name:"PST",rateBasisPoints:700}]});const invoice=await create(),detail=await service.get(actor(),invoice.id);expect(invoice.identifier).toMatch(/^INV-\d+$/);expect(detail.invoice).toMatchObject({subtotalCents:15000,taxCents:1800,totalCents:16800,amountPaidCents:0,balanceCents:16800});expect(detail.lines[0]).toMatchObject({description:"Diagnostic service",totalCents:15000});expect(detail.invoice.billingSnapshot).toContain("100 Test Street");expect(detail.invoice.taxSnapshot).toContain("GST");expect((await new AuditRepository().listForEntity(actor().organizationId,"invoice",invoice.id)).map(x=>x.action)).toContain("invoice.created")});
  it("freezes billing and tax snapshots from later source changes",async()=>{const invoice=await create(),before=await service.get(actor(),invoice.id);await new CustomerService().updateCustomer(actor(),customer.id,{name:"Changed Customer"});await new TaxService().publish(actor(),{enabled:false,countryCode:"CA",regionCode:"BC",currency:"CAD",pricesIncludeTax:false,defaultTaxable:true,components:[]});const after=await service.get(actor(),invoice.id);expect(after.invoice.billingSnapshot).toBe(before.invoice.billingSnapshot);expect(after.invoice.taxSnapshot).toBe(before.invoice.taxSnapshot);expect(after.invoice.totalCents).toBe(before.invoice.totalCents)});
  it("uses row versions for draft edits and freezes issued content",async()=>{const invoice=await create(),detail=await service.get(actor(),invoice.id),line=detail.lines[0]!;await service.updateLine(actor(),invoice.id,line.id,{expectedRowVersion:0,description:"Updated line",category:"service",unit:"hour",quantityMilli:2000,unitPriceCents:7000,taxable:false});await expect(service.updateLine(actor(),invoice.id,line.id,{expectedRowVersion:0,description:"Stale",category:"service",unit:"each",quantityMilli:1000,unitPriceCents:1,taxable:false})).rejects.toBeInstanceOf(ConflictError);const updated=await service.get(actor(),invoice.id);expect(updated.invoice.totalCents).toBe(14000);const issued=await service.issue(actor(),invoice.id);expect(issued).toMatchObject({status:"issued",issueDate:expect.any(String),dueDate:expect.any(String)});await expect(service.updateDraft(actor(),invoice.id,{expectedRowVersion:issued.rowVersion,notes:"mutate"})).rejects.toBeInstanceOf(ConflictError);await expect(service.removeLine(actor(),invoice.id,line.id,issued.rowVersion)).rejects.toBeInstanceOf(ConflictError)});
  it("voids but never hard-deletes issued records",async()=>{const draft=await create();await service.issue(actor(),draft.id);const voided=await service.void(actor(),draft.id,{reason:"Synthetic correction"});expect(voided.status).toBe("void");const history=await getDb().select().from(invoiceStatusHistory);expect(history.some(x=>x.invoiceId===draft.id&&x.toStatus==="void")).toBe(true);await expect(service.deleteDraft(actor(),draft.id)).rejects.toBeInstanceOf(ConflictError)});
  it("enforces tenant isolation for reads, mutations, sources, lists and PDF models",async()=>{const invoice=await create();await expect(service.get(foreign(),invoice.id)).rejects.toBeInstanceOf(NotFoundError);await expect(service.updateDraft(foreign(),invoice.id,{expectedRowVersion:0,notes:"foreign"})).rejects.toBeInstanceOf(NotFoundError);await expect(service.issue(foreign(),invoice.id)).rejects.toBeInstanceOf(NotFoundError);await expect(service.void(foreign(),invoice.id,{reason:"foreign"})).rejects.toBeInstanceOf(NotFoundError);await expect(service.pdfModel(foreign(),invoice.id)).rejects.toBeInstanceOf(NotFoundError);await expect(service.create(foreign(),{source:"manual",customerId:customer.id,lines:[{description:"foreign",quantityMilli:1000,unitPriceCents:1}]})).rejects.toBeInstanceOf(ConflictError);expect((await service.list(foreign(),{search:invoice.identifier,limit:20}))).toHaveLength(0)});
  it("denies technician/member financial access and permits viewer reads only",async()=>{const users=new UserService(),memberResult=await users.createUserWithMembership(actor(),{name:"Member",email:`invoice-member-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-789"},"member"),viewerResult=await users.createUserWithMembership(actor(),{name:"Viewer",email:`invoice-viewer-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-012"},"viewer"),invoice=await create(),member={userId:memberResult.user.id,organizationId:a.organization.id,role:"member" as const},viewer={userId:viewerResult.user.id,organizationId:a.organization.id,role:"viewer" as const};await expect(service.get(member,invoice.id)).rejects.toBeInstanceOf(ForbiddenError);await service.get(viewer,invoice.id);await expect(service.issue(viewer,invoice.id)).rejects.toBeInstanceOf(ForbiddenError)});
  it("serializes tenant numbering under concurrent creation",async()=>{const [one,two]=await Promise.all([create({notes:"one"}),create({notes:"two"})]);expect(one.sequenceNumber).not.toBe(two.sequenceNumber)});
  it("serializes simultaneous issuance so only one transition wins",async()=>{const invoice=await create(),results=await Promise.allSettled([service.issue(actor(),invoice.id),service.issue(actor(),invoice.id)]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(results.filter(result=>result.status==="rejected")).toHaveLength(1);expect((await service.get(actor(),invoice.id)).invoice.status).toBe("issued")});
  it("orders issue-versus-edit without partially mutating issued content",async()=>{const invoice=await create(),results=await Promise.allSettled([service.updateDraft(actor(),invoice.id,{expectedRowVersion:0,notes:"Concurrent edit"}),service.issue(actor(),invoice.id)]),detail=await service.get(actor(),invoice.id);expect(detail.invoice.status).toBe("issued");expect(["Synthetic","Concurrent edit"]).toContain(detail.invoice.notes);expect(results.some(result=>result.status==="fulfilled")).toBe(true);expect(detail.invoice.totalCents).toBeGreaterThan(0)});
  it("rejects incomplete Job and foreign Contract provenance without weakening compliance",async()=>{await expect(service.create(actor(),{source:"job",jobId:crypto.randomUUID(),lines:[{description:"x",quantityMilli:1000,unitPriceCents:1}]})).rejects.toBeInstanceOf(ConflictError);await expect(service.create(actor(),{source:"contract",contractId:crypto.randomUUID()})).rejects.toBeInstanceOf(ConflictError)});
  it("copies exact executed Contract provenance and prevents duplicate or cross-tenant invoicing",async()=>{const estimates=new EstimateService(),parity=new EstimateParityService(),quote=await estimates.create(actor(),{customerId:customer.id,tiers:["good"]});await estimates.addLine(actor(),quote.id,{optionId:quote.options[0]!.id,description:"Accepted snapshot line",unitPriceCents:23456});const proposal=await parity.issuePublicLink(actor(),quote.id);await parity.selectPublic(proposal.token,{optionId:quote.options[0]!.id,selectorName:"Synthetic Customer"},{ip:null,userAgent:null});const contracts=new ContractService(new MemoryStorage()),contract=await contracts.create(actor(),{quoteId:quote.id,title:"Invoice source",body:"Terms"});await contracts.addSigner(actor(),contract.id,{name:"Synthetic Signer",email:"signer@example.test"});const sent=await contracts.send(actor(),contract.id,{}),token=sent.links[0]!.token;await contracts.consent(token,{consentTextVersion:"v1"},{ip:null,userAgent:null});await contracts.sign(token,{signerName:"Synthetic Signer",method:"typed"},{ip:null,userAgent:null});const invoice=await service.create(actor(),{source:"contract",contractId:contract.id,paymentTerms:"due_on_receipt"}),detail=await service.get(actor(),invoice.id);expect(detail.invoice).toMatchObject({contractId:contract.id,quoteId:quote.id,quoteVersionId:quote.currentVersionId,quoteOptionId:quote.options[0]!.id,totalCents:23456});expect(detail.lines[0]?.description).toBe("Accepted snapshot line");await expect(service.create(actor(),{source:"contract",contractId:contract.id})).rejects.toBeInstanceOf(ConflictError);await expect(service.create(foreign(),{source:"contract",contractId:contract.id})).rejects.toBeInstanceOf(ConflictError)});
});
