import "server-only";
import { authorize } from "@/auth/authorization";
import { getDb, type DatabaseExecutor } from "@/db";
import { ConflictError, NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { AuditRepository } from "@/modules/audit/audit.repository";
import type { RequestActor } from "@/modules/customers/customer.service";
import { TaxRepository } from "@/modules/estimates/tax.repository";
import { PostgresInvoicePaymentLedger } from "@/modules/payments/payment-ledger";
import { InvoiceRepository } from "./invoice.repository";
import { createInvoiceSchema, invoiceFilterSchema, invoiceLineSchema, reorderInvoiceLinesSchema, updateInvoiceSchema, voidInvoiceSchema } from "./invoice.schema";
import { assertDraft, calculateInvoice, dueDateFor, invoiceBalance, isInvoiceOverdue, lineTotalCents } from "./invoice.rules";

export interface InvoicePaymentLedger { amountPaidCents(organizationId: string, invoiceId: string, executor?: DatabaseExecutor): Promise<number>; }
type InputLine = { pricebookItemId?: string; description:string;category:string;unit:string;quantityMilli:number;unitPriceCents:number;taxable:boolean };
type CommercialSnapshot = { quoteId:string;quoteVersionId:string;optionId:string;lines:Array<{description:string;category:string;quantityMilli:number;unit:string;unitPriceCents:number;taxable:boolean;totalCents:number}>;subtotalCents:number;discountCents:number;taxCents:number;totalCents:number;taxSnapshot:null|{currency:string;enabled:boolean;pricesIncludeTax:boolean;countryCode:string;regionCode:string;taxableBaseCents:number;totalTaxCents:number;components:Array<{code:string;name:string;rateBasisPoints:number;amountCents:number}>} };
const parseJson=<T>(value:string):T=>JSON.parse(value) as T;
const businessDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Vancouver",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

export class InvoiceService {
  constructor(private readonly ledger:InvoicePaymentLedger=new PostgresInvoicePaymentLedger()) {}
  private async normalizedLines(repository:InvoiceRepository,organizationId:string,lines:InputLine[]){return Promise.all(lines.map(async line=>{if(!line.pricebookItemId)return{...line,totalCents:lineTotalCents(line.quantityMilli,line.unitPriceCents)};const item=await repository.pricebookItem(organizationId,line.pricebookItemId);if(!item)throw new ConflictError("Pricebook item is unavailable in this organization");return{pricebookItemId:item.id,description:item.name,category:item.type,unit:item.unit,quantityMilli:line.quantityMilli,unitPriceCents:item.sellPriceCents,taxable:item.taxable,totalCents:lineTotalCents(line.quantityMilli,item.sellPriceCents)}}));}
  private async pricing(repository:InvoiceRepository,organizationId:string,lines:Array<{quantityMilli:number;unitPriceCents:number;taxable:boolean}>){const profile=await new TaxRepository(repository.db).current(organizationId);const safe=profile??{enabled:false,pricesIncludeTax:false,currency:"CAD",countryCode:"",regionCode:"",components:[]};const totals=calculateInvoice(lines,safe);return{...totals,currency:safe.currency,taxSnapshot:JSON.stringify({enabled:safe.enabled,pricesIncludeTax:safe.pricesIncludeTax,countryCode:safe.countryCode,regionCode:safe.regionCode,currency:safe.currency,taxableBaseCents:totals.tax.taxableBaseCents,totalTaxCents:totals.tax.totalTaxCents,components:totals.tax.components})};}
  async create(actor:RequestActor,raw:unknown){await authorize(actor,"invoice.create");const input=parseInput(createInvoiceSchema,raw);try{return await getDb().transaction(async tx=>{const r=new InvoiceRepository(tx);await r.lockOrganization(actor.organizationId);let customerId:string,jobId:string|undefined,contractId:string|undefined,contractVersionId:string|undefined,quoteId:string|undefined,quoteVersionId:string|undefined,quoteOptionId:string|undefined,billingSnapshotOverride:string|undefined,lines:Array<InputLine&{totalCents:number}>,fixed:{subtotalCents:number;discountCents:number;taxCents:number;totalCents:number;currency:string;taxSnapshot:string}|null=null;
    if(input.source==="contract"){const contract=await r.contract(actor.organizationId,input.contractId);if(!contract||contract.status!=="signed"||!contract.currentVersionId)throw new ConflictError("Only an executed Contract can be invoiced");if(await r.activeForContract(actor.organizationId,contract.id))throw new ConflictError("This Contract already has an active Invoice");const version=await r.contractVersion(actor.organizationId,contract.id,contract.currentVersionId);if(!version||!version.signedAt||!version.documentHash)throw new ConflictError("Executed Contract provenance is incomplete");const commercial=parseJson<CommercialSnapshot>(version.commercialSnapshot);if(commercial.quoteId!==contract.quoteId||commercial.quoteVersionId!==contract.acceptedQuoteVersionId||commercial.optionId!==contract.acceptedOptionId||commercial.totalCents!==contract.acceptedTotalCents)throw new ConflictError("Contract commercial provenance is invalid");customerId=contract.customerId;contractId=contract.id;contractVersionId=version.id;quoteId=contract.quoteId;quoteVersionId=contract.acceptedQuoteVersionId;quoteOptionId=contract.acceptedOptionId;billingSnapshotOverride=version.customerSnapshot;lines=commercial.lines;fixed={subtotalCents:commercial.subtotalCents,discountCents:commercial.discountCents,taxCents:commercial.taxCents,totalCents:commercial.totalCents,currency:commercial.taxSnapshot?.currency??"CAD",taxSnapshot:JSON.stringify(commercial.taxSnapshot)};
    }else if(input.source==="job"){const job=await r.job(actor.organizationId,input.jobId);if(!job||!["completed","invoiced"].includes(job.status))throw new ConflictError("Job completion compliance must be satisfied before invoicing");if(await r.activeForJob(actor.organizationId,job.id))throw new ConflictError("This Job already has an active Invoice");customerId=job.customerId;jobId=job.id;lines=await this.normalizedLines(r,actor.organizationId,input.lines);
    }else{const customer=await r.customer(actor.organizationId,input.customerId);if(!customer)throw new ConflictError("Customer is unavailable in this organization");customerId=customer.id;lines=await this.normalizedLines(r,actor.organizationId,input.lines);}
    const customer=await r.customer(actor.organizationId,customerId);if(!customer)throw new ConflictError("Customer is unavailable in this organization");const priced=fixed??await this.pricing(r,actor.organizationId,lines);const sequenceNumber=await r.nextSequence(actor.organizationId);const invoice=await r.create({organizationId:actor.organizationId,sequenceNumber,identifier:`INV-${sequenceNumber}`,source:input.source,customerId,jobId,contractId,contractVersionId,quoteId,quoteVersionId,quoteOptionId,billingSnapshot:billingSnapshotOverride??JSON.stringify({customerId:customer.id,name:customer.name,email:customer.email,phone:customer.phone,addressLine1:customer.addressLine1,addressLine2:customer.addressLine2,city:customer.city,region:customer.region,postalCode:customer.postalCode}),taxSnapshot:priced.taxSnapshot,currency:priced.currency,paymentTerms:input.paymentTerms,dueDate:input.dueDate,notes:input.notes,terms:input.terms,subtotalCents:priced.subtotalCents,discountCents:priced.discountCents,taxCents:priced.taxCents,totalCents:priced.totalCents,createdBy:actor.userId,updatedBy:actor.userId});await r.insertLines(lines.map((line,sortOrder)=>({organizationId:actor.organizationId,invoiceId:invoice.id,pricebookItemId:line.pricebookItemId,description:line.description,category:line.category,unit:line.unit,quantityMilli:line.quantityMilli,unitPriceCents:line.unitPriceCents,taxable:line.taxable,totalCents:line.totalCents,sortOrder})));await r.history({organizationId:actor.organizationId,invoiceId:invoice.id,fromStatus:null,toStatus:"draft",actorUserId:actor.userId,reason:`Created from ${input.source}`});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.created",entityType:"invoice",entityId:invoice.id,metadata:{source:input.source,contractId,jobId}});return invoice;});}catch(error){if(error instanceof ConflictError)throw error;if(error instanceof Error&&/invoices_(live_(job|contract)|org_sequence)_unique/.test(error.message))throw new ConflictError("An active Invoice already exists for this source or number");throw error;}}
  async get(actor:RequestActor,id:string){await authorize(actor,"invoice.read");const r=new InvoiceRepository(),invoice=await r.find(actor.organizationId,id);if(!invoice)throw new NotFoundError("Invoice not found");const amountPaidCents=await this.ledger.amountPaidCents(actor.organizationId,id,r.db),balanceCents=invoiceBalance(invoice.totalCents,amountPaidCents);return{invoice:{...invoice,amountPaidCents,balanceCents,isOverdue:isInvoiceOverdue(invoice.status,invoice.dueDate,balanceCents,businessDate())},lines:await r.lines(actor.organizationId,id)};}
  async list(actor:RequestActor,raw:unknown={}){await authorize(actor,"invoice.read");return new InvoiceRepository().list(actor.organizationId,parseInput(invoiceFilterSchema,raw));}
  async updateDraft(actor:RequestActor,id:string,raw:unknown){await authorize(actor,"invoice.update");const input=parseInput(updateInvoiceSchema,raw);return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,id,true);if(!invoice)throw new NotFoundError("Invoice not found");assertDraft(invoice.status);if(!await r.claimVersion(actor.organizationId,id,input.expectedRowVersion))throw new ConflictError("Invoice changed; reload and retry");const dueDate=input.dueDate===null?null:input.dueDate;const result=await r.update(actor.organizationId,id,{notes:input.notes,terms:input.terms,paymentTerms:input.paymentTerms,dueDate,updatedBy:actor.userId});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.updated",entityType:"invoice",entityId:id,metadata:{}});return result;});}
  private async reprice(r:InvoiceRepository,organizationId:string,invoiceId:string){const lines=await r.lines(organizationId,invoiceId),priced=await this.pricing(r,organizationId,lines);await r.replaceTotals(organizationId,invoiceId,priced);return priced;}
  async updateLine(actor:RequestActor,invoiceId:string,lineId:string,raw:unknown){await authorize(actor,"invoice.update");const input=parseInput(invoiceLineSchema,raw);return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,invoiceId,true);if(!invoice)throw new NotFoundError("Invoice not found");assertDraft(invoice.status);if(invoice.source==="contract")throw new ConflictError("Contract-derived Invoice lines are immutable");if(!await r.claimVersion(actor.organizationId,invoiceId,input.expectedRowVersion))throw new ConflictError("Invoice changed; reload and retry");if(!await r.line(actor.organizationId,invoiceId,lineId))throw new NotFoundError("Invoice line not found");const [line]=await this.normalizedLines(r,actor.organizationId,[input]);await r.updateLine(actor.organizationId,invoiceId,lineId,line!);await this.reprice(r,actor.organizationId,invoiceId);await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.line_updated",entityType:"invoice",entityId:invoiceId,metadata:{lineId}});});}
  async removeLine(actor:RequestActor,invoiceId:string,lineId:string,expectedRowVersion:number){await authorize(actor,"invoice.update");return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,invoiceId,true);if(!invoice)throw new NotFoundError("Invoice not found");assertDraft(invoice.status);if(invoice.source==="contract")throw new ConflictError("Contract-derived Invoice lines are immutable");const lines=await r.lines(actor.organizationId,invoiceId);if(lines.length<=1)throw new ConflictError("An Invoice requires at least one line");if(!await r.claimVersion(actor.organizationId,invoiceId,expectedRowVersion))throw new ConflictError("Invoice changed; reload and retry");if(!await r.removeLine(actor.organizationId,invoiceId,lineId))throw new NotFoundError("Invoice line not found");await this.reprice(r,actor.organizationId,invoiceId);await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.line_removed",entityType:"invoice",entityId:invoiceId,metadata:{lineId}});});}
  async reorderLines(actor:RequestActor,invoiceId:string,raw:unknown){await authorize(actor,"invoice.update");const input=parseInput(reorderInvoiceLinesSchema,raw);return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,invoiceId,true);if(!invoice)throw new NotFoundError("Invoice not found");assertDraft(invoice.status);if(invoice.source==="contract")throw new ConflictError("Contract-derived Invoice lines are immutable");const lines=await r.lines(actor.organizationId,invoiceId);if(lines.length!==input.lineIds.length||input.lineIds.some(id=>!lines.some(line=>line.id===id)))throw new ConflictError("Complete Invoice line ordering is required");if(!await r.claimVersion(actor.organizationId,invoiceId,input.expectedRowVersion))throw new ConflictError("Invoice changed; reload and retry");await r.reorder(actor.organizationId,invoiceId,input.lineIds);await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.lines_reordered",entityType:"invoice",entityId:invoiceId,metadata:{}});});}
  async issue(actor:RequestActor,id:string){await authorize(actor,"invoice.issue");return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,id,true);if(!invoice)throw new NotFoundError("Invoice not found");assertDraft(invoice.status);if(!(await r.lines(actor.organizationId,id)).length)throw new ConflictError("An Invoice requires a line");const issueDate=businessDate(),dueDate=dueDateFor(issueDate,invoice.paymentTerms,invoice.dueDate),changed=await r.transition(actor.organizationId,id,"draft",{status:"issued",issueDate,dueDate,issuedAt:new Date(),updatedBy:actor.userId});if(!changed)throw new ConflictError("Invoice changed concurrently");await r.history({organizationId:actor.organizationId,invoiceId:id,fromStatus:"draft",toStatus:"issued",actorUserId:actor.userId});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.issued",entityType:"invoice",entityId:id,metadata:{issueDate,dueDate}});return changed;});}
  async void(actor:RequestActor,id:string,raw:unknown){await authorize(actor,"invoice.void");const input=parseInput(voidInvoiceSchema,raw);return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,id,true);if(!invoice)throw new NotFoundError("Invoice not found");if(invoice.status==="void")throw new ConflictError("Invoice is already void");const changed=await r.transition(actor.organizationId,id,invoice.status,{status:"void",voidedAt:new Date(),voidReason:input.reason,updatedBy:actor.userId});if(!changed)throw new ConflictError("Invoice changed concurrently");await r.history({organizationId:actor.organizationId,invoiceId:id,fromStatus:invoice.status,toStatus:"void",actorUserId:actor.userId,reason:input.reason});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"invoice.voided",entityType:"invoice",entityId:id,metadata:{previousStatus:invoice.status,reason:input.reason}});return changed;});}
  async deleteDraft(actor:RequestActor,id:string){await authorize(actor,"invoice.delete");return getDb().transaction(async tx=>{const r=new InvoiceRepository(tx),invoice=await r.find(actor.organizationId,id,true);if(!invoice)throw new NotFoundError("Invoice not found");assertDraft(invoice.status);if(!await r.hardDeleteDraft(actor.organizationId,id))throw new ConflictError("Invoice changed concurrently");});}
  async pdfModel(actor:RequestActor,id:string){const detail=await this.get(actor,id);const billing=parseJson<Record<string,string|null>>(detail.invoice.billingSnapshot),tax=parseJson<Record<string,unknown>|null>(detail.invoice.taxSnapshot);return{identifier:detail.invoice.identifier,status:detail.invoice.status,issueDate:detail.invoice.issueDate,dueDate:detail.invoice.dueDate,currency:detail.invoice.currency,customer:billing,lines:detail.lines,subtotalCents:detail.invoice.subtotalCents,discountCents:detail.invoice.discountCents,taxCents:detail.invoice.taxCents,totalCents:detail.invoice.totalCents,amountPaidCents:detail.invoice.amountPaidCents,balanceCents:detail.invoice.balanceCents,notes:detail.invoice.notes,terms:detail.invoice.terms,tax};}
}
