import { authorize } from "@/auth/authorization";
import { ConflictError, NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { changedFields, nullable, parseEntityId } from "@/modules/crm/crm.helpers";
import type { Authorizer, RequestActor } from "@/modules/customers/customer.service";
import { archivePipelineSchema, createPipelineSchema, createPipelineStageSchema, pipelineFilterSchema, reorderPipelineStagesSchema, setDefaultPipelineSchema, updatePipelineSchema, updatePipelineStageSchema, type CreatePipelineInput, type CreatePipelineStageInput, type ReorderPipelineStagesInput, type UpdatePipelineInput, type UpdatePipelineStageInput } from "./pipeline.schema";
import { PipelineRepository } from "./pipeline.repository";
import { PipelineStageRepository } from "./pipeline-stage.repository";
import { assertCompleteOrder, assertStageProbability, isUniqueViolation } from "./pipeline.rules";
import { DrizzlePipelineUnitOfWork, type PipelineUnitOfWork } from "./pipeline.unit-of-work";
import type { Pipeline, PipelineStage } from "./pipeline.types";

export interface PipelineWithStages { pipeline: Pipeline; stages: PipelineStage[] }

export class PipelineService {
  constructor(private readonly pipelines = new PipelineRepository(), private readonly stages = new PipelineStageRepository(), private readonly authorizer: Authorizer = authorize, private readonly unitOfWork: PipelineUnitOfWork = new DrizzlePipelineUnitOfWork()) {}

  async listPipelines(actor: RequestActor, raw: { query?: string } = {}): Promise<Pipeline[]> { await this.authorizer(actor, "pipeline.read"); const input = parseInput(pipelineFilterSchema, raw); return this.pipelines.list(actor.organizationId, input.query); }
  async getPipeline(actor: RequestActor, id: string): Promise<PipelineWithStages> { await this.authorizer(actor, "pipeline.read"); await this.authorizer(actor, "pipeline_stage.read"); id = parseEntityId(id); const pipeline = await this.pipelines.findById(actor.organizationId, id); if (!pipeline) throw new NotFoundError("Pipeline not found"); return { pipeline, stages: await this.stages.list(actor.organizationId, id) }; }

  async createPipeline(actor: RequestActor, raw: CreatePipelineInput): Promise<PipelineWithStages> {
    await this.authorizer(actor, "pipeline.create"); const input = parseInput(createPipelineSchema, raw); input.stages?.forEach((stage) => assertStageProbability(stage.kind, stage.probability));
    const names = input.stages?.map((stage) => stage.name.toLowerCase()) ?? []; if (new Set(names).size !== names.length) throw new ConflictError("Stage names must be unique within a pipeline");
    try {
      return await this.unitOfWork.transaction(async ({ pipelines, stages, audit }) => {
        await pipelines.lockOrganization(actor.organizationId); if (await pipelines.nameExists(actor.organizationId, input.name)) throw new ConflictError("An active pipeline with this name already exists");
        const makeDefault = input.makeDefault || await pipelines.countActive(actor.organizationId) === 0; if (makeDefault) await pipelines.clearDefault(actor.organizationId);
        const pipeline = await pipelines.create({ organizationId: actor.organizationId, name: input.name, description: nullable(input.description), isDefault: makeDefault, createdBy: actor.userId, updatedBy: actor.userId });
        const createdStages: PipelineStage[] = [];
        for (const [position, stage] of (input.stages ?? []).entries()) { const created = await stages.create({ organizationId: actor.organizationId, pipelineId: pipeline.id, name: stage.name, position, kind: stage.kind, probability: stage.probability, color: stage.color || null, createdBy: actor.userId, updatedBy: actor.userId }); createdStages.push(created); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline_stage.created", entityType: "pipeline_stage", entityId: created.id, metadata: { pipelineId: pipeline.id, position, kind: stage.kind } }); }
        await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline.created", entityType: "pipeline", entityId: pipeline.id, metadata: { isDefault: makeDefault, stageCount: createdStages.length } }); return { pipeline, stages: createdStages };
      });
    } catch (error) { if (isUniqueViolation(error)) throw new ConflictError("Pipeline or stage name/order conflicts with an existing record"); throw error; }
  }

  async updatePipeline(actor: RequestActor, id: string, raw: UpdatePipelineInput): Promise<Pipeline> {
    await this.authorizer(actor, "pipeline.update"); id = parseEntityId(id); const input = parseInput(updatePipelineSchema, raw);
    try { return await this.unitOfWork.transaction(async ({ pipelines, audit }) => { await pipelines.lockOrganization(actor.organizationId); if (!await pipelines.findByIdForUpdate(actor.organizationId, id)) throw new NotFoundError("Pipeline not found"); if (input.name && await pipelines.nameExists(actor.organizationId, input.name, id)) throw new ConflictError("An active pipeline with this name already exists"); const pipeline = await pipelines.update(actor.organizationId, id, { ...input, description: nullable(input.description), updatedBy: actor.userId }); if (!pipeline) throw new NotFoundError("Pipeline not found"); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline.updated", entityType: "pipeline", entityId: id, metadata: { fields: changedFields(input) } }); return pipeline; }); } catch (error) { if (isUniqueViolation(error)) throw new ConflictError("An active pipeline with this name already exists"); throw error; }
  }

  async setDefaultPipeline(actor: RequestActor, raw: { pipelineId: string }): Promise<Pipeline> {
    await this.authorizer(actor, "pipeline.update"); const { pipelineId } = parseInput(setDefaultPipelineSchema, raw);
    return this.unitOfWork.transaction(async ({ pipelines, audit }) => { await pipelines.lockOrganization(actor.organizationId); const target = await pipelines.findByIdForUpdate(actor.organizationId, pipelineId); if (!target) throw new NotFoundError("Pipeline not found"); if (target.isDefault) return target; const previous = (await pipelines.list(actor.organizationId)).find((pipeline) => pipeline.isDefault); await pipelines.clearDefault(actor.organizationId); const updated = await pipelines.markDefault(actor.organizationId, pipelineId, actor.userId); if (!updated) throw new NotFoundError("Pipeline not found"); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline.default_changed", entityType: "pipeline", entityId: pipelineId, metadata: { previousPipelineId: previous?.id ?? null } }); return updated; });
  }

  async archivePipeline(actor: RequestActor, id: string, raw: { replacementPipelineId?: string } = {}): Promise<void> {
    await this.authorizer(actor, "pipeline.delete"); id = parseEntityId(id); const input = parseInput(archivePipelineSchema, raw);
    await this.unitOfWork.transaction(async ({ pipelines, stages, deals, audit }) => { await pipelines.lockOrganization(actor.organizationId); const current = await pipelines.findByIdForUpdate(actor.organizationId, id); if (!current) throw new NotFoundError("Pipeline not found"); if (await deals.countActiveForPipeline(actor.organizationId, id)) throw new ConflictError("Archive active deals before archiving this pipeline"); const count = await pipelines.countActive(actor.organizationId); if (count === 1) throw new ConflictError("The only active pipeline cannot be archived"); let replacement: Pipeline | null = null; if (current.isDefault) { if (!input.replacementPipelineId || input.replacementPipelineId === id) throw new ConflictError("Choose another active pipeline as the default"); replacement = await pipelines.findByIdForUpdate(actor.organizationId, input.replacementPipelineId); if (!replacement) throw new NotFoundError("Replacement pipeline not found"); }
      const archivedStageCount = (await stages.listForUpdate(actor.organizationId, id)).length; await stages.archiveForPipeline(actor.organizationId, id, actor.userId); const archived = await pipelines.archive(actor.organizationId, id, actor.userId); if (!archived) throw new NotFoundError("Pipeline not found"); if (replacement) { await pipelines.markDefault(actor.organizationId, replacement.id, actor.userId); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline.default_changed", entityType: "pipeline", entityId: replacement.id, metadata: { previousPipelineId: id } }); } await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline.archived", entityType: "pipeline", entityId: id, metadata: { archivedStageCount } }); });
  }

  async createStage(actor: RequestActor, pipelineId: string, raw: CreatePipelineStageInput): Promise<PipelineStage> {
    await this.authorizer(actor, "pipeline_stage.create"); pipelineId = parseEntityId(pipelineId); const input = parseInput(createPipelineStageSchema, raw); assertStageProbability(input.kind, input.probability);
    try { return await this.unitOfWork.transaction(async ({ pipelines, stages, audit }) => { if (!await pipelines.findByIdForUpdate(actor.organizationId, pipelineId)) throw new NotFoundError("Pipeline not found"); if (await stages.nameExists(actor.organizationId, pipelineId, input.name)) throw new ConflictError("An active stage with this name already exists"); const position = (await stages.listForUpdate(actor.organizationId, pipelineId)).length; const stage = await stages.create({ organizationId: actor.organizationId, pipelineId, name: input.name, position, kind: input.kind, probability: input.probability, color: input.color || null, createdBy: actor.userId, updatedBy: actor.userId }); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline_stage.created", entityType: "pipeline_stage", entityId: stage.id, metadata: { pipelineId, position, kind: stage.kind } }); return stage; }); } catch (error) { if (isUniqueViolation(error)) throw new ConflictError("Stage name or position conflicts with an existing stage"); throw error; }
  }

  async updateStage(actor: RequestActor, pipelineId: string, id: string, raw: UpdatePipelineStageInput): Promise<PipelineStage> {
    await this.authorizer(actor, "pipeline_stage.update"); pipelineId = parseEntityId(pipelineId); id = parseEntityId(id); const input = parseInput(updatePipelineStageSchema, raw);
    try { return await this.unitOfWork.transaction(async ({ pipelines, stages, audit }) => { if (!await pipelines.findByIdForUpdate(actor.organizationId, pipelineId)) throw new NotFoundError("Pipeline not found"); const current = await stages.findById(actor.organizationId, id); if (!current || current.pipelineId !== pipelineId) throw new NotFoundError("Pipeline stage not found"); const kind = input.kind ?? current.kind; const probability = input.probability ?? current.probability; assertStageProbability(kind, probability); if (input.name && await stages.nameExists(actor.organizationId, pipelineId, input.name, id)) throw new ConflictError("An active stage with this name already exists"); const stage = await stages.update(actor.organizationId, pipelineId, id, { ...input, color: input.color === undefined ? undefined : input.color || null, updatedBy: actor.userId }); if (!stage) throw new NotFoundError("Pipeline stage not found"); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline_stage.updated", entityType: "pipeline_stage", entityId: id, metadata: { pipelineId, fields: changedFields(input) } }); return stage; }); } catch (error) { if (isUniqueViolation(error)) throw new ConflictError("An active stage with this name already exists"); throw error; }
  }

  async reorderStages(actor: RequestActor, pipelineId: string, raw: ReorderPipelineStagesInput): Promise<PipelineStage[]> {
    await this.authorizer(actor, "pipeline_stage.update"); pipelineId = parseEntityId(pipelineId); const input = parseInput(reorderPipelineStagesSchema, raw);
    return this.unitOfWork.transaction(async ({ pipelines, stages, audit }) => { if (!await pipelines.findByIdForUpdate(actor.organizationId, pipelineId)) throw new NotFoundError("Pipeline not found"); const current = await stages.listForUpdate(actor.organizationId, pipelineId); assertCompleteOrder(current.map((stage) => stage.id), input.stageIds); await stages.shiftToTemporaryPositions(actor.organizationId, pipelineId); for (const [position, id] of input.stageIds.entries()) { if (!await stages.setPosition(actor.organizationId, pipelineId, id, position, actor.userId)) throw new ConflictError("Stage ordering changed during reorder"); } await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline_stage.reordered", entityType: "pipeline", entityId: pipelineId, metadata: { stageIds: input.stageIds } }); return stages.list(actor.organizationId, pipelineId); });
  }

  async archiveStage(actor: RequestActor, pipelineId: string, id: string): Promise<void> {
    await this.authorizer(actor, "pipeline_stage.delete"); pipelineId = parseEntityId(pipelineId); id = parseEntityId(id);
    await this.unitOfWork.transaction(async ({ pipelines, stages, deals, audit }) => { if (!await pipelines.findByIdForUpdate(actor.organizationId, pipelineId)) throw new NotFoundError("Pipeline not found"); const current = await stages.findById(actor.organizationId, id); if (!current || current.pipelineId !== pipelineId) throw new NotFoundError("Pipeline stage not found"); if (await deals.countActiveForStage(actor.organizationId, pipelineId, id)) throw new ConflictError("Archive or move active deals before archiving this stage"); await stages.archive(actor.organizationId, pipelineId, id, actor.userId); const remaining = await stages.listForUpdate(actor.organizationId, pipelineId); await stages.shiftToTemporaryPositions(actor.organizationId, pipelineId); for (const [position, stage] of remaining.entries()) await stages.setPosition(actor.organizationId, pipelineId, stage.id, position, actor.userId); await audit.record({ organizationId: actor.organizationId, actorUserId: actor.userId, action: "pipeline_stage.archived", entityType: "pipeline_stage", entityId: id, metadata: { pipelineId } }); });
  }
}
