import { describe, expect, it } from "vitest";
import { can } from "@/auth/permissions";
import { ConflictError, ValidationError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { createAgreementSchema, createPlanSchema, createScheduleSchema, signAgreementSchema } from "./maintenance.schema";
import { advanceDueDate, agreementTransition, assertEntitlement, daysBetween, dueState, planMaterialChanges, renewalTerm, validateTerm } from "./maintenance.rules";

describe("Maintenance domain rules", () => {
  it("uses stable calendar recurrence including month-end and leap-year behavior", () => { expect(advanceDueDate("2024-02-29", "annual")).toBe("2025-02-28"); expect(advanceDueDate("2025-08-31", "semi_annual")).toBe("2026-02-28"); expect(advanceDueDate("2025-01-31", "quarterly")).toBe("2025-04-30"); expect(advanceDueDate("2025-03-08", "custom_days", 90)).toBe("2025-06-06"); });
  it("derives Vancouver business-date states without timestamp arithmetic", () => { expect(daysBetween("2025-03-08", "2025-03-09")).toBe(1); expect(dueState("2025-03-07", "2025-03-08")).toBe("overdue"); expect(dueState("2025-03-08", "2025-03-08")).toBe("due"); expect(dueState("2025-03-20", "2025-03-08")).toBe("upcoming"); });
  it("carries the actual term length into renewal", () => { expect(renewalTerm("2025-01-01", "2025-12-31")).toEqual({ effectiveDate: "2025-12-31", expiresOn: "2026-12-30" }); expect(() => validateTerm("2025-10-01", "2025-09-30")).toThrow(ValidationError); });
  it("enforces explicit lifecycle transitions", () => { expect(() => agreementTransition("draft", "sent")).not.toThrow(); expect(() => agreementTransition("viewed", "active")).not.toThrow(); expect(() => agreementTransition("active", "draft")).toThrow(ConflictError); });
  it("detects material benefit changes and finite entitlement exhaustion", () => { const plan = { status: "active", priceCents: 100, discountType: "percent", discountBasisPoints: 1000, discountFixedCents: null, visitEntitlementCount: 2 }; expect(planMaterialChanges({ priceCents: 99, discountType: "percent", discountBasisPoints: 1000, discountFixedCents: null, visitEntitlementCount: 2 }, plan)).toEqual(["price_changed"]); expect(() => assertEntitlement(2, 0)).toThrow(ConflictError); expect(() => assertEntitlement(null, 0)).not.toThrow(); });
  it("strictly validates plans, schedules, agreements and explicit consent", () => { expect(() => parseInput(createPlanSchema, { code: "GOLD", name: "Gold", priceCents: 100, discountType: "percent" })).toThrow(ValidationError); expect(() => parseInput(createScheduleSchema, { recurrence: "custom_days" })).toThrow(ValidationError); expect(() => parseInput(createAgreementSchema, { customerId: crypto.randomUUID(), planId: crypto.randomUUID(), effectiveDate: "2025-01-01", expiresOn: "2025-12-31", termsSnapshot: "Terms", serviceLocation: "1 Test Street", organizationId: crypto.randomUUID() })).toThrow(ValidationError); expect(() => parseInput(signAgreementSchema, { signerName: "Customer", signatureMethod: "typed", consentTextVersion: "v1" })).toThrow(ValidationError); });
  it("keeps Maintenance administration office-only", () => { expect(can({ role: "owner" }, "maintenance_plan.manage")).toBe(true); expect(can({ role: "manager" }, "maintenance_agreement.manage")).toBe(true); expect(can({ role: "member" }, "maintenance_agreement.read")).toBe(false); expect(can({ role: "viewer" }, "maintenance_plan.read")).toBe(false); });
});
