import"server-only";
import{and,asc,desc,eq,ilike,inArray,isNull,lte,or,sql}from"drizzle-orm";
import{getDb,type DatabaseExecutor}from"@/db";
import{customers,maintenanceAgreements,maintenanceAgreementStatusHistory,maintenanceAgreementVersions,maintenanceAutomationRuns,maintenanceEntitlementEvents,maintenanceMemberships,maintenanceOccurrences,maintenancePlans,maintenanceReminderIntents,maintenanceSchedules,maintenanceSignatureRequests,organizations}from"@/db/schema";

export class MaintenanceRepository{constructor(readonly db:DatabaseExecutor=getDb()){}
async lockOrganization(id:string){return(await this.db.select().from(organizations).where(eq(organizations.id,id)).for("update"))[0]}
async plan(org:string,id:string,lock=false){const q=this.db.select().from(maintenancePlans).where(and(eq(maintenancePlans.organizationId,org),eq(maintenancePlans.id,id)));return lock?(await q.for("update"))[0]:(await q)[0]}
async listPlans(org:string,input:{query?:string;status?:"active"|"inactive";limit:number}){return this.db.select().from(maintenancePlans).where(and(eq(maintenancePlans.organizationId,org),input.status?eq(maintenancePlans.status,input.status):undefined,input.query?or(ilike(maintenancePlans.code,`%${input.query}%`),ilike(maintenancePlans.name,`%${input.query}%`)):undefined)).orderBy(asc(maintenancePlans.sortOrder),asc(maintenancePlans.name)).limit(input.limit)}
async createPlan(value:typeof maintenancePlans.$inferInsert){return(await this.db.insert(maintenancePlans).values(value).returning())[0]!}
async updatePlan(org:string,id:string,expected:number,value:Partial<typeof maintenancePlans.$inferInsert>){return(await this.db.update(maintenancePlans).set({...value,id:undefined,organizationId:undefined,code:undefined,createdBy:undefined,createdAt:undefined,rowVersion:sql`${maintenancePlans.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(maintenancePlans.organizationId,org),eq(maintenancePlans.id,id),eq(maintenancePlans.rowVersion,expected))).returning())[0]}
async setPlanStatus(org:string,id:string,status:"active"|"inactive",actor:string){return(await this.db.update(maintenancePlans).set({status,updatedBy:actor,updatedAt:new Date()}).where(and(eq(maintenancePlans.organizationId,org),eq(maintenancePlans.id,id))).returning())[0]}
async customer(org:string,id:string){return this.db.query.customers.findFirst({where:and(eq(customers.organizationId,org),eq(customers.id,id),eq(customers.status,"active"),isNull(customers.archivedAt))})}
async nextAgreementSequence(org:string){const[row]=await this.db.select({value:sql<number>`coalesce(max(${maintenanceAgreements.sequenceNumber}),0)+1`}).from(maintenanceAgreements).where(eq(maintenanceAgreements.organizationId,org));return Number(row?.value??1)}
async createAgreement(value:typeof maintenanceAgreements.$inferInsert){return(await this.db.insert(maintenanceAgreements).values(value).returning())[0]!}
async createVersion(value:typeof maintenanceAgreementVersions.$inferInsert){return(await this.db.insert(maintenanceAgreementVersions).values(value).returning())[0]!}
async setCurrentVersion(org:string,id:string,versionId:string){return(await this.db.update(maintenanceAgreements).set({currentVersionId:versionId,updatedAt:new Date()}).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.id,id))).returning())[0]}
async agreement(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceAgreements).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.id,id)));return lock?(await q.for("update"))[0]:(await q)[0]}
async version(org:string,agreementId:string,id:string){return this.db.query.maintenanceAgreementVersions.findFirst({where:and(eq(maintenanceAgreementVersions.organizationId,org),eq(maintenanceAgreementVersions.agreementId,agreementId),eq(maintenanceAgreementVersions.id,id))})}
async listAgreements(org:string,input:{query?:string;customerId?:string;status?:typeof maintenanceAgreements.$inferSelect.status;dueBefore?:string;limit:number}){return this.db.select({agreement:maintenanceAgreements,customerName:customers.name,expiresOn:maintenanceAgreementVersions.expiresOn}).from(maintenanceAgreements).innerJoin(customers,and(eq(customers.organizationId,maintenanceAgreements.organizationId),eq(customers.id,maintenanceAgreements.customerId))).innerJoin(maintenanceAgreementVersions,and(eq(maintenanceAgreementVersions.organizationId,maintenanceAgreements.organizationId),eq(maintenanceAgreementVersions.id,maintenanceAgreements.currentVersionId))).where(and(eq(maintenanceAgreements.organizationId,org),input.status?eq(maintenanceAgreements.status,input.status):undefined,input.customerId?eq(maintenanceAgreements.customerId,input.customerId):undefined,input.dueBefore?lte(maintenanceAgreementVersions.expiresOn,input.dueBefore):undefined,input.query?or(ilike(maintenanceAgreements.identifier,`%${input.query}%`),ilike(customers.name,`%${input.query}%`)):undefined)).orderBy(asc(maintenanceAgreementVersions.expiresOn),desc(maintenanceAgreements.updatedAt)).limit(input.limit)}
async transition(org:string,id:string,from:typeof maintenanceAgreements.$inferSelect.status,to:typeof maintenanceAgreements.$inferSelect.status,value:Partial<typeof maintenanceAgreements.$inferInsert>={}){return(await this.db.update(maintenanceAgreements).set({...value,status:to,rowVersion:sql`${maintenanceAgreements.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.id,id),eq(maintenanceAgreements.status,from))).returning())[0]}
async history(value:typeof maintenanceAgreementStatusHistory.$inferInsert){return(await this.db.insert(maintenanceAgreementStatusHistory).values(value).returning())[0]!}
async historyFor(org:string,id:string){return this.db.select().from(maintenanceAgreementStatusHistory).where(and(eq(maintenanceAgreementStatusHistory.organizationId,org),eq(maintenanceAgreementStatusHistory.agreementId,id))).orderBy(asc(maintenanceAgreementStatusHistory.createdAt),asc(maintenanceAgreementStatusHistory.id))}
async revokeLiveRequests(org:string,agreementId:string){await this.db.update(maintenanceSignatureRequests).set({status:"revoked",updatedAt:new Date()}).where(and(eq(maintenanceSignatureRequests.organizationId,org),eq(maintenanceSignatureRequests.agreementId,agreementId),eq(maintenanceSignatureRequests.status,"pending")))}
async createSignatureRequest(value:typeof maintenanceSignatureRequests.$inferInsert){return(await this.db.insert(maintenanceSignatureRequests).values(value).returning())[0]!}
async requestByHash(hash:string,lock=false){const q=this.db.select().from(maintenanceSignatureRequests).where(eq(maintenanceSignatureRequests.tokenHash,hash));return lock?(await q.for("update"))[0]:(await q)[0]}
async markRequestViewed(id:string){await this.db.update(maintenanceSignatureRequests).set({updatedAt:new Date()}).where(and(eq(maintenanceSignatureRequests.id,id),eq(maintenanceSignatureRequests.status,"pending")))}
async expireRequest(id:string){return(await this.db.update(maintenanceSignatureRequests).set({status:"expired",updatedAt:new Date()}).where(and(eq(maintenanceSignatureRequests.id,id),eq(maintenanceSignatureRequests.status,"pending"))).returning())[0]}
async signRequest(id:string,value:Partial<typeof maintenanceSignatureRequests.$inferInsert>){return(await this.db.update(maintenanceSignatureRequests).set({...value,status:"signed",rowVersion:sql`${maintenanceSignatureRequests.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(maintenanceSignatureRequests.id,id),eq(maintenanceSignatureRequests.status,"pending"))).returning())[0]}
async finalizeVersion(org:string,id:string,value:Partial<typeof maintenanceAgreementVersions.$inferInsert>){return(await this.db.update(maintenanceAgreementVersions).set(value).where(and(eq(maintenanceAgreementVersions.organizationId,org),eq(maintenanceAgreementVersions.id,id),isNull(maintenanceAgreementVersions.signedAt))).returning())[0]}
async createMembership(value:typeof maintenanceMemberships.$inferInsert){return(await this.db.insert(maintenanceMemberships).values(value).onConflictDoNothing().returning())[0]}
async membership(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceMemberships).where(and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.id,id)));return lock?(await q.for("update"))[0]:(await q)[0]}
async membershipForAgreement(org:string,agreementId:string){return this.db.query.maintenanceMemberships.findFirst({where:and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.agreementId,agreementId))})}
async setMembershipStatus(org:string,id:string,status:typeof maintenanceMemberships.$inferSelect.status,reason?:string){return(await this.db.update(maintenanceMemberships).set({status,cancelReason:reason,updatedAt:new Date(),cancelledAt:status==="cancelled"?new Date():undefined}).where(and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.id,id))).returning())[0]}
async addEntitlement(value:typeof maintenanceEntitlementEvents.$inferInsert){return(await this.db.insert(maintenanceEntitlementEvents).values(value).onConflictDoNothing().returning())[0]}
async entitlement(org:string,membershipId:string){const[row]=await this.db.select({value:sql<number>`coalesce(sum(${maintenanceEntitlementEvents.visitDelta}),0)`}).from(maintenanceEntitlementEvents).where(and(eq(maintenanceEntitlementEvents.organizationId,org),eq(maintenanceEntitlementEvents.membershipId,membershipId)));return Number(row?.value??0)}
async createSchedule(value:typeof maintenanceSchedules.$inferInsert){return(await this.db.insert(maintenanceSchedules).values(value).returning())[0]!}
async schedule(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceSchedules).where(and(eq(maintenanceSchedules.organizationId,org),eq(maintenanceSchedules.id,id)));return lock?(await q.for("update"))[0]:(await q)[0]}
async scheduleForMembership(org:string,membershipId:string){return this.db.query.maintenanceSchedules.findFirst({where:and(eq(maintenanceSchedules.organizationId,org),eq(maintenanceSchedules.membershipId,membershipId))})}
async setScheduleStatus(org:string,id:string,status:typeof maintenanceSchedules.$inferSelect.status,reason?:string){return(await this.db.update(maintenanceSchedules).set({status,pauseReason:reason,updatedAt:new Date()}).where(and(eq(maintenanceSchedules.organizationId,org),eq(maintenanceSchedules.id,id))).returning())[0]}
async dueSchedules(org:string,today:string){return this.db.select().from(maintenanceSchedules).where(and(eq(maintenanceSchedules.organizationId,org),eq(maintenanceSchedules.status,"active"),eq(maintenanceSchedules.automationEnabled,true),lte(maintenanceSchedules.nextDueDate,today))).orderBy(asc(maintenanceSchedules.nextDueDate),asc(maintenanceSchedules.id))}
async createOccurrence(value:typeof maintenanceOccurrences.$inferInsert){return(await this.db.insert(maintenanceOccurrences).values(value).onConflictDoNothing().returning())[0]}
async occurrenceForCycle(org:string,scheduleId:string,cycle:number){return this.db.query.maintenanceOccurrences.findFirst({where:and(eq(maintenanceOccurrences.organizationId,org),eq(maintenanceOccurrences.scheduleId,scheduleId),eq(maintenanceOccurrences.cycleNumber,cycle))})}
async finishOccurrence(org:string,id:string,value:Partial<typeof maintenanceOccurrences.$inferInsert>){return(await this.db.update(maintenanceOccurrences).set(value).where(and(eq(maintenanceOccurrences.organizationId,org),eq(maintenanceOccurrences.id,id),eq(maintenanceOccurrences.status,"claimed"))).returning())[0]}
async advanceSchedule(org:string,id:string,cycle:number,next:string){return(await this.db.update(maintenanceSchedules).set({cyclesGenerated:cycle,nextDueDate:next,updatedAt:new Date()}).where(and(eq(maintenanceSchedules.organizationId,org),eq(maintenanceSchedules.id,id),eq(maintenanceSchedules.cyclesGenerated,cycle-1))).returning())[0]}
async occurrences(org:string,scheduleId:string){return this.db.select().from(maintenanceOccurrences).where(and(eq(maintenanceOccurrences.organizationId,org),eq(maintenanceOccurrences.scheduleId,scheduleId))).orderBy(desc(maintenanceOccurrences.dueDate),desc(maintenanceOccurrences.id))}
async renewalCandidates(org:string,todayPlus14:string,today:string){return this.db.select({agreement:maintenanceAgreements,version:maintenanceAgreementVersions,plan:maintenancePlans}).from(maintenanceAgreements).innerJoin(maintenanceAgreementVersions,and(eq(maintenanceAgreementVersions.organizationId,maintenanceAgreements.organizationId),eq(maintenanceAgreementVersions.id,maintenanceAgreements.currentVersionId))).innerJoin(maintenancePlans,and(eq(maintenancePlans.organizationId,maintenanceAgreements.organizationId),eq(maintenancePlans.id,maintenanceAgreements.planId))).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.status,"active"),isNull(maintenanceAgreements.supersededByAgreementId),lte(maintenanceAgreementVersions.expiresOn,todayPlus14),sql`${maintenanceAgreementVersions.expiresOn}>=${today}`)).orderBy(asc(maintenanceAgreementVersions.expiresOn))}
async reminderCandidates(org:string,dates:string[]){return this.db.select({agreement:maintenanceAgreements,version:maintenanceAgreementVersions,customer:customers}).from(maintenanceAgreements).innerJoin(maintenanceAgreementVersions,and(eq(maintenanceAgreementVersions.organizationId,maintenanceAgreements.organizationId),eq(maintenanceAgreementVersions.id,maintenanceAgreements.currentVersionId))).innerJoin(customers,and(eq(customers.organizationId,maintenanceAgreements.organizationId),eq(customers.id,maintenanceAgreements.customerId))).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.status,"active"),inArray(maintenanceAgreementVersions.expiresOn,dates)))}
async createReminder(value:typeof maintenanceReminderIntents.$inferInsert){return(await this.db.insert(maintenanceReminderIntents).values(value).onConflictDoNothing().returning())[0]}
async reminders(org:string,agreementId:string){return this.db.select().from(maintenanceReminderIntents).where(and(eq(maintenanceReminderIntents.organizationId,org),eq(maintenanceReminderIntents.agreementId,agreementId))).orderBy(desc(maintenanceReminderIntents.createdAt))}
async cancelReminders(org:string,agreementId:string){await this.db.update(maintenanceReminderIntents).set({status:"cancelled"}).where(and(eq(maintenanceReminderIntents.organizationId,org),eq(maintenanceReminderIntents.agreementId,agreementId),eq(maintenanceReminderIntents.status,"pending")))}
async claimRenewal(org:string,oldId:string,newId:string){return(await this.db.update(maintenanceAgreements).set({supersededByAgreementId:newId,updatedAt:new Date()}).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.id,oldId),isNull(maintenanceAgreements.supersededByAgreementId))).returning())[0]}
async linkSupersedes(org:string,newId:string,oldId:string){await this.db.update(maintenanceAgreements).set({supersedesAgreementId:oldId,updatedAt:new Date()}).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.id,newId)))}
async createRun(value:typeof maintenanceAutomationRuns.$inferInsert){return(await this.db.insert(maintenanceAutomationRuns).values(value).returning())[0]!}
async runs(org:string,limit:number){return this.db.select().from(maintenanceAutomationRuns).where(eq(maintenanceAutomationRuns.organizationId,org)).orderBy(desc(maintenanceAutomationRuns.createdAt)).limit(limit)}
}
