import "server-only";
import { and, asc, desc, eq, isNull, sql } from "drizzle-orm";
import { getDb, type DatabaseExecutor } from "@/db";
import { assets, attachments, jobs, jobStatusHistory, maintenanceAgreementCoverage, maintenanceAgreements, maintenanceAgreementVersions, maintenanceBenefitApplications, maintenanceChecklistTemplates, maintenanceChecklistVersions, maintenanceEntitlementEvents, maintenanceLegalDocuments, maintenanceLegalVersions, maintenanceMemberships, maintenanceOccurrences, maintenanceOutbox, maintenancePlans, maintenanceReminderIntents, maintenanceServiceReports, maintenanceSignedArtifacts } from "@/db/schema";

export class MaintenanceParityRepository {
  constructor(readonly db:DatabaseExecutor=getDb()){}
  asset(org:string,id:string,lock=false){const q=this.db.select().from(assets).where(and(eq(assets.organizationId,org),eq(assets.id,id)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  listAssets(org:string,customerId?:string){return this.db.select().from(assets).where(and(eq(assets.organizationId,org),customerId?eq(assets.customerId,customerId):undefined)).orderBy(asc(assets.displayName),asc(assets.id))}
  createAsset(v:typeof assets.$inferInsert){return this.db.insert(assets).values(v).returning().then(x=>x[0]!)}
  updateAsset(org:string,id:string,expected:number,v:Partial<typeof assets.$inferInsert>){return this.db.update(assets).set({...v,id:undefined,organizationId:undefined,customerId:undefined,rowVersion:sql`${assets.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(assets.organizationId,org),eq(assets.id,id),eq(assets.rowVersion,expected))).returning().then(x=>x[0])}
  setAssetStatus(org:string,id:string,status:"active"|"inactive"|"retired",actor:string){return this.db.update(assets).set({status,updatedBy:actor,rowVersion:sql`${assets.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(assets.organizationId,org),eq(assets.id,id))).returning().then(x=>x[0])}
  createLegalDocument(v:typeof maintenanceLegalDocuments.$inferInsert){return this.db.insert(maintenanceLegalDocuments).values(v).returning().then(x=>x[0]!)}
  listLegalDocuments(org:string){return this.db.select().from(maintenanceLegalDocuments).where(eq(maintenanceLegalDocuments.organizationId,org)).orderBy(asc(maintenanceLegalDocuments.title))}
  legalDocument(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceLegalDocuments).where(and(eq(maintenanceLegalDocuments.organizationId,org),eq(maintenanceLegalDocuments.id,id)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  legalVersion(org:string,id:string){return this.db.query.maintenanceLegalVersions.findFirst({where:and(eq(maintenanceLegalVersions.organizationId,org),eq(maintenanceLegalVersions.id,id))})}
  createLegalVersion(v:typeof maintenanceLegalVersions.$inferInsert){return this.db.insert(maintenanceLegalVersions).values(v).returning().then(x=>x[0]!)}
  nextLegalVersion(org:string,documentId:string){return this.db.select({n:sql<number>`coalesce(max(${maintenanceLegalVersions.versionNumber}),0)+1`}).from(maintenanceLegalVersions).where(and(eq(maintenanceLegalVersions.organizationId,org),eq(maintenanceLegalVersions.documentId,documentId))).then(x=>Number(x[0]?.n??1))}
  publishLegal(org:string,documentId:string,versionId:string,actor:string){return this.db.update(maintenanceLegalVersions).set({status:"published",publishedAt:new Date(),publishedBy:actor}).where(and(eq(maintenanceLegalVersions.organizationId,org),eq(maintenanceLegalVersions.documentId,documentId),eq(maintenanceLegalVersions.id,versionId),eq(maintenanceLegalVersions.status,"draft"))).returning().then(x=>x[0])}
  supersedeLegal(org:string,documentId:string,except:string){return this.db.update(maintenanceLegalVersions).set({status:"superseded"}).where(and(eq(maintenanceLegalVersions.organizationId,org),eq(maintenanceLegalVersions.documentId,documentId),eq(maintenanceLegalVersions.status,"published"),sql`${maintenanceLegalVersions.id}<>${except}`))}
  setPublishedLegal(org:string,id:string,versionId:string){return this.db.update(maintenanceLegalDocuments).set({currentPublishedVersionId:versionId,updatedAt:new Date()}).where(and(eq(maintenanceLegalDocuments.organizationId,org),eq(maintenanceLegalDocuments.id,id))).returning().then(x=>x[0])}
  createChecklistTemplate(v:typeof maintenanceChecklistTemplates.$inferInsert){return this.db.insert(maintenanceChecklistTemplates).values(v).returning().then(x=>x[0]!)}
  listChecklistTemplates(org:string){return this.db.select().from(maintenanceChecklistTemplates).where(eq(maintenanceChecklistTemplates.organizationId,org)).orderBy(asc(maintenanceChecklistTemplates.name))}
  checklistTemplate(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceChecklistTemplates).where(and(eq(maintenanceChecklistTemplates.organizationId,org),eq(maintenanceChecklistTemplates.id,id)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  checklistVersion(org:string,id:string){return this.db.query.maintenanceChecklistVersions.findFirst({where:and(eq(maintenanceChecklistVersions.organizationId,org),eq(maintenanceChecklistVersions.id,id))})}
  createChecklistVersion(v:typeof maintenanceChecklistVersions.$inferInsert){return this.db.insert(maintenanceChecklistVersions).values(v).returning().then(x=>x[0]!)}
  nextChecklistVersion(org:string,templateId:string){return this.db.select({n:sql<number>`coalesce(max(${maintenanceChecklistVersions.versionNumber}),0)+1`}).from(maintenanceChecklistVersions).where(and(eq(maintenanceChecklistVersions.organizationId,org),eq(maintenanceChecklistVersions.templateId,templateId))).then(x=>Number(x[0]?.n??1))}
  publishChecklist(org:string,templateId:string,versionId:string,actor:string){return this.db.update(maintenanceChecklistVersions).set({status:"published",publishedAt:new Date(),publishedBy:actor}).where(and(eq(maintenanceChecklistVersions.organizationId,org),eq(maintenanceChecklistVersions.templateId,templateId),eq(maintenanceChecklistVersions.id,versionId),eq(maintenanceChecklistVersions.status,"draft"))).returning().then(x=>x[0])}
  supersedeChecklist(org:string,templateId:string,except:string){return this.db.update(maintenanceChecklistVersions).set({status:"superseded"}).where(and(eq(maintenanceChecklistVersions.organizationId,org),eq(maintenanceChecklistVersions.templateId,templateId),eq(maintenanceChecklistVersions.status,"published"),sql`${maintenanceChecklistVersions.id}<>${except}`))}
  setPublishedChecklist(org:string,id:string,versionId:string){return this.db.update(maintenanceChecklistTemplates).set({currentPublishedVersionId:versionId,updatedAt:new Date()}).where(and(eq(maintenanceChecklistTemplates.organizationId,org),eq(maintenanceChecklistTemplates.id,id))).returning().then(x=>x[0])}
  addCoverage(values:Array<typeof maintenanceAgreementCoverage.$inferInsert>){return this.db.insert(maintenanceAgreementCoverage).values(values).onConflictDoNothing().returning()}
  coverage(org:string,agreementVersionId:string){return this.db.select().from(maintenanceAgreementCoverage).where(and(eq(maintenanceAgreementCoverage.organizationId,org),eq(maintenanceAgreementCoverage.agreementVersionId,agreementVersionId))).orderBy(asc(maintenanceAgreementCoverage.createdAt))}
  agreement(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceAgreements).where(and(eq(maintenanceAgreements.organizationId,org),eq(maintenanceAgreements.id,id)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  agreementVersion(org:string,id:string){return this.db.query.maintenanceAgreementVersions.findFirst({where:and(eq(maintenanceAgreementVersions.organizationId,org),eq(maintenanceAgreementVersions.id,id))})}
  membership(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceMemberships).where(and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.id,id)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  activeMembershipForCustomer(org:string,customerId:string,today:string){return this.db.select({membership:maintenanceMemberships,plan:maintenancePlans}).from(maintenanceMemberships).innerJoin(maintenancePlans,and(eq(maintenancePlans.organizationId,maintenanceMemberships.organizationId),eq(maintenancePlans.id,maintenanceMemberships.planId))).where(and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.customerId,customerId),eq(maintenanceMemberships.status,"active"),sql`${maintenanceMemberships.effectiveStart}<=${today}`,sql`${maintenanceMemberships.effectiveEnd}>=${today}`)).orderBy(desc(maintenanceMemberships.createdAt)).limit(1).then(x=>x[0])}
  occurrence(org:string,id:string){return this.db.query.maintenanceOccurrences.findFirst({where:and(eq(maintenanceOccurrences.organizationId,org),eq(maintenanceOccurrences.id,id))})}
  job(org:string,id:string,lock=false){const q=this.db.select().from(jobs).where(and(eq(jobs.organizationId,org),eq(jobs.id,id),isNull(jobs.archivedAt)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  attachment(org:string,id:string){return this.db.query.attachments.findFirst({where:and(eq(attachments.organizationId,org),eq(attachments.id,id),isNull(attachments.archivedAt),isNull(attachments.storageDeletedAt))})}
  createReport(v:typeof maintenanceServiceReports.$inferInsert){return this.db.insert(maintenanceServiceReports).values(v).onConflictDoNothing().returning().then(x=>x[0])}
  report(org:string,id:string,lock=false){const q=this.db.select().from(maintenanceServiceReports).where(and(eq(maintenanceServiceReports.organizationId,org),eq(maintenanceServiceReports.id,id)));return lock?q.for("update").then(x=>x[0]):q.then(x=>x[0])}
  reportForJob(org:string,jobId:string){return this.db.query.maintenanceServiceReports.findFirst({where:and(eq(maintenanceServiceReports.organizationId,org),eq(maintenanceServiceReports.jobId,jobId))})}
  listReports(org:string,limit=50){return this.db.select().from(maintenanceServiceReports).where(eq(maintenanceServiceReports.organizationId,org)).orderBy(desc(maintenanceServiceReports.createdAt)).limit(limit)}
  submitReport(org:string,id:string,expected:number,v:Partial<typeof maintenanceServiceReports.$inferInsert>){return this.db.update(maintenanceServiceReports).set({...v,status:"submitted",rowVersion:sql`${maintenanceServiceReports.rowVersion}+1`,updatedAt:new Date()}).where(and(eq(maintenanceServiceReports.organizationId,org),eq(maintenanceServiceReports.id,id),eq(maintenanceServiceReports.status,"draft"),eq(maintenanceServiceReports.rowVersion,expected))).returning().then(x=>x[0])}
  artifact(org:string,versionId:string){return this.db.query.maintenanceSignedArtifacts.findFirst({where:and(eq(maintenanceSignedArtifacts.organizationId,org),eq(maintenanceSignedArtifacts.agreementVersionId,versionId))})}
  createArtifact(v:typeof maintenanceSignedArtifacts.$inferInsert){return this.db.insert(maintenanceSignedArtifacts).values(v).onConflictDoNothing().returning().then(x=>x[0])}
  addBenefit(v:typeof maintenanceBenefitApplications.$inferInsert){return this.db.insert(maintenanceBenefitApplications).values(v).onConflictDoNothing().returning().then(x=>x[0])}
  async benefitByKey(org:string,key:string){const benefit=await this.db.query.maintenanceBenefitApplications.findFirst({where:and(eq(maintenanceBenefitApplications.organizationId,org),eq(maintenanceBenefitApplications.idempotencyKey,key))});return benefit??(key.startsWith("maintenance-job:")?await this.entitlementByKey(org,key):undefined)}
  addOutbox(v:typeof maintenanceOutbox.$inferInsert){return this.db.insert(maintenanceOutbox).values(v).onConflictDoNothing().returning().then(x=>x[0])}
  outbox(org:string,status?:typeof maintenanceOutbox.$inferSelect.status,limit=50){return this.db.select().from(maintenanceOutbox).where(and(eq(maintenanceOutbox.organizationId,org),status?eq(maintenanceOutbox.status,status):undefined)).orderBy(asc(maintenanceOutbox.createdAt)).limit(limit)}
  reminder(org:string,id:string){return this.db.query.maintenanceReminderIntents.findFirst({where:and(eq(maintenanceReminderIntents.organizationId,org),eq(maintenanceReminderIntents.id,id))})}
  entitlement(org:string,membershipId:string){return this.db.select({value:sql<number>`coalesce(sum(${maintenanceEntitlementEvents.visitDelta}),0)`}).from(maintenanceEntitlementEvents).where(and(eq(maintenanceEntitlementEvents.organizationId,org),eq(maintenanceEntitlementEvents.membershipId,membershipId))).then(x=>Number(x[0]?.value??0))}
  entitlementByKey(org:string,key:string){return this.db.query.maintenanceEntitlementEvents.findFirst({where:and(eq(maintenanceEntitlementEvents.organizationId,org),eq(maintenanceEntitlementEvents.idempotencyKey,key))})}
  consumeEntitlement(v:typeof maintenanceEntitlementEvents.$inferInsert){return this.db.insert(maintenanceEntitlementEvents).values(v).onConflictDoNothing().returning().then(x=>x[0])}
  completeJob(org:string,id:string,actor:string){return this.db.update(jobs).set({status:"completed",completedAt:new Date(),updatedBy:actor,updatedAt:new Date()}).where(and(eq(jobs.organizationId,org),eq(jobs.id,id),eq(jobs.status,"in_progress"))).returning().then(x=>x[0])}
  addJobHistory(v:typeof jobStatusHistory.$inferInsert){return this.db.insert(jobStatusHistory).values(v).returning().then(x=>x[0]!)}
}
