import { describe,expect,it } from "vitest";
import type { ObjectStorage } from "@/lib/r2";
import { AttachmentService } from "@/modules/attachments/attachment.service";
import { CustomerService } from "@/modules/customers/customer.service";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { JobService } from "@/modules/jobs/job.service";
import { EstimateService } from "@/modules/estimates/estimate.service";
import { ConflictError,ForbiddenError,NotFoundError } from "@/lib/errors";
import { MaintenanceAutomationService } from "./maintenance.automation";
import { MaintenanceParityService } from "./maintenance-parity.service";
import { MaintenanceService,type MaintenanceClock } from "./maintenance.service";

class MemoryStorage implements ObjectStorage{objects=new Map<string,Uint8Array>();async put(k:string,b:Uint8Array){this.objects.set(k,b)}async get(k:string){const b=this.objects.get(k);if(!b)throw new Error("missing");return b}async delete(k:string){this.objects.delete(k)}async signedDownloadUrl(k:string){return`https://storage.example.test/${encodeURIComponent(k)}`}}
describe.sequential("PostgreSQL Maintenance parity completion",()=>{
 const fixed=new Date("2026-09-08T18:00:00Z"),clock:MaintenanceClock={now:()=>fixed,today:()=>"2026-09-08"},storage=new MemoryStorage(),parity=new MaintenanceParityService(storage),maintenance=new MaintenanceService(clock),automation=new MaintenanceAutomationService(clock),jobs=new JobService(),attachments=new AttachmentService(undefined,undefined,undefined,storage);
 let a:Awaited<ReturnType<OrganizationService["createOrganizationWithOwner"]>>,b:typeof a,customer:Awaited<ReturnType<CustomerService["createCustomer"]>>,foreignCustomer:typeof customer,tech:Awaited<ReturnType<UserService["createUserWithMembership"]>>,plan:Awaited<ReturnType<MaintenanceService["createPlan"]>>,agreementId:string,membershipId:string,occurrenceId:string,jobId:string,assetId:string,checklistVersionId:string,reportId:string;
 const actor=()=>({userId:a.user.id,organizationId:a.organization.id,role:"owner" as const}),foreign=()=>({userId:b.user.id,organizationId:b.organization.id,role:"owner" as const}),pdf=new TextEncoder().encode("%PDF-1.7 evidence");
 it("creates tenant fixtures and rejects cross-tenant Asset ownership",async()=>{const organizations=new OrganizationService();a=await organizations.createOrganizationWithOwner({name:"Parity A",slug:`parity-a-${crypto.randomUUID()}`},{name:"Owner",email:`parity-a-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-123"});b=await organizations.createOrganizationWithOwner({name:"Parity B",slug:`parity-b-${crypto.randomUUID()}`},{name:"Owner",email:`parity-b-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-456"});customer=await new CustomerService().createCustomer(actor(),{name:"Synthetic Customer",email:"synthetic@example.test"});foreignCustomer=await new CustomerService().createCustomer(foreign(),{name:"Foreign"});tech=await new UserService().createUserWithMembership(actor(),{name:"Technician",email:`tech-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-789"},"member");await expect(parity.createAsset(actor(),{customerId:foreignCustomer.id,type:"furnace",serviceLocation:"100 Test"})).rejects.toBeInstanceOf(NotFoundError);const asset=await parity.createAsset(actor(),{customerId:customer.id,type:"furnace",displayName:"Synthetic Furnace",manufacturer:"Example",model:"F-1",serialNumber:"TEST-1",serviceLocation:"100 Test"});assetId=asset.id;expect(await parity.listAssets(actor(),customer.id)).toHaveLength(1);expect(await parity.listAssets(foreign(),customer.id)).toHaveLength(0)});
 it("publishes immutable tenant-local legal and checklist versions",async()=>{const legal=await parity.createLegalDocument(actor(),{title:"Maintenance terms",content:"Synthetic terms v1"});await parity.publishLegalVersion(actor(),legal.document.id,legal.version.id);await expect(parity.publishLegalVersion(foreign(),legal.document.id,legal.version.id)).rejects.toBeInstanceOf(NotFoundError);const checklist=await parity.createChecklistTemplate(actor(),{name:"Annual furnace",applicability:["furnace"],sections:[{title:"Safety",items:[{key:"safe",label:"Safety checked",type:"PASS_FAIL",required:true}]}]});await parity.publishChecklistVersion(actor(),checklist.template.id,checklist.version.id);checklistVersionId=checklist.version.id;await expect(parity.createChecklistVersion(foreign(),checklist.template.id,{sections:[{title:"x",items:[{key:"x",label:"x",type:"TEXT"}]}]})).rejects.toBeInstanceOf(NotFoundError)});
 it("snapshots covered equipment before Agreement issuance and retains signed PDF",async()=>{plan=await maintenance.createPlan(actor(),{code:`PARITY-${crypto.randomUUID().slice(0,8)}`,name:"Parity Gold",priceCents:20000,currency:"CAD",visitEntitlementCount:1,discountType:"percent",discountBasisPoints:1000,includedServices:["inspection"],equipmentEligibility:["furnace"]});const created=await maintenance.createAgreement(actor(),{customerId:customer.id,planId:plan.id,effectiveDate:"2026-01-01",expiresOn:"2027-12-31",renewalPreference:"manual",termsSnapshot:"Signed synthetic terms",serviceLocation:"100 Test"});agreementId=created.agreement.id;await parity.attachCoverage(actor(),agreementId,{assetIds:[assetId],coverage:{included:["inspection"]}});const link=await maintenance.sendAgreement(actor(),agreementId,{signerName:"Synthetic Customer",signerEmail:"synthetic@example.test"});await maintenance.signPublic(link.token,{signerName:"Synthetic Customer",signatureMethod:"typed",consentTextVersion:"v1",autoRenewEnabled:false});const detail=await maintenance.getAgreement(actor(),agreementId);membershipId=detail.membership!.id;await expect(parity.attachCoverage(actor(),agreementId,{assetIds:[assetId]})).rejects.toBeInstanceOf(ConflictError);const artifact=await parity.retainSignedAgreement(actor(),agreementId);expect(artifact.sha256).toMatch(/^[0-9a-f]{64}$/);expect(storage.objects.get(artifact.objectKey)?.slice(0,5)).toEqual(new TextEncoder().encode("%PDF-"));expect((await parity.signedArtifactUrl(actor(),agreementId)).url).toContain("storage.example.test");await expect(parity.signedArtifactUrl(foreign(),agreementId)).rejects.toBeInstanceOf(NotFoundError)});
 it("generates a maintenance Job and enforces report relationship provenance",async()=>{await maintenance.createSchedule(actor(),membershipId,{recurrence:"annual",startDate:"2026-09-08"});expect((await automation.runManual(actor())).jobsGenerated).toBe(1);const detail=await maintenance.getAgreement(actor(),agreementId),occurrence=detail.occurrences.find(x=>x.status==="job_generated")!;occurrenceId=occurrence.id;jobId=occurrence.jobId!;await jobs.scheduleJob(actor(),jobId,{technicianUserId:tech.user.id,scheduledDate:"2026-09-08",scheduledTime:"10:00",durationMinutes:60,timezone:"America/Vancouver"});await jobs.transitionJob(actor(),jobId,{toStatus:"in_progress"});const report=await parity.createServiceReport(actor(),{jobId,membershipId,occurrenceId,assetId,checklistVersionId});reportId=report.id;await expect(parity.createServiceReport(foreign(),{jobId,membershipId,occurrenceId,assetId,checklistVersionId})).rejects.toBeInstanceOf(NotFoundError)});
it("requires same-Job evidence, required checklist answers and consumes once under concurrent completion",async()=>{const pre=await attachments.uploadAttachment(actor(),{filename:"pre.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"job",targetId:jobId},pdf),post=await attachments.uploadAttachment(actor(),{filename:"post.pdf",contentType:"application/pdf",sizeBytes:pdf.byteLength,targetType:"job",targetId:jobId},pdf);await expect(parity.submitServiceReport(actor(),reportId,{responses:{},preWorkAttachmentId:pre.id,postWorkAttachmentId:post.id,customerSignerName:"Synthetic Customer",customerSignature:"typed",expectedRowVersion:0})).rejects.toBeInstanceOf(ConflictError);const report=await parity.submitServiceReport(actor(),reportId,{responses:{safe:true},findings:"System operational",deficiencies:"",recommendations:"",preWorkAttachmentId:pre.id,postWorkAttachmentId:post.id,customerSignerName:"Synthetic Customer",customerSignature:"typed",expectedRowVersion:0});expect(report.status).toBe("submitted");const techActor={userId:tech.user.id,organizationId:a.organization.id,role:"member" as const};await expect(jobs.transitionJob(techActor,jobId,{toStatus:"completed"})).rejects.toThrow("Maintenance Jobs");const completions=await Promise.all([parity.completeMaintenanceVisit(techActor,reportId),parity.completeMaintenanceVisit(techActor,reportId)]);expect(completions.filter(result=>result.consumed)).toHaveLength(1);expect(completions.some(result=>result.idempotent)).toBe(true);expect((await maintenance.getAgreement(actor(),agreementId)).entitlement).toBe(0);expect((await parity.completeMaintenanceVisit(techActor,reportId)).idempotent).toBe(true)});
 it("applies active same-tenant commercial benefits and snapshots provenance",async()=>{const result=await parity.applyCommercialBenefit(actor(),{customerId:customer.id,serviceCode:"inspection",assetId,subtotalCents:10000,idempotencyKey:`benefit-${crypto.randomUUID()}`});expect(result).toMatchObject({eligible:true,discountCents:10000});await expect(parity.applyCommercialBenefit(foreign(),{customerId:customer.id,serviceCode:"inspection",assetId,subtotalCents:10000,idempotencyKey:`benefit-${crypto.randomUUID()}`})).resolves.toMatchObject({eligible:false})});
 it("applies benefits directly to authoritative Quote option totals",async()=>{const estimates=new EstimateService(),quote=await estimates.create(actor(),{customerId:customer.id,tiers:["good"]});await estimates.addLine(actor(),quote.id,{optionId:quote.options[0]!.id,description:"inspection",quantityMilli:1000,unitPriceCents:10000,taxable:true});const applied=await parity.applyQuoteBenefit(actor(),{quoteId:quote.id,quoteOptionId:quote.options[0]!.id,serviceCode:"inspection",assetId,idempotencyKey:`quote-benefit-${crypto.randomUUID()}`});expect(applied).toMatchObject({eligible:true,discountCents:10000,option:{totalCents:0}});await expect(parity.applyQuoteBenefit(foreign(),{quoteId:quote.id,quoteOptionId:quote.options[0]!.id,serviceCode:"inspection",assetId,idempotencyKey:`quote-benefit-${crypto.randomUUID()}`})).rejects.toBeInstanceOf(ConflictError)});
 it("creates durable idempotent outbox rows without claiming delivery",async()=>{const reminderAgreement=await maintenance.createAgreement(actor(),{customerId:customer.id,planId:plan.id,effectiveDate:"2026-01-01",expiresOn:"2026-11-07",renewalPreference:"manual",termsSnapshot:"Terms",serviceLocation:"100 Test"}),link=await maintenance.sendAgreement(actor(),reminderAgreement.agreement.id,{signerName:"Synthetic Customer",signerEmail:"synthetic@example.test"});await maintenance.signPublic(link.token,{signerName:"Synthetic Customer",signatureMethod:"typed",consentTextVersion:"v1",autoRenewEnabled:false});await automation.runManual(actor());const detail=await maintenance.getAgreement(actor(),reminderAgreement.agreement.id),reminder=detail.reminders[0]!;const before=await parity.listOutbox(actor(),{status:"pending"});await parity.enqueueReminder(actor(),reminder.id);const after=await parity.listOutbox(actor(),{status:"pending"});expect(after.length).toBe(before.length);expect(after.some(x=>x.reminderIntentId===reminder.id&&x.status==="pending")).toBe(true);await expect(parity.enqueueReminder(foreign(),reminder.id)).rejects.toBeInstanceOf(NotFoundError)});
 it("keeps administration office-only",async()=>{const techActor={userId:tech.user.id,organizationId:a.organization.id,role:"member" as const};await expect(parity.createLegalDocument(techActor,{title:"x",content:"x"})).rejects.toBeInstanceOf(ForbiddenError);await expect(parity.createAsset(techActor,{customerId:customer.id,type:"x",serviceLocation:"x"})).rejects.toBeInstanceOf(ForbiddenError)});
});
