import { describe, expect, it } from "vitest";
import { getDb } from "@/db";
import { jobs, maintenanceAgreements, maintenanceOccurrences, maintenanceReminderIntents } from "@/db/schema";
import { ApplicationError, ConflictError, ForbiddenError, NotFoundError } from "@/lib/errors";
import { AuditRepository } from "@/modules/audit/audit.repository";
import { CustomerService } from "@/modules/customers/customer.service";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { MaintenanceAutomationService } from "./maintenance.automation";
import { MaintenanceService, type MaintenanceClock } from "./maintenance.service";

describe.sequential("PostgreSQL Maintenance Agreements and automation", () => {
  const fixed = new Date("2026-01-15T18:00:00.000Z"), testClock: MaintenanceClock = { now: () => fixed, today: () => "2026-01-15" };
  const service = new MaintenanceService(testClock), automation = new MaintenanceAutomationService(testClock);
  let a: Awaited<ReturnType<OrganizationService["createOrganizationWithOwner"]>>, b: typeof a, customer: Awaited<ReturnType<CustomerService["createCustomer"]>>, plan: Awaited<ReturnType<MaintenanceService["createPlan"]>>;
  const actor = () => ({ userId: a.user.id, organizationId: a.organization.id, role: "owner" as const });
  const foreign = () => ({ userId: b.user.id, organizationId: b.organization.id, role: "owner" as const });
  const agreementInput = (extra: Record<string, unknown> = {}) => ({ customerId: customer.id, planId: plan.id, effectiveDate: "2026-01-01", expiresOn: "2026-12-31", renewalPreference: "auto", termsSnapshot: "Synthetic maintenance terms v1", serviceLocation: "100 Synthetic Service Road", ...extra });
  const activate = async (extra: Record<string, unknown> = {}, autoRenewEnabled = false) => { const created = await service.createAgreement(actor(), agreementInput(extra)), link = await service.sendAgreement(actor(), created.agreement.id, { signerName: "Synthetic Customer", signerEmail: "maintenance@example.test", expiresInDays: 14 }); await service.publicAgreement(link.token); const signed = await service.signPublic(link.token, { signerName: "Synthetic Customer", signatureMethod: "typed", consentTextVersion: "maintenance-consent-v1", autoRenewEnabled }, { ip: "192.0.2.10", userAgent: "integration-test" }); return { ...created, ...signed, token: link.token }; };

  it("creates isolated organizations, Customer and versionable plan fixtures", async () => { const organizations = new OrganizationService(); a = await organizations.createOrganizationWithOwner({ name: "Maintenance Tenant A", slug: `maintenance-a-${crypto.randomUUID()}` }, { name: "Owner A", email: `maintenance-a-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-123" }); b = await organizations.createOrganizationWithOwner({ name: "Maintenance Tenant B", slug: `maintenance-b-${crypto.randomUUID()}` }, { name: "Owner B", email: `maintenance-b-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-456" }); customer = await new CustomerService().createCustomer(actor(), { name: "Synthetic Maintenance Customer", email: "maintenance@example.test", addressLine1: "100 Synthetic Service Road" }); plan = await service.createPlan(actor(), { code: "SYNTH-GOLD", name: "Synthetic Gold", priceCents: 24900, currency: "CAD", visitEntitlementCount: 2, frequencyDescription: "Annual", priorityBenefit: "Priority booking", discountType: "percent", discountBasisPoints: 1000, includedServices: ["Inspection"] }); expect(plan.organizationId).toBe(a.organization.id); expect(await service.listPlans(actor(), { query: "GOLD", limit: 10 })).toHaveLength(1); });
  it("snapshots plan/customer/location terms and activates one idempotent Membership", async () => { const active = await activate({}, true), detail = await service.getAgreement(actor(), active.agreement.id); expect(detail.agreement.status).toBe("active"); expect(detail.membership).toMatchObject({ status: "active", customerId: customer.id, visitsIncluded: 2 }); expect(detail.entitlement).toBe(2); expect(detail.version?.documentHash).toMatch(/^[a-f0-9]{64}$/); expect(JSON.parse(detail.version!.planSnapshot)).toMatchObject({ code: "SYNTH-GOLD", priceCents: 24900 }); await expect(service.signPublic(active.token, { signerName: "Synthetic Customer", signatureMethod: "typed", consentTextVersion: "v1", autoRenewEnabled: true })).rejects.toBeInstanceOf(ConflictError); });
  it("rejects a malformed public signing token as an ApplicationError, not an uncaught crash", async () => { await expect(service.publicAgreement("not-a-well-formed-token")).rejects.toBeInstanceOf(ApplicationError); await expect(service.signPublic("not-a-well-formed-token", { signerName: "x", signatureMethod: "typed", consentTextVersion: "maintenance-consent-v1", autoRenewEnabled: false }, {})).rejects.toBeInstanceOf(ApplicationError); });
  it("rejects cross-tenant plan, Customer and agreement access without leaking", async () => { await expect(service.createAgreement(foreign(), agreementInput())).rejects.toBeInstanceOf(NotFoundError); const active = await activate(); await expect(service.getAgreement(foreign(), active.agreement.id)).rejects.toBeInstanceOf(NotFoundError); expect(await service.listAgreements(foreign(), { query: active.agreement.identifier, limit: 10 })).toHaveLength(0); await expect(service.createSchedule(foreign(), active.membershipId, { recurrence: "annual" })).rejects.toBeInstanceOf(NotFoundError); });
  it("keeps plan and agreement mutation office-only with persisted membership RBAC", async () => { const users = new UserService(), memberResult = await users.createUserWithMembership(actor(), { name: "Technician", email: `maintenance-tech-${crypto.randomUUID()}@example.test`, password: "Synthetic-Pass-789" }, "member"), member = { userId: memberResult.user.id, organizationId: a.organization.id, role: "member" as const }; await expect(service.listPlans(member, {})).rejects.toBeInstanceOf(ForbiddenError); await expect(service.createAgreement(member, agreementInput())).rejects.toBeInstanceOf(ForbiddenError); });
  it("generates one tenant-local unscheduled Job per occurrence and advances deterministically", async () => { const active = await activate({ effectiveDate: "2025-01-15", expiresOn: "2027-01-15" }), schedule = await service.createSchedule(actor(), active.membershipId, { recurrence: "annual", startDate: "2025-01-15" }); const first = await automation.runManual(actor()); expect(first).toMatchObject({ occurrencesProcessed: 1, jobsGenerated: 1 }); const detail = await service.getAgreement(actor(), active.agreement.id); expect(detail.schedule).toMatchObject({ id: schedule.id, nextDueDate: "2026-01-15", cyclesGenerated: 1 }); expect(detail.occurrences[0]).toMatchObject({ dueDate: "2025-01-15", status: "job_generated" }); const second = await automation.runManual(actor()); expect(second.jobsGenerated).toBe(1); const third = await automation.runManual(actor()); expect(third.jobsGenerated).toBe(0); const createdJobs = await getDb().select().from(jobs); expect(createdJobs.filter(job => job.organizationId === a.organization.id && job.description?.includes(active.agreement.identifier))).toHaveLength(2); });
  it("serializes concurrent runners without duplicating one due cycle", async () => { const active = await activate(), schedule = await service.createSchedule(actor(), active.membershipId, { recurrence: "quarterly", startDate: "2026-01-15" }); const results = await Promise.all([automation.runManual(actor()), automation.runManual(actor())]); expect(results.reduce((sum, item) => sum + item.jobsGenerated, 0)).toBe(1); const detail = await service.getAgreement(actor(), active.agreement.id); expect(detail.occurrences.filter(item => item.scheduleId === schedule.id)).toHaveLength(1); });
  it("creates exact 60/30/14 durable reminder intents without claiming delivery", async () => { const reminder = await activate({ expiresOn: "2026-03-16", renewalPreference: "manual" }); const first = await automation.runManual(actor()), second = await automation.runManual(actor()); expect(first.remindersCreated).toBeGreaterThanOrEqual(1); expect(second.remindersCreated).toBe(0); const detail = await service.getAgreement(actor(), reminder.agreement.id); expect(detail.reminders).toHaveLength(1); expect(detail.reminders[0]).toMatchObject({ milestoneDays: 60, status: "pending" }); });
  it("auto-renews only unchanged standing-consent snapshots and supersedes atomically", async () => { const old = await activate({ effectiveDate: "2025-01-25", expiresOn: "2026-01-25" }, true), result = await automation.runManual(actor()), oldDetail = await service.getAgreement(actor(), old.agreement.id); expect(result.renewalsProcessed).toBeGreaterThanOrEqual(1); expect(oldDetail.agreement.status).toBe("superseded"); expect(oldDetail.agreement.supersededByAgreementId).toBeTruthy(); const renewed = await service.getAgreement(actor(), oldDetail.agreement.supersededByAgreementId!); expect(renewed).toMatchObject({ agreement: { status: "active", supersedesAgreementId: old.agreement.id }, membership: { status: "active" } }); expect(renewed.version?.activationProvenance).toBe("standing_auto_renew_consent"); });
  it("falls back to fresh customer acceptance after material plan change", async () => { const old = await activate({ effectiveDate: "2025-01-26", expiresOn: "2026-01-26" }, true); await service.updatePlan(actor(), plan.id, { expectedRowVersion: plan.rowVersion, priceCents: 25900 }); plan = (await service.listPlans(actor(), { query: "SYNTH-GOLD", limit: 1 }))[0]!; await automation.runManual(actor()); const oldDetail = await service.getAgreement(actor(), old.agreement.id), pending = await service.getAgreement(actor(), oldDetail.agreement.supersededByAgreementId!); expect(oldDetail.agreement.status).toBe("active"); expect(pending.agreement.status).toBe("draft"); expect(JSON.parse(pending.version!.planSnapshot).priceCents).toBe(25900); });
  it("cancellation stops schedules/reminders and race-safe tenant history remains auditable", async () => { const active = await activate(), schedule = await service.createSchedule(actor(), active.membershipId, { recurrence: "annual", startDate: "2026-01-15" }); await service.cancelAgreement(actor(), active.agreement.id, { reason: "Synthetic cancellation" }); const detail = await service.getAgreement(actor(), active.agreement.id); expect(detail).toMatchObject({ agreement: { status: "cancelled" }, membership: { status: "cancelled" }, schedule: { id: schedule.id, status: "cancelled" } }); const run = await automation.runManual(actor()); expect(run.jobsGenerated).toBe(0); const events = await new AuditRepository().listForEntity(actor().organizationId, "maintenance_agreement", active.agreement.id); expect(events.map(event => event.action)).toContain("maintenance_agreement.cancelled"); expect(JSON.stringify(events)).not.toContain("integration-test"); });
  it("database constraints keep occurrence, reminder and renewal provenance tenant-local", async () => { const agreements = await getDb().select().from(maintenanceAgreements), occurrences = await getDb().select().from(maintenanceOccurrences), reminders = await getDb().select().from(maintenanceReminderIntents); expect(agreements.some(item => item.organizationId === a.organization.id)).toBe(true); expect(occurrences.filter(item => item.organizationId === b.organization.id)).toHaveLength(0); expect(reminders.filter(item => item.organizationId === b.organization.id)).toHaveLength(0); });
});
