import { describe, expect, it } from "vitest";
import { getDb } from "@/db";
import { payments } from "@/db/schema";
import { ConflictError, ForbiddenError, NotFoundError, ValidationError } from "@/lib/errors";
import { AuditRepository } from "@/modules/audit/audit.repository";
import { CustomerService } from "@/modules/customers/customer.service";
import { OrganizationService } from "@/modules/identity/organization.service";
import { UserService } from "@/modules/identity/user.service";
import { InvoiceService } from "@/modules/invoices";
import { PaymentService } from "./payment.service";

describe.sequential("PostgreSQL Payments",()=>{
  let a:Awaited<ReturnType<OrganizationService["createOrganizationWithOwner"]>>,b:typeof a,customer:Awaited<ReturnType<CustomerService["createCustomer"]>>;
  const service=new PaymentService(),invoices=new InvoiceService();
  const actor=()=>({userId:a.user.id,organizationId:a.organization.id,role:"owner" as const});const foreign=()=>({userId:b.user.id,organizationId:b.organization.id,role:"owner" as const});
  const issue=async(totalCents=10000)=>{const invoice=await invoices.create(actor(),{source:"manual",customerId:customer.id,lines:[{description:"Synthetic payment service",quantityMilli:1000,unitPriceCents:totalCents,taxable:false}]});await invoices.issue(actor(),invoice.id);return invoice};
  const posting=(amountCents:number,extra:Record<string,unknown>={})=>({amountCents,payerType:"customer",method:"cash",source:"manual",idempotencyKey:`payment-${crypto.randomUUID()}`,...extra});

  it("creates isolated payment fixtures",async()=>{const organizations=new OrganizationService();a=await organizations.createOrganizationWithOwner({name:"Payment Tenant A",slug:`payment-a-${crypto.randomUUID()}`},{name:"Owner A",email:`payment-a-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-123"});b=await organizations.createOrganizationWithOwner({name:"Payment Tenant B",slug:`payment-b-${crypto.randomUUID()}`},{name:"Owner B",email:`payment-b-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-456"});customer=await new CustomerService().createCustomer(actor(),{name:"Synthetic Payment Customer",email:"payer@example.test"})});
  it("posts partial then exact final payments and reconciles Invoice reads",async()=>{const invoice=await issue();const partial=await service.post(actor(),invoice.id,posting(4000,{payerType:"government",method:"e_transfer",externalReference:"SYNTHETIC-GOV-1",receivedBy:"Synthetic Clerk"}));expect(partial.financials).toMatchObject({amountPaidCents:4000,balanceCents:6000,invoiceStatus:"partially_paid"});expect((await invoices.get(actor(),invoice.id)).invoice).toMatchObject({status:"partially_paid",amountPaidCents:4000,balanceCents:6000});const final=await service.post(actor(),invoice.id,posting(6000));expect(final.financials).toMatchObject({amountPaidCents:10000,balanceCents:0,invoiceStatus:"paid"});expect((await invoices.get(actor(),invoice.id)).invoice.status).toBe("paid")});
  it("rejects invalid states, unsafe provider facts and overpayments without partial writes",async()=>{const draft=await invoices.create(actor(),{source:"manual",customerId:customer.id,lines:[{description:"Draft",quantityMilli:1000,unitPriceCents:1000,taxable:false}]});await expect(service.post(actor(),draft.id,posting(1))).rejects.toBeInstanceOf(ConflictError);const invoice=await issue(1000);await expect(service.post(actor(),invoice.id,posting(1001))).rejects.toBeInstanceOf(ConflictError);await expect(service.post(actor(),invoice.id,{...posting(100),source:"online_provider"})).rejects.toBeInstanceOf(ConflictError);await expect(service.post(actor(),invoice.id,{...posting(0)})).rejects.toBeInstanceOf(ValidationError);expect(await service.listForInvoice(actor(),invoice.id)).toHaveLength(0)});
  it("prevents concurrent aggregate overpayment with an Invoice row lock",async()=>{const invoice=await issue();const results=await Promise.allSettled([service.post(actor(),invoice.id,posting(6000)),service.post(actor(),invoice.id,posting(6000))]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(results.filter(x=>x.status==="rejected")).toHaveLength(1);expect((await invoices.get(actor(),invoice.id)).invoice).toMatchObject({amountPaidCents:6000,balanceCents:4000,status:"partially_paid"})});
  it("makes provider/manual retries idempotent without merging legitimate equal payments",async()=>{const invoice=await issue(),key=`retry-${crypto.randomUUID()}`,input=posting(2500,{idempotencyKey:key,externalReference:"SAFE-REFERENCE"});const first=await service.post(actor(),invoice.id,input),retry=await service.post(actor(),invoice.id,input);expect(retry.idempotent).toBe(true);expect(retry.payment.id).toBe(first.payment.id);await expect(service.post(actor(),invoice.id,{...input,amountCents:2501})).rejects.toBeInstanceOf(ConflictError);const other=await service.post(actor(),invoice.id,posting(2500));expect(other.payment.id).not.toBe(first.payment.id);expect((await invoices.get(actor(),invoice.id)).invoice.amountPaidCents).toBe(5000)});
  it("serializes concurrent duplicate idempotency claims",async()=>{const invoice=await issue(),input=posting(1000,{idempotencyKey:`concurrent-${crypto.randomUUID()}`});const [one,two]=await Promise.all([service.post(actor(),invoice.id,input),service.post(actor(),invoice.id,input)]);expect(one.payment.id).toBe(two.payment.id);expect((await service.listForInvoice(actor(),invoice.id).then(rows=>rows.filter(row=>row.entryType==="payment")))).toHaveLength(1)});
  it("appends one reversal, restores balance/status and rejects double reversal",async()=>{const invoice=await issue(),posted=await service.post(actor(),invoice.id,posting(10000));const reversed=await service.reverse(actor(),posted.payment.id,{reason:"Synthetic correction"});expect(reversed.reversal.reversesPaymentId).toBe(posted.payment.id);expect(reversed.financials).toMatchObject({amountPaidCents:0,balanceCents:10000,invoiceStatus:"issued"});expect((await service.get(actor(),posted.payment.id)).reversal?.reversalReason).toBe("Synthetic correction");await expect(service.reverse(actor(),posted.payment.id,{reason:"Again"})).rejects.toBeInstanceOf(ConflictError);expect(await service.listForInvoice(actor(),invoice.id)).toHaveLength(2)});
  it("protects final-payment and reversal races",async()=>{const invoice=await issue(),first=await service.post(actor(),invoice.id,posting(9000));const finals=await Promise.allSettled([service.post(actor(),invoice.id,posting(1000)),service.post(actor(),invoice.id,posting(1000))]);expect(finals.filter(x=>x.status==="fulfilled")).toHaveLength(1);const reversals=await Promise.allSettled([service.reverse(actor(),first.payment.id,{reason:"Race A"}),service.reverse(actor(),first.payment.id,{reason:"Race B"})]);expect(reversals.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect((await invoices.get(actor(),invoice.id)).invoice).toMatchObject({amountPaidCents:1000,balanceCents:9000,status:"partially_paid"})});
  it("serializes payment against Invoice void without corrupting the ledger",async()=>{const invoice=await issue(1000),results=await Promise.allSettled([service.post(actor(),invoice.id,posting(500)),invoices.void(actor(),invoice.id,{reason:"Concurrent void"})]),detail=await invoices.get(actor(),invoice.id);expect(results.some(x=>x.status==="fulfilled")).toBe(true);expect(detail.invoice.status).toBe("void");expect([0,500]).toContain(detail.invoice.amountPaidCents);expect(detail.invoice.balanceCents).toBe(1000-detail.invoice.amountPaidCents)});
  it("enforces tenant isolation across metadata, posting, reversal, receipt and lists",async()=>{const invoice=await issue(),posted=await service.post(actor(),invoice.id,posting(100));await expect(service.post(foreign(),invoice.id,posting(1))).rejects.toBeInstanceOf(NotFoundError);await expect(service.get(foreign(),posted.payment.id)).rejects.toBeInstanceOf(NotFoundError);await expect(service.reverse(foreign(),posted.payment.id,{reason:"Foreign"})).rejects.toBeInstanceOf(NotFoundError);await expect(service.receiptModel(foreign(),posted.payment.id)).rejects.toBeInstanceOf(NotFoundError);expect(await service.list(foreign(),{search:invoice.identifier,limit:20})).toHaveLength(0);expect(await service.list(actor(),{invoiceId:invoice.id,limit:20})).toHaveLength(1)});
  it("keeps financial RBAC office-only and creates minimal safe audit",async()=>{const users=new UserService(),managerResult=await users.createUserWithMembership(actor(),{name:"Manager",email:`payment-manager-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-789"},"manager"),viewerResult=await users.createUserWithMembership(actor(),{name:"Viewer",email:`payment-viewer-${crypto.randomUUID()}@example.test`,password:"Synthetic-Pass-012"},"viewer"),manager={userId:managerResult.user.id,organizationId:a.organization.id,role:"manager" as const},viewer={userId:viewerResult.user.id,organizationId:a.organization.id,role:"viewer" as const},invoice=await issue(),posted=await service.post(manager,invoice.id,posting(100,{notes:"Do not put this in audit"}));await expect(service.get(viewer,posted.payment.id)).rejects.toBeInstanceOf(ForbiddenError);const events=await new AuditRepository().listForEntity(actor().organizationId,"payment",posted.payment.id);expect(events.map(event=>event.action)).toContain("payment.posted");expect(JSON.stringify(events)).not.toContain("Do not put this in audit")});
  it("authorizes live receipts from immutable payment facts and current aggregate balance",async()=>{const invoice=await issue(5000),posted=await service.post(actor(),invoice.id,posting(2000,{method:"check",externalReference:"RECEIPT-SYNTHETIC"})),model=await service.receiptModel(actor(),posted.payment.id);expect(model).toMatchObject({invoiceIdentifier:invoice.identifier,customerName:"Synthetic Payment Customer",amountCents:2000,amountPaidCents:2000,balanceCents:3000,reversed:false});await service.reverse(actor(),posted.payment.id,{reason:"Receipt reversal"});expect(await service.receiptModel(actor(),posted.payment.id)).toMatchObject({reversed:true,amountPaidCents:0,balanceCents:5000})});
  it("persists only append-oriented entries",async()=>{const rows=await getDb().select().from(payments);expect(rows.some(row=>row.entryType==="payment")).toBe(true);expect(rows.some(row=>row.entryType==="reversal"&&!!row.reversesPaymentId)).toBe(true);expect(rows.every(row=>row.amountCents>0)).toBe(true)});
});
