import { notFound, redirect } from "next/navigation";
import { can } from "@/auth/permissions";
import { currentActor } from "@/auth/current-actor";
import { NotFoundError } from "@/lib/errors";
import { DealService } from "@/modules/deals/deal.service";
import { PipelineService } from "@/modules/pipelines/pipeline.service";
import { AttachmentPanel } from "./attachment-panel";
import { DealControls } from "./deal-controls";
import { InteractionPanel } from "./interaction-panel";
export default async function DealPage({ params }: { params: Promise<{ id: string }> }) { const actor = await currentActor(); if (!actor) redirect("/login"); const { id } = await params; const dealService = new DealService(); let result; try { result = await dealService.getDeal(actor, id); } catch (error) { if (error instanceof NotFoundError) notFound(); throw error; } const pipeline = await new PipelineService().getPipeline(actor, result.deal.pipelineId); const stage = pipeline.stages.find((value) => value.id === result.deal.stageId); const owners = (await dealService.listAssignableOwners(actor)).map(({ userId, name }) => ({ userId, name })); return <main className="mx-auto max-w-4xl px-6 py-12"><p className="text-sm font-medium text-primary">{result.deal.identifier}</p><div className="mt-2 flex items-start justify-between gap-4"><h1 className="text-4xl font-semibold tracking-tight">{result.deal.name}</h1><span className="rounded-full border px-3 py-1 text-sm">{stage?.name ?? "Unavailable stage"}</span></div><dl className="mt-8 grid gap-4 rounded-xl border bg-card p-6 sm:grid-cols-3"><div><dt className="text-sm text-muted-foreground">Value</dt><dd>{result.deal.amountCents} {result.deal.currency}</dd></div><div><dt className="text-sm text-muted-foreground">Expected close</dt><dd>{result.deal.expectedCloseDate || "—"}</dd></div><div><dt className="text-sm text-muted-foreground">Closed</dt><dd>{result.deal.closedAt?.toISOString() || "Open"}</dd></div></dl>{can(actor, "deal.update") && can(actor, "deal.move") ? <DealControls deal={result.deal} stages={pipeline.stages.map(({ id, name, kind }) => ({ id, name, kind }))} owners={owners} /> : null}<section className="mt-10"><h2 className="text-xl font-semibold">Stage history</h2><ol className="mt-3 space-y-2">{result.history.map((entry) => <li key={entry.id} className="rounded-lg border px-4 py-3 text-sm"><span className="font-medium">{entry.previousStageId ? "Stage changed" : "Deal created"}</span><span className="ml-2 text-muted-foreground">{entry.createdAt.toISOString()}</span></li>)}</ol></section><InteractionPanel actor={actor} dealId={id}/><AttachmentPanel actor={actor} dealId={id}/></main>; }
