import { z } from "zod";
const text = (max: number) => z.string().trim().max(max);
export const consentSource = z.enum(["phone", "in_person", "website", "written_form", "other"]);
export const preferenceSchema = z.strictObject({ marketingEmailOptIn: z.boolean(), marketingSmsOptIn: z.boolean(), consentSource: consentSource.optional(), doNotContact: z.boolean().default(false) }).superRefine((v, c) => { if ((v.marketingEmailOptIn || v.marketingSmsOptIn) && !v.consentSource) c.addIssue({ code: "custom", path: ["consentSource"], message: "Consent source is required when opting in" }); });
export const programSchema = z.strictObject({ enabled: z.boolean(), rewardType: z.enum(["account_credit", "fixed_reward", "service_credit", "future_discount", "non_cash"]), rewardValueCents: z.int().min(1).max(100_000_000).nullable(), rewardDescription: text(500), qualificationRule: z.enum(["first_completed_job", "first_paid_invoice"]) });
export const referralClaimSchema = z.strictObject({ name: z.string().trim().min(1).max(200), email: z.email().max(320).optional(), phone: text(40).optional() }).refine(v => v.email || v.phone, { message: "Email or phone is required" });
export const loyaltyGrantSchema = z.strictObject({ amountCents: z.int().min(1).max(100_000_000), reason: z.string().trim().min(2).max(500) });
export const creditActionSchema = z.strictObject({ reason: z.string().trim().min(2).max(500) });
export const audienceFilterSchema = z.strictObject({ city: text(100).optional(), membership: z.enum(["active", "inactive", "any"]).optional(), minDaysSinceLastJob: z.int().min(0).max(36500).optional(), maxDaysSinceLastJob: z.int().min(0).max(36500).optional() }).refine(v => v.minDaysSinceLastJob === undefined || v.maxDaysSinceLastJob === undefined || v.minDaysSinceLastJob <= v.maxDaysSinceLastJob, { message: "Minimum inactivity cannot exceed maximum" });
export const createCampaignSchema = z.strictObject({ name: z.string().trim().min(1).max(200), campaignType: z.enum(["seasonal", "referral_promo", "general"]).default("seasonal"), channel: z.enum(["email", "sms", "both"]), subject: text(300).default(""), body: text(10_000), ctaLink: z.union([z.url().max(2_000), z.literal("")]).default(""), audienceFilter: audienceFilterSchema.default({}) });
export const updateCampaignSchema = createCampaignSchema.partial();
export const scheduleCampaignSchema = z.strictObject({ scheduledFor: z.coerce.date() });
export const cancelCampaignSchema = z.strictObject({ reason: z.string().trim().min(2).max(500) });
export const pageSchema = z.strictObject({ page: z.int().min(1).default(1), pageSize: z.int().min(1).max(100).default(25), status: z.string().max(40).optional() });
const httpUrl=z.url().max(2_000).refine(value=>/^https?:\/\//i.test(value),{message:"URL must use HTTP or HTTPS"});
const optionalPublicUrl=z.union([httpUrl,z.literal("")]).transform(value=>value||null);
export const retentionSettingsSchema=z.strictObject({followUpDelayDays:z.int().min(0).max(365),publicBaseUrl:optionalPublicUrl,reviewUrl:optionalPublicUrl});
export const publicCapabilitySchema=z.string().min(32).max(200).regex(/^[A-Za-z0-9_-]+$/);
export const followUpResponseSchema=z.strictObject({response:z.enum(["satisfied","needs_attention"]),notes:z.string().trim().max(2_000).default("")});
