import "server-only";
import { randomBytes } from "node:crypto";
import { authorize } from "@/auth/authorization";
import { getDb } from "@/db";
import { ConflictError, NotFoundError } from "@/lib/errors";
import { parseInput } from "@/lib/validation";
import { AuditRepository } from "@/modules/audit/audit.repository";
import type { RequestActor } from "@/modules/customers/customer.service";
import { assertCampaignTransition, assertNotSelfReferral, channels, createRetentionCapability, creditBalance, hashRetentionCapability, retentionState, vancouverDate } from "./retention.rules";
import { cancelCampaignSchema, createCampaignSchema, creditActionSchema, followUpResponseSchema, loyaltyGrantSchema, pageSchema, preferenceSchema, programSchema, publicCapabilitySchema, referralClaimSchema, retentionSettingsSchema, scheduleCampaignSchema, updateCampaignSchema } from "./retention.schema";
import { RetentionRepository } from "./retention.repository";

function safeCode(){return randomBytes(18).toString("base64url");}
export class RetentionService {
  async getSettings(actor:RequestActor){await authorize(actor,"retention.read");const r=new RetentionRepository();return await r.settings(actor.organizationId)??{followUpDelayDays:7,publicBaseUrl:null,reviewUrl:null};}
  async saveSettings(actor:RequestActor,raw:unknown){await authorize(actor,"retention.manage");const input=parseInput(retentionSettingsSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx);await r.ensureSettings(actor.organizationId);await r.settings(actor.organizationId,true);const row=await r.saveSettings(actor.organizationId,{...input,updatedBy:actor.userId});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"retention.settings_updated",entityType:"retention_settings",entityId:row.id,metadata:{followUpDelayDays:row.followUpDelayDays,publicBaseUrlConfigured:Boolean(row.publicBaseUrl),reviewUrlConfigured:Boolean(row.reviewUrl)}});return row;});}
  async signals(actor:RequestActor,customerId:string){await authorize(actor,"retention.read");const r=new RetentionRepository();if(!await r.customer(actor.organizationId,customerId))throw new NotFoundError("Customer not found");const rows=await r.signalRows(actor.organizationId,customerId);if(!rows)throw new NotFoundError("Customer not found");return retentionState(rows.lastCompletedAt,Number(rows.completedCount),rows.activeMembership);}
  async getPreferences(actor:RequestActor,customerId:string){await authorize(actor,"retention.read");const r=new RetentionRepository();if(!await r.customer(actor.organizationId,customerId))throw new NotFoundError("Customer not found");return await r.preference(actor.organizationId,customerId)??{marketingEmailOptIn:false,marketingSmsOptIn:false,doNotContact:false};}
  async savePreferences(actor:RequestActor,customerId:string,raw:unknown){await authorize(actor,"retention.manage");const input=parseInput(preferenceSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),audit=new AuditRepository(tx),customer=await r.customer(actor.organizationId,customerId,true);if(!customer)throw new NotFoundError("Customer not found");const existing=await r.preference(actor.organizationId,customerId,true),now=new Date();const emailNew=input.marketingEmailOptIn&&!existing?.marketingEmailOptIn,smsNew=input.marketingSmsOptIn&&!existing?.marketingSmsOptIn;const row=await r.savePreference(actor.organizationId,customerId,{marketingEmailOptIn:input.marketingEmailOptIn,marketingSmsOptIn:input.marketingSmsOptIn,marketingEmailConsentAt:emailNew?now:existing?.marketingEmailConsentAt??null,marketingEmailConsentSource:emailNew?input.consentSource:existing?.marketingEmailConsentSource??null,marketingSmsConsentAt:smsNew?now:existing?.marketingSmsConsentAt??null,marketingSmsConsentSource:smsNew?input.consentSource:existing?.marketingSmsConsentSource??null,doNotContact:input.doNotContact,unsubscribedAt:input.marketingEmailOptIn||input.marketingSmsOptIn?null:existing?.unsubscribedAt??null,updatedBy:actor.userId});await audit.record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"retention.preferences_updated",entityType:"customer",entityId:customerId,metadata:{marketingEmailOptIn:row.marketingEmailOptIn,marketingSmsOptIn:row.marketingSmsOptIn,doNotContact:row.doNotContact}});return row;});}
  async unsubscribe(organizationId:string,customerId:string){return getDb().transaction(async tx=>this.unsubscribeLocked(new RetentionRepository(tx),new AuditRepository(tx),organizationId,customerId));}
  async publicFollowUpView(rawToken:unknown){const token=parseInput(publicCapabilitySchema,rawToken),r=new RetentionRepository(),capability=await r.capabilityByHash(hashRetentionCapability(token)),now=new Date();if(!capability||capability.purpose!=="follow_up_response"||(capability.expiresAt&&capability.expiresAt<=now))throw new NotFoundError("Follow-up link is unavailable");const value=await r.publicFollowUp(capability.organizationId,capability.resourceId);if(!value||value.followUp.customerId!==capability.customerId||value.followUp.dueDate>vancouverDate(now))throw new NotFoundError("Follow-up link is unavailable");return{status:value.followUp.status,jobIdentifier:value.jobIdentifier,customerName:value.customerName};}
  async respondPublic(rawToken:unknown,raw:unknown){const token=parseInput(publicCapabilitySchema,rawToken),input=parseInput(followUpResponseSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),audit=new AuditRepository(tx),capability=await r.capabilityByHash(hashRetentionCapability(token),true),now=new Date();if(!capability||capability.purpose!=="follow_up_response"||(capability.expiresAt&&capability.expiresAt<=now))throw new NotFoundError("Follow-up link is unavailable");const follow=await r.followUp(capability.organizationId,capability.resourceId,true);if(!follow||follow.customerId!==capability.customerId||follow.dueDate>vancouverDate(now))throw new NotFoundError("Follow-up link is unavailable");if(follow.response)return{status:follow.status,reviewUrl:follow.reviewUrlSnapshot,planOffer:(follow.maintenanceOfferSnapshot as MaintenanceOffer[]|null)??null};const satisfied=input.response==="satisfied";await r.ensureSettings(capability.organizationId);const settings=await r.settings(capability.organizationId,true);let reviewUrl:string|null=null,planOffer:MaintenanceOffer[]|null=null;if(satisfied){reviewUrl=settings?.reviewUrl??null;const membership=await r.activeMaintenanceMembership(capability.organizationId,follow.customerId,vancouverDate(now),true);if(!membership){const plans=await r.activeMaintenancePlans(capability.organizationId,vancouverDate(now));if(plans.length)planOffer=plans;}}const updated=await r.updateFollowUp(capability.organizationId,follow.id,{status:satisfied?"satisfied":"needs_attention",response:input.response,responseNotes:input.notes,respondedAt:now,reviewEligible:Boolean(reviewUrl),reviewUrlSnapshot:reviewUrl,maintenanceOfferShown:Boolean(planOffer?.length),maintenanceOfferSnapshot:planOffer});await r.consumeCapability(capability.id,now);await audit.record({organizationId:capability.organizationId,actorUserId:null,action:"retention.follow_up_responded",entityType:"retention_follow_up",entityId:follow.id,metadata:{response:input.response,reviewEligible:Boolean(reviewUrl),maintenanceOfferShown:Boolean(planOffer?.length)}});if(!satisfied)await audit.record({organizationId:capability.organizationId,actorUserId:null,action:"retention.follow_up_escalated",entityType:"retention_follow_up",entityId:follow.id,metadata:{requiresStaffFollowUp:true}});return{status:updated!.status,reviewUrl,planOffer};});}
  async markReviewClicked(rawToken:unknown){const token=parseInput(publicCapabilitySchema,rawToken);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),capability=await r.capabilityByHash(hashRetentionCapability(token),true);if(!capability||capability.purpose!=="follow_up_response"||(capability.expiresAt&&capability.expiresAt<=new Date()))throw new NotFoundError("Follow-up link is unavailable");const follow=await r.followUp(capability.organizationId,capability.resourceId,true);if(!follow||follow.customerId!==capability.customerId||!follow.reviewEligible||!follow.reviewUrlSnapshot)throw new NotFoundError("Follow-up link is unavailable");if(!follow.reviewClickedAt){await r.updateFollowUp(capability.organizationId,follow.id,{reviewClickedAt:new Date()});await new AuditRepository(tx).record({organizationId:capability.organizationId,actorUserId:null,action:"retention.review_link_clicked",entityType:"retention_follow_up",entityId:follow.id,metadata:{}});}return{reviewUrl:follow.reviewUrlSnapshot};});}
  async publicUnsubscribeView(rawToken:unknown){const token=parseInput(publicCapabilitySchema,rawToken),capability=await new RetentionRepository().capabilityByHash(hashRetentionCapability(token));if(!capability||capability.purpose!=="marketing_unsubscribe")throw new NotFoundError("Unsubscribe link is unavailable");return{valid:true};}
  async unsubscribePublic(rawToken:unknown){const token=parseInput(publicCapabilitySchema,rawToken);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),audit=new AuditRepository(tx),capability=await r.capabilityByHash(hashRetentionCapability(token),true);if(!capability||capability.purpose!=="marketing_unsubscribe")throw new NotFoundError("Unsubscribe link is unavailable");await this.unsubscribeLocked(r,audit,capability.organizationId,capability.customerId);await r.consumeCapability(capability.id,new Date());return{ok:true};});}
  private async unsubscribeLocked(r:RetentionRepository,audit:AuditRepository,organizationId:string,customerId:string){const customer=await r.customer(organizationId,customerId,true);if(!customer)throw new NotFoundError("Customer not found");const existing=await r.preference(organizationId,customerId,true),alreadyUnsubscribed=Boolean(existing?.unsubscribedAt),now=new Date(),row=await r.savePreference(organizationId,customerId,{marketingEmailOptIn:false,marketingSmsOptIn:false,marketingEmailConsentAt:existing?.marketingEmailConsentAt??null,marketingEmailConsentSource:existing?.marketingEmailConsentSource??null,marketingSmsConsentAt:existing?.marketingSmsConsentAt??null,marketingSmsConsentSource:existing?.marketingSmsConsentSource??null,doNotContact:existing?.doNotContact??false,unsubscribedAt:existing?.unsubscribedAt??now}),cancelled=await r.cancelPendingMarketing(organizationId,customerId);if(!alreadyUnsubscribed)await audit.record({organizationId,actorUserId:null,action:"retention.marketing_unsubscribed",entityType:"customer",entityId:customerId,metadata:{cancelledPendingIntents:cancelled}});return row;}
  async getProgram(actor:RequestActor){await authorize(actor,"referral.read");return await new RetentionRepository().program(actor.organizationId)??{enabled:false,rewardType:"account_credit",rewardValueCents:null,rewardDescription:"",qualificationRule:"first_completed_job"};}
  async saveProgram(actor:RequestActor,raw:unknown){await authorize(actor,"referral.manage");const input=parseInput(programSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),row=await r.saveProgram(actor.organizationId,{...input,updatedBy:actor.userId});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"referral.program_updated",entityType:"referral_program",entityId:row.id,metadata:{enabled:row.enabled,rewardType:row.rewardType,qualificationRule:row.qualificationRule}});return row;});}
  async mintReferral(actor:RequestActor,referrerCustomerId:string){await authorize(actor,"referral.manage");return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),program=await r.program(actor.organizationId,true);if(!program?.enabled)throw new ConflictError("Referral program is disabled");if(!await r.customer(actor.organizationId,referrerCustomerId,true))throw new NotFoundError("Customer not found");const row=await r.createReferral({organizationId:actor.organizationId,referrerCustomerId,referralCode:safeCode(),createdBy:actor.userId});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"referral.created",entityType:"referral",entityId:row.id,metadata:{referrerCustomerId}});return row;});}
  async claimReferral(code:string,raw:unknown){const input=parseInput(referralClaimSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),referral=await r.referralByCode(code,true);if(!referral||referral.referredLeadId||referral.referredCustomerId||referral.status!=="pending")throw new NotFoundError("Referral link is unavailable");const program=await r.program(referral.organizationId,true);if(!program?.enabled)throw new NotFoundError("Referral link is unavailable");const referrer=await r.customer(referral.organizationId,referral.referrerCustomerId,true);if(!referrer)throw new NotFoundError("Referral link is unavailable");assertNotSelfReferral(referrer,input);const lead=await r.createLeadForReferral(referral.organizationId,input.name,input.email??null,input.phone??null,referral.id);const claimed=await r.claimReferral(referral.organizationId,referral.id,lead.id);if(!claimed)throw new ConflictError("Referral link was already used");await new AuditRepository(tx).record({organizationId:referral.organizationId,actorUserId:null,action:"referral.claimed",entityType:"referral",entityId:referral.id,metadata:{leadId:lead.id}});return{leadId:lead.id};});}
  async listReferrals(actor:RequestActor,raw:unknown){await authorize(actor,"referral.read");const p=parseInput(pageSchema,raw);return new RetentionRepository().listReferrals(actor.organizationId,{limit:p.pageSize,offset:(p.page-1)*p.pageSize});}
  async listCredits(actor:RequestActor,customerId:string){await authorize(actor,"loyalty.read");const r=new RetentionRepository();if(!await r.customer(actor.organizationId,customerId))throw new NotFoundError("Customer not found");const items=await r.credits(actor.organizationId,customerId);return{items,availableBalanceCents:creditBalance(items)};}
  async issueCredit(actor:RequestActor,customerId:string,raw:unknown){await authorize(actor,"loyalty.manage");const i=parseInput(loyaltyGrantSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx);if(!await r.customer(actor.organizationId,customerId,true))throw new NotFoundError("Customer not found");const row=await r.addCredit({organizationId:actor.organizationId,customerId,sourceType:"loyalty_grant",amountCents:i.amountCents,reason:i.reason,actorUserId:actor.userId});if(!row)throw new ConflictError("Credit already exists");await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"loyalty.earned",entityType:"loyalty_credit",entityId:row.id,metadata:{amountCents:i.amountCents,sourceType:row.sourceType}});return row;});}
  async changeCredit(actor:RequestActor,id:string,action:"redeem"|"void",raw:unknown){await authorize(actor,"loyalty.manage");const i=parseInput(creditActionSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),row=await r.lockCredit(actor.organizationId,id);if(!row)throw new NotFoundError("Credit not found");if(row.status!=="issued")throw new ConflictError("Credit is no longer available");const updated=await r.updateCredit(actor.organizationId,id,action==="redeem"?{status:"redeemed",redeemedAt:new Date(),redeemedReason:i.reason}:{status:"voided",voidedAt:new Date(),voidReason:i.reason});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:`loyalty.${action === "redeem" ? "redeemed" : "voided"}`,entityType:"loyalty_credit",entityId:id,metadata:{reason:i.reason}});return updated!;});}
}

type MaintenanceOffer={id:string;name:string;description:string;tier:string;priceCents:number;currency:string};

export class CampaignService {
  async list(actor:RequestActor,raw:unknown){await authorize(actor,"campaign.read");const p=parseInput(pageSchema,raw);return new RetentionRepository().listCampaigns(actor.organizationId,{limit:p.pageSize,offset:(p.page-1)*p.pageSize,status:p.status});}
  async get(actor:RequestActor,id:string){await authorize(actor,"campaign.read");const row=await new RetentionRepository().campaign(actor.organizationId,id);if(!row)throw new NotFoundError("Campaign not found");return row;}
  async create(actor:RequestActor,raw:unknown){await authorize(actor,"campaign.manage");const i=parseInput(createCampaignSchema,raw);return getDb().transaction(async tx=>{const row=await new RetentionRepository(tx).createCampaign({organizationId:actor.organizationId,...i,createdBy:actor.userId});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:"campaign.created",entityType:"campaign",entityId:row.id,metadata:{channel:row.channel,campaignType:row.campaignType}});return row;});}
  async update(actor:RequestActor,id:string,raw:unknown){await authorize(actor,"campaign.manage");const i=parseInput(updateCampaignSchema,raw);return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),current=await r.campaign(actor.organizationId,id,true);if(!current)throw new NotFoundError("Campaign not found");if(current.status!=="draft")throw new ConflictError("Campaign content is frozen after scheduling");return (await r.updateCampaign(actor.organizationId,id,i))!;});}
  async schedule(actor:RequestActor,id:string,raw:unknown){await authorize(actor,"campaign.manage");const i=parseInput(scheduleCampaignSchema,raw);return this.transition(actor,id,"scheduled",{scheduledFor:i.scheduledFor});}
  async pause(actor:RequestActor,id:string){await authorize(actor,"campaign.manage");return this.transition(actor,id,"paused",{});}
  async resume(actor:RequestActor,id:string){await authorize(actor,"campaign.manage");return this.transition(actor,id,"scheduled",{});}
  async cancel(actor:RequestActor,id:string,raw:unknown){await authorize(actor,"campaign.manage");const i=parseInput(cancelCampaignSchema,raw);return this.transition(actor,id,"cancelled",{cancelledAt:new Date(),cancelReason:i.reason});}
  async preview(actor:RequestActor,id:string){await authorize(actor,"campaign.read");const r=new RetentionRepository(),campaign=await r.campaign(actor.organizationId,id);if(!campaign)throw new NotFoundError("Campaign not found");return this.evaluateAudience(r,actor.organizationId,campaign.audienceFilter,campaign.channel);}
  async recipients(actor:RequestActor,id:string){await authorize(actor,"campaign.read");if(!await new RetentionRepository().campaign(actor.organizationId,id))throw new NotFoundError("Campaign not found");return new RetentionRepository().listRecipients(actor.organizationId,id);}
  async execute(actor:RequestActor,id:string){await authorize(actor,"campaign.execute");return getDb().transaction(tx=>this.executeLocked(new RetentionRepository(tx),new AuditRepository(tx),actor.organizationId,id,actor.userId,new Date()));}
  async executeTrusted(organizationId:string,id:string,now=new Date()){return getDb().transaction(tx=>this.executeLocked(new RetentionRepository(tx),new AuditRepository(tx),organizationId,id,null,now));}
  private async transition(actor:RequestActor,id:string,to:"scheduled"|"paused"|"cancelled",fields:Record<string,unknown>){return getDb().transaction(async tx=>{const r=new RetentionRepository(tx),current=await r.campaign(actor.organizationId,id,true);if(!current)throw new NotFoundError("Campaign not found");assertCampaignTransition(current.status,to);const row=await r.updateCampaign(actor.organizationId,id,{status:to,...fields});await new AuditRepository(tx).record({organizationId:actor.organizationId,actorUserId:actor.userId,action:`campaign.${to}`,entityType:"campaign",entityId:id,metadata:{from:current.status}});return row!;});}
  private async evaluateAudience(r:RetentionRepository,org:string,filter:Parameters<RetentionRepository["audience"]>[1],channel:"email"|"sms"|"both"){const candidates=await r.audience(org,filter);const results=[];for(const customer of candidates){const pref=await r.preference(org,customer.id);for(const selectedChannel of channels(channel)){const address=selectedChannel==="email"?customer.email:customer.phone;const optedIn=selectedChannel==="email"?pref?.marketingEmailOptIn:pref?.marketingSmsOptIn;const reason=!address?"missing_recipient":pref?.doNotContact?"do_not_contact":pref?.unsubscribedAt?"unsubscribed":!optedIn?"marketing_not_opted_in":null;results.push({customer,channel:selectedChannel,eligible:!reason,reason});}}return{totalCandidates:candidates.length,eligible:results.filter(x=>x.eligible).length,suppressed:results.filter(x=>!x.eligible).length,results};}
  private async executeLocked(r:RetentionRepository,audit:AuditRepository,org:string,id:string,actorUserId:string|null,now:Date){const campaign=await r.campaign(org,id,true);if(!campaign)throw new NotFoundError("Campaign not found");if(campaign.status==="completed")return{finalized:0,pending:0,suppressed:0,idempotent:true};if(campaign.status!=="scheduled"||!campaign.scheduledFor||campaign.scheduledFor>now)throw new ConflictError("Campaign is not due");assertCampaignTransition(campaign.status,"running");await r.updateCampaign(org,id,{status:"running",startedAt:now});await r.ensureSettings(org);const settings=await r.settings(org,true);const audience=await this.evaluateAudience(r,org,campaign.audienceFilter,campaign.channel);let pending=0,suppressed=0;for(const item of audience.results){await r.customer(org,item.customer.id,true);const currentPref=await r.preference(org,item.customer.id,true);const address=item.channel==="email"?item.customer.email:item.customer.phone;const optedIn=item.channel==="email"?currentPref?.marketingEmailOptIn:currentPref?.marketingSmsOptIn;const reason=!address?"missing_recipient":currentPref?.doNotContact?"do_not_contact":currentPref?.unsubscribedAt?"unsubscribed":!optedIn?"marketing_not_opted_in":null;const recipient=await r.addRecipient({organizationId:org,campaignId:id,customerId:item.customer.id,channel:item.channel,status:reason?"suppressed":"queued",suppressionReason:reason,recipientSnapshot:{customerId:item.customer.id,name:item.customer.name,address,channel:item.channel}});if(!recipient)continue;if(reason){suppressed++;continue;}const token=createRetentionCapability();await r.addCapability({organizationId:org,customerId:item.customer.id,purpose:"marketing_unsubscribe",resourceId:recipient.id,tokenHash:hashRetentionCapability(token)});const path=`/unsubscribe/${token}`,unsubscribeUrl=settings?.publicBaseUrl?`${settings.publicBaseUrl.replace(/\/+$/g,"")}${path}`:path;const outbox=await r.addOutbox({organizationId:org,customerId:item.customer.id,channel:item.channel,eventType:"campaign",entityType:"campaign",entityId:id,dedupeKey:`campaign:${id}:${item.customer.id}:${item.channel}`,recipientSnapshot:recipient.recipientSnapshot,payload:{subject:campaign.subject,body:campaign.body,ctaLink:campaign.ctaLink,unsubscribeUrl}});if(outbox){await r.attachOutbox(org,recipient.id,outbox.id);pending++;}}
    await r.updateCampaign(org,id,{status:"completed",completedAt:now});await audit.record({organizationId:org,actorUserId,action:"campaign.audience_finalized",entityType:"campaign",entityId:id,metadata:{pending,suppressed,providerDelivery:"deferred"}});return{finalized:pending+suppressed,pending,suppressed,idempotent:false};}
}
