import "server-only";
import { and, asc, count, desc, eq, gte, ilike, inArray, isNull, lte, or, sql } from "drizzle-orm";
import { getDb, type DatabaseExecutor } from "@/db";
import { campaignRecipients, campaigns, customerCreditLedger, customerReferrals, customers, invoices, jobs, leads, maintenanceMemberships, maintenancePlans, notificationOutbox, referralPrograms, retentionAutomationRuns, retentionFollowUps, retentionPreferences, retentionPublicCapabilities, retentionSettings, type RetentionAudienceFilter } from "@/db/schema";

export class RetentionRepository {
  constructor(private readonly db: DatabaseExecutor = getDb()) {}
  async ensureSettings(org:string){await this.db.insert(retentionSettings).values({organizationId:org}).onConflictDoNothing();}
  settings(org:string,lock=false){const q=this.db.select().from(retentionSettings).where(eq(retentionSettings.organizationId,org)).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async saveSettings(org:string,input:Omit<typeof retentionSettings.$inferInsert,"organizationId"|"id"|"createdAt">){const[row]=await this.db.insert(retentionSettings).values({organizationId:org,...input}).onConflictDoUpdate({target:retentionSettings.organizationId,set:{...input,updatedAt:new Date()}}).returning();return row;}
  customer(org:string,id:string,lock=false){const q=this.db.select().from(customers).where(and(eq(customers.organizationId,org),eq(customers.id,id),eq(customers.status,"active"),isNull(customers.archivedAt))).limit(1);return (lock?q.for("update"):q).then(r=>r[0]??null);}
  preference(org:string,customerId:string,lock=false){const q=this.db.select().from(retentionPreferences).where(and(eq(retentionPreferences.organizationId,org),eq(retentionPreferences.customerId,customerId))).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async savePreference(org:string,customerId:string,input:Omit<typeof retentionPreferences.$inferInsert,"organizationId"|"customerId">){const [row]=await this.db.insert(retentionPreferences).values({organizationId:org,customerId,...input}).onConflictDoUpdate({target:[retentionPreferences.organizationId,retentionPreferences.customerId],set:{...input,updatedAt:new Date()}}).returning();return row;}
  capabilityByHash(hash:string,lock=false){const q=this.db.select().from(retentionPublicCapabilities).where(eq(retentionPublicCapabilities.tokenHash,hash)).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  capabilityForResource(org:string,purpose:string,resourceId:string){return this.db.select().from(retentionPublicCapabilities).where(and(eq(retentionPublicCapabilities.organizationId,org),eq(retentionPublicCapabilities.purpose,purpose),eq(retentionPublicCapabilities.resourceId,resourceId))).limit(1).then(r=>r[0]??null);}
  async addCapability(input:typeof retentionPublicCapabilities.$inferInsert){const[row]=await this.db.insert(retentionPublicCapabilities).values(input).onConflictDoNothing().returning();return row??null;}
  async consumeCapability(id:string,at:Date){await this.db.update(retentionPublicCapabilities).set({consumedAt:at}).where(and(eq(retentionPublicCapabilities.id,id),isNull(retentionPublicCapabilities.consumedAt)));}
  program(org:string,lock=false){const q=this.db.select().from(referralPrograms).where(eq(referralPrograms.organizationId,org)).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async saveProgram(org:string,input:Omit<typeof referralPrograms.$inferInsert,"organizationId">){const [row]=await this.db.insert(referralPrograms).values({organizationId:org,...input}).onConflictDoUpdate({target:referralPrograms.organizationId,set:{...input,updatedAt:new Date()}}).returning();return row;}
  referral(org:string,id:string,lock=false){const q=this.db.select().from(customerReferrals).where(and(eq(customerReferrals.organizationId,org),eq(customerReferrals.id,id))).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  referralByCode(code:string,lock=false){const q=this.db.select().from(customerReferrals).where(eq(customerReferrals.referralCode,code)).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async createReferral(input:typeof customerReferrals.$inferInsert){const[row]=await this.db.insert(customerReferrals).values(input).returning();return row;}
  async claimReferral(org:string,id:string,leadId:string){const[row]=await this.db.update(customerReferrals).set({referredLeadId:leadId,updatedAt:new Date()}).where(and(eq(customerReferrals.organizationId,org),eq(customerReferrals.id,id),isNull(customerReferrals.referredLeadId),isNull(customerReferrals.referredCustomerId),eq(customerReferrals.status,"pending"))).returning();return row??null;}
  async listReferrals(org:string,{limit,offset}:{limit:number;offset:number}){const where=eq(customerReferrals.organizationId,org);const [items,[{total}]]=await Promise.all([this.db.select().from(customerReferrals).where(where).orderBy(desc(customerReferrals.createdAt)).limit(limit).offset(offset),this.db.select({total:count()}).from(customerReferrals).where(where)]);return{items,total:Number(total)};}
  async createLeadForReferral(org:string,name:string,email:string|null,phone:string|null,referralId:string){const[lead]=await this.db.insert(leads).values({organizationId:org,identifier:`LEAD-REF-${referralId.slice(0,8).toUpperCase()}`,name,email,phone,source:"Existing Customer Referral",notes:`Referral ${referralId}`}).returning();return lead;}
  async pendingReferralQualifications(org:string){return this.db.select({referral:customerReferrals,convertedCustomerId:leads.convertedCustomerId}).from(customerReferrals).leftJoin(leads,and(eq(leads.organizationId,customerReferrals.organizationId),eq(leads.id,customerReferrals.referredLeadId))).where(and(eq(customerReferrals.organizationId,org),eq(customerReferrals.status,"pending"),or(sql`${customerReferrals.referredCustomerId} is not null`,sql`${leads.convertedCustomerId} is not null`))).limit(100);}
  async qualifyingJob(org:string,customerId:string){const[row]=await this.db.select().from(jobs).where(and(eq(jobs.organizationId,org),eq(jobs.customerId,customerId),inArray(jobs.status,["completed","invoiced"]))).orderBy(asc(jobs.completedAt)).limit(1);return row??null;}
  async qualifyingInvoice(org:string,customerId:string){const[row]=await this.db.select().from(invoices).where(and(eq(invoices.organizationId,org),eq(invoices.customerId,customerId),eq(invoices.status,"paid"))).orderBy(asc(invoices.issuedAt)).limit(1);return row??null;}
  async qualifyReferral(org:string,id:string,customerId:string,jobId:string|null,invoiceId:string|null){const[row]=await this.db.update(customerReferrals).set({referredCustomerId:customerId,qualifyingJobId:jobId,qualifyingInvoiceId:invoiceId,status:"qualified",qualifiedAt:new Date(),updatedAt:new Date()}).where(and(eq(customerReferrals.organizationId,org),eq(customerReferrals.id,id),eq(customerReferrals.status,"pending"))).returning();return row??null;}
  async markReferralRewarded(org:string,id:string){await this.db.update(customerReferrals).set({status:"rewarded",updatedAt:new Date()}).where(and(eq(customerReferrals.organizationId,org),eq(customerReferrals.id,id),eq(customerReferrals.status,"qualified")));}
  creditBySource(org:string,sourceType:string,sourceId:string){return this.db.select().from(customerCreditLedger).where(and(eq(customerCreditLedger.organizationId,org),eq(customerCreditLedger.sourceType,sourceType),eq(customerCreditLedger.sourceId,sourceId))).limit(1).then(r=>r[0]??null);}
  async addCredit(input:typeof customerCreditLedger.$inferInsert){const[row]=await this.db.insert(customerCreditLedger).values(input).onConflictDoNothing().returning();return row??null;}
  async lockCredit(org:string,id:string){const[row]=await this.db.select().from(customerCreditLedger).where(and(eq(customerCreditLedger.organizationId,org),eq(customerCreditLedger.id,id))).for("update").limit(1);return row??null;}
  async updateCredit(org:string,id:string,input:Partial<typeof customerCreditLedger.$inferInsert>){const[row]=await this.db.update(customerCreditLedger).set(input).where(and(eq(customerCreditLedger.organizationId,org),eq(customerCreditLedger.id,id))).returning();return row??null;}
  async credits(org:string,customerId:string){return this.db.select().from(customerCreditLedger).where(and(eq(customerCreditLedger.organizationId,org),eq(customerCreditLedger.customerId,customerId))).orderBy(desc(customerCreditLedger.createdAt));}
  campaign(org:string,id:string,lock=false){const q=this.db.select().from(campaigns).where(and(eq(campaigns.organizationId,org),eq(campaigns.id,id))).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async createCampaign(input:typeof campaigns.$inferInsert){const[row]=await this.db.insert(campaigns).values(input).returning();return row;}
  async updateCampaign(org:string,id:string,input:Partial<typeof campaigns.$inferInsert>){const[row]=await this.db.update(campaigns).set({...input,organizationId:undefined,id:undefined,updatedAt:new Date()}).where(and(eq(campaigns.organizationId,org),eq(campaigns.id,id))).returning();return row??null;}
  async listCampaigns(org:string,{limit,offset,status}:{limit:number;offset:number;status?:string}){const where=and(eq(campaigns.organizationId,org),status?sql`${campaigns.status}::text=${status}`:undefined);const[items,[{total}]]=await Promise.all([this.db.select().from(campaigns).where(where).orderBy(desc(campaigns.createdAt)).limit(limit).offset(offset),this.db.select({total:count()}).from(campaigns).where(where)]);return{items,total:Number(total)};}
  async dueCampaigns(org:string,now:Date){return this.db.select().from(campaigns).where(and(eq(campaigns.organizationId,org),eq(campaigns.status,"scheduled"),lte(campaigns.scheduledFor,now))).orderBy(asc(campaigns.scheduledFor)).limit(20);}
  async audience(org:string,filter:RetentionAudienceFilter,limit=500){const lastJob=sql<Date|null>`max(${jobs.completedAt})`;const completedCount=sql<number>`count(${jobs.id}) filter (where ${jobs.status} in ('completed','invoiced'))`;const activeMembership=sql<boolean>`bool_or(${maintenanceMemberships.status}='active' and ${maintenanceMemberships.effectiveEnd} >= current_date)`;const rows=await this.db.select({id:customers.id,name:customers.name,email:customers.email,phone:customers.phone,city:customers.city,lastCompletedAt:lastJob,completedCount,activeMembership}).from(customers).leftJoin(jobs,and(eq(jobs.organizationId,customers.organizationId),eq(jobs.customerId,customers.id),inArray(jobs.status,["completed","invoiced"]))).leftJoin(maintenanceMemberships,and(eq(maintenanceMemberships.organizationId,customers.organizationId),eq(maintenanceMemberships.customerId,customers.id))).where(and(eq(customers.organizationId,org),eq(customers.status,"active"),isNull(customers.archivedAt),filter.city?ilike(customers.city,filter.city):undefined)).groupBy(customers.id).orderBy(asc(customers.id)).limit(limit);return rows.filter(r=>{const days=r.lastCompletedAt?Math.floor((Date.now()-new Date(r.lastCompletedAt).getTime())/86400000):null;if(filter.membership&&filter.membership!=="any"&&Boolean(r.activeMembership)!==(filter.membership==="active"))return false;if(filter.minDaysSinceLastJob!==undefined&&(days===null||days<filter.minDaysSinceLastJob))return false;if(filter.maxDaysSinceLastJob!==undefined&&(days===null||days>filter.maxDaysSinceLastJob))return false;return true;});}
  async addRecipient(input:typeof campaignRecipients.$inferInsert){const[row]=await this.db.insert(campaignRecipients).values(input).onConflictDoNothing().returning();return row??null;}
  async addOutbox(input:typeof notificationOutbox.$inferInsert){const[row]=await this.db.insert(notificationOutbox).values(input).onConflictDoNothing().returning();return row??null;}
  async cancelPendingMarketing(org:string,customerId:string){const rows=await this.db.update(notificationOutbox).set({status:"cancelled",updatedAt:new Date()}).where(and(eq(notificationOutbox.organizationId,org),eq(notificationOutbox.customerId,customerId),eq(notificationOutbox.eventType,"campaign"),eq(notificationOutbox.status,"pending"))).returning({id:notificationOutbox.id});await this.db.update(campaignRecipients).set({status:"cancelled",suppressionReason:"unsubscribed"}).where(and(eq(campaignRecipients.organizationId,org),eq(campaignRecipients.customerId,customerId),inArray(campaignRecipients.outboxId,rows.map(x=>x.id))));return rows.length;}
  async attachOutbox(org:string,recipientId:string,outboxId:string){await this.db.update(campaignRecipients).set({outboxId,status:"pending"}).where(and(eq(campaignRecipients.organizationId,org),eq(campaignRecipients.id,recipientId)));}
  listRecipients(org:string,campaignId:string){return this.db.select().from(campaignRecipients).where(and(eq(campaignRecipients.organizationId,org),eq(campaignRecipients.campaignId,campaignId))).orderBy(asc(campaignRecipients.finalizedAt));}
  async completedJobsForFollowup(org:string,earliest:Date){return this.db.select().from(jobs).where(and(eq(jobs.organizationId,org),inArray(jobs.status,["completed","invoiced"]),gte(jobs.completedAt,earliest))).orderBy(asc(jobs.completedAt)).limit(100);}
  async addFollowUp(input:typeof retentionFollowUps.$inferInsert){const[row]=await this.db.insert(retentionFollowUps).values(input).onConflictDoNothing().returning();return row??null;}
  followUp(org:string,id:string,lock=false){const q=this.db.select().from(retentionFollowUps).where(and(eq(retentionFollowUps.organizationId,org),eq(retentionFollowUps.id,id))).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async updateFollowUp(org:string,id:string,input:Partial<typeof retentionFollowUps.$inferInsert>){const[row]=await this.db.update(retentionFollowUps).set({...input,id:undefined,organizationId:undefined,jobId:undefined,customerId:undefined,updatedAt:new Date()}).where(and(eq(retentionFollowUps.organizationId,org),eq(retentionFollowUps.id,id))).returning();return row??null;}
  async publicFollowUp(org:string,id:string){const[row]=await this.db.select({followUp:retentionFollowUps,jobIdentifier:jobs.identifier,customerName:customers.name}).from(retentionFollowUps).innerJoin(jobs,and(eq(jobs.organizationId,retentionFollowUps.organizationId),eq(jobs.id,retentionFollowUps.jobId))).innerJoin(customers,and(eq(customers.organizationId,retentionFollowUps.organizationId),eq(customers.id,retentionFollowUps.customerId))).where(and(eq(retentionFollowUps.organizationId,org),eq(retentionFollowUps.id,id))).limit(1);return row??null;}
  async activeMaintenanceMembership(org:string,customerId:string,today:string,lock=false){const q=this.db.select({id:maintenanceMemberships.id}).from(maintenanceMemberships).where(and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.customerId,customerId),eq(maintenanceMemberships.status,"active"),lte(maintenanceMemberships.effectiveStart,today),gte(maintenanceMemberships.effectiveEnd,today))).limit(1);return(lock?q.for("update"):q).then(r=>r[0]??null);}
  async activeMaintenancePlans(org:string,today:string){return this.db.select({id:maintenancePlans.id,name:maintenancePlans.name,description:maintenancePlans.description,tier:maintenancePlans.tier,priceCents:maintenancePlans.priceCents,currency:maintenancePlans.currency}).from(maintenancePlans).where(and(eq(maintenancePlans.organizationId,org),eq(maintenancePlans.status,"active"),or(isNull(maintenancePlans.effectiveFrom),lte(maintenancePlans.effectiveFrom,today)),or(isNull(maintenancePlans.effectiveUntil),gte(maintenancePlans.effectiveUntil,today)))).orderBy(asc(maintenancePlans.sortOrder),asc(maintenancePlans.name)).limit(20);}
  async addRun(input:typeof retentionAutomationRuns.$inferInsert){const[row]=await this.db.insert(retentionAutomationRuns).values(input).returning();return row;}
  listRuns(org:string){return this.db.select().from(retentionAutomationRuns).where(eq(retentionAutomationRuns.organizationId,org)).orderBy(desc(retentionAutomationRuns.createdAt)).limit(50);}
  async signalRows(org:string,customerId:string){const [row]=await this.db.select({lastCompletedAt:sql<Date|null>`max(${jobs.completedAt})`,completedCount:sql<number>`count(${jobs.id}) filter (where ${jobs.status} in ('completed','invoiced'))`}).from(customers).leftJoin(jobs,and(eq(jobs.organizationId,customers.organizationId),eq(jobs.customerId,customers.id))).where(and(eq(customers.organizationId,org),eq(customers.id,customerId))).groupBy(customers.id);const[membership]=await this.db.select({id:maintenanceMemberships.id}).from(maintenanceMemberships).where(and(eq(maintenanceMemberships.organizationId,org),eq(maintenanceMemberships.customerId,customerId),eq(maintenanceMemberships.status,"active"),gte(maintenanceMemberships.effectiveEnd,sql`current_date`))).limit(1);return row?{...row,activeMembership:Boolean(membership)}:null;}
}
