import "server-only";
import { authorize } from "@/auth/authorization";
import { getDb } from "@/db";
import { organizations } from "@/db/schema";
import { eq } from "drizzle-orm";
import { ConflictError } from "@/lib/errors";
import { AuditRepository } from "@/modules/audit/audit.repository";
import type { RequestActor } from "@/modules/customers/customer.service";
import { CampaignService } from "./retention.service";
import { RetentionRepository } from "./retention.repository";
import { addBusinessDays, createRetentionCapability, hashRetentionCapability } from "./retention.rules";

export interface TrustedRetentionRunner { kind:"trusted_retention_scheduler"; organizationId:string }
export class RetentionAutomationService {
  async runManual(actor:RequestActor){await authorize(actor,"campaign.execute");return this.run(actor.organizationId,"manual",actor.userId);}
  async runTrusted(context:TrustedRetentionRunner){if(context.kind!=="trusted_retention_scheduler")throw new ConflictError("Invalid retention scheduler context");return this.run(context.organizationId,"scheduler",null);}
  async runTrustedAll(context:{kind:"trusted_retention_scheduler"}){if(context.kind!=="trusted_retention_scheduler")throw new ConflictError("Invalid retention scheduler context");const rows=await getDb().select({id:organizations.id}).from(organizations).where(eq(organizations.active,true));const results=[];for(const row of rows)results.push({organizationId:row.id,...await this.run(row.id,"scheduler",null)});return results;}
  private async run(org:string,triggeredBy:"manual"|"scheduler",actorUserId:string|null){const summary={followUpsCreated:0,referralsQualified:0,rewardsIssued:0,campaignsExecuted:0,recipientsFinalized:0,erroredCount:0,errorSummary:""};
    await getDb().transaction(async tx=>{const r=new RetentionRepository(tx),audit=new AuditRepository(tx),now=new Date(),earliest=new Date(now.getTime()-60*86400000);await r.ensureSettings(org);const settings=await r.settings(org,true);for(const job of await r.completedJobsForFollowup(org,earliest)){const customer=await r.customer(org,job.customerId);if(!customer)continue;const completedAt=job.completedAt??now,dueInstant=new Date(completedAt.getTime()+(settings?.followUpDelayDays??7)*86400000),dueDate=addBusinessDays(completedAt,settings?.followUpDelayDays??7);const follow=await r.addFollowUp({organizationId:org,jobId:job.id,customerId:job.customerId,dueDate});if(!follow)continue;summary.followUpsCreated++;const pref=await r.preference(org,customer.id);const channel=customer.email?"email":customer.phone?"sms":null;const address=channel==="email"?customer.email:customer.phone;if(channel&&address&&!pref?.doNotContact){const token=createRetentionCapability();await r.addCapability({organizationId:org,customerId:customer.id,purpose:"follow_up_response",resourceId:follow.id,tokenHash:hashRetentionCapability(token),expiresAt:new Date(dueInstant.getTime()+30*86400000)});const path=`/follow-up/${token}`,responseUrl=settings?.publicBaseUrl?`${settings.publicBaseUrl.replace(/\/+$/g,"")}${path}`:path;await r.addOutbox({organizationId:org,customerId:customer.id,channel,eventType:"post_job_follow_up",entityType:"retention_follow_up",entityId:follow.id,dedupeKey:`follow-up:${follow.id}:${channel}`,recipientSnapshot:{customerId:customer.id,name:customer.name,address,channel},payload:{jobId:job.id,dueDate,responseUrl},availableAt:dueInstant});}}
      const program=await r.program(org,true);if(program?.enabled){for(const candidate of await r.pendingReferralQualifications(org)){const customerId=candidate.referral.referredCustomerId??candidate.convertedCustomerId;if(!customerId)continue;const qualifying=program.qualificationRule==="first_paid_invoice"?await r.qualifyingInvoice(org,customerId):await r.qualifyingJob(org,customerId);if(!qualifying)continue;const qualified=await r.qualifyReferral(org,candidate.referral.id,customerId,program.qualificationRule==="first_completed_job"?qualifying.id:null,program.qualificationRule==="first_paid_invoice"?qualifying.id:null);if(!qualified)continue;summary.referralsQualified++;const reward=await r.addCredit({organizationId:org,customerId:qualified.referrerCustomerId,sourceType:"referral_reward",sourceId:qualified.id,amountCents:program.rewardValueCents,valueDescription:program.rewardDescription,reason:`Qualified by ${program.qualificationRule}`,actorUserId});if(reward){summary.rewardsIssued++;await r.markReferralRewarded(org,qualified.id);await audit.record({organizationId:org,actorUserId,action:"referral.rewarded",entityType:"referral",entityId:qualified.id,metadata:{rewardId:reward.id,rewardType:program.rewardType,amountCents:reward.amountCents}});}}}
      });
    const r=new RetentionRepository();for(const campaign of await r.dueCampaigns(org,new Date())){try{const result=await new CampaignService().executeTrusted(org,campaign.id);if(!result.idempotent){summary.campaignsExecuted++;summary.recipientsFinalized+=result.finalized;}}catch(error){summary.erroredCount++;summary.errorSummary=error instanceof Error?error.message:"Campaign execution failed";}}
    await new RetentionRepository().addRun({organizationId:org,triggeredBy,actorUserId,...summary});return summary;}
}
