import { sql } from "drizzle-orm";
import { bigint, boolean, check, date, foreignKey, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { attachments } from "./attachments";
import { customers } from "./customers";
import { organizations, users } from "./identity";
import { jobs } from "./jobs";
import { maintenanceAgreements, maintenanceAgreementVersions, maintenanceMemberships, maintenanceOccurrences, maintenancePlans, maintenanceReminderIntents } from "./maintenance";

export const assetStatus = pgEnum("asset_status", ["active", "inactive", "retired"]);
export const templateVersionStatus = pgEnum("maintenance_template_version_status", ["draft", "published", "superseded"]);
export const serviceReportStatus = pgEnum("maintenance_service_report_status", ["draft", "submitted"]);
export const outboxStatus = pgEnum("maintenance_outbox_status", ["pending", "processing", "delivered", "failed", "cancelled"]);

export const assets = pgTable("assets", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), customerId: uuid("customer_id").notNull(),
  type: text("type").notNull(), displayName: text("display_name").default("").notNull(), manufacturer: text("manufacturer").default("").notNull(), model: text("model").default("").notNull(), serialNumber: text("serial_number").default("").notNull(), installationDate: date("installation_date"), serviceLocation: text("service_location").notNull(), status: assetStatus("status").default("active").notNull(), notes: text("notes").default("").notNull(),
  rowVersion: integer("row_version").default(0).notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("assets_org_id_unique").on(t.organizationId, t.id), index("assets_org_customer_idx").on(t.organizationId, t.customerId, t.status), index("assets_org_serial_idx").on(t.organizationId, t.serialNumber), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "assets_customer_tenant_fk" }).onDelete("restrict"), check("assets_row_version_valid", sql`${t.rowVersion} >= 0`)]);

export const maintenanceLegalDocuments = pgTable("maintenance_legal_documents", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), title: text("title").notNull(), active: boolean("active").default(true).notNull(), currentPublishedVersionId: uuid("current_published_version_id"), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_legal_documents_org_id_unique").on(t.organizationId, t.id), index("maintenance_legal_documents_org_idx").on(t.organizationId, t.active)]);

export const maintenanceLegalVersions = pgTable("maintenance_legal_versions", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull(), documentId: uuid("document_id").notNull(), versionNumber: integer("version_number").notNull(), status: templateVersionStatus("status").default("draft").notNull(), content: text("content").notNull(), contentHash: text("content_hash").notNull(), effectiveFrom: date("effective_from"), publishedAt: timestamp("published_at", { withTimezone: true }), publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_legal_versions_org_id_unique").on(t.organizationId, t.id), uniqueIndex("maintenance_legal_version_number_unique").on(t.organizationId, t.documentId, t.versionNumber), foreignKey({ columns: [t.organizationId, t.documentId], foreignColumns: [maintenanceLegalDocuments.organizationId, maintenanceLegalDocuments.id], name: "maintenance_legal_version_document_tenant_fk" }).onDelete("cascade")]);

export const maintenanceChecklistTemplates = pgTable("maintenance_checklist_templates", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), applicability: jsonb("applicability").$type<string[]>().default([]).notNull(), active: boolean("active").default(true).notNull(), currentPublishedVersionId: uuid("current_published_version_id"), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_checklist_templates_org_id_unique").on(t.organizationId, t.id), index("maintenance_checklist_templates_org_idx").on(t.organizationId, t.active)]);

export const maintenanceChecklistVersions = pgTable("maintenance_checklist_versions", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull(), templateId: uuid("template_id").notNull(), versionNumber: integer("version_number").notNull(), status: templateVersionStatus("status").default("draft").notNull(), sections: jsonb("sections").$type<Array<{ title: string; items: Array<{ key: string; label: string; type: string; required: boolean }> }>>().notNull(), contentHash: text("content_hash").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), publishedBy: uuid("published_by").references(() => users.id, { onDelete: "set null" }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_checklist_versions_org_id_unique").on(t.organizationId, t.id), uniqueIndex("maintenance_checklist_version_number_unique").on(t.organizationId, t.templateId, t.versionNumber), foreignKey({ columns: [t.organizationId, t.templateId], foreignColumns: [maintenanceChecklistTemplates.organizationId, maintenanceChecklistTemplates.id], name: "maintenance_checklist_version_template_tenant_fk" }).onDelete("cascade")]);

export const maintenanceAgreementCoverage = pgTable("maintenance_agreement_coverage", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull(), agreementId: uuid("agreement_id").notNull(), agreementVersionId: uuid("agreement_version_id").notNull(), assetId: uuid("asset_id"), assetSnapshot: jsonb("asset_snapshot").$type<Record<string, unknown>>().notNull(), coverageSnapshot: jsonb("coverage_snapshot").$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_coverage_version_asset_unique").on(t.organizationId, t.agreementVersionId, t.assetId), index("maintenance_coverage_agreement_idx").on(t.organizationId, t.agreementId), foreignKey({ columns: [t.organizationId, t.agreementId], foreignColumns: [maintenanceAgreements.organizationId, maintenanceAgreements.id], name: "maintenance_coverage_agreement_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.agreementVersionId], foreignColumns: [maintenanceAgreementVersions.organizationId, maintenanceAgreementVersions.id], name: "maintenance_coverage_version_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.assetId], foreignColumns: [assets.organizationId, assets.id], name: "maintenance_coverage_asset_tenant_fk" }).onDelete("set null")]);

export const maintenanceServiceReports = pgTable("maintenance_service_reports", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), jobId: uuid("job_id").notNull(), agreementId: uuid("agreement_id").notNull(), agreementVersionId: uuid("agreement_version_id").notNull(), membershipId: uuid("membership_id").notNull(), occurrenceId: uuid("occurrence_id").notNull(), assetId: uuid("asset_id"), checklistVersionId: uuid("checklist_version_id").notNull(), status: serviceReportStatus("status").default("draft").notNull(), checklistSnapshot: jsonb("checklist_snapshot").notNull(), responses: jsonb("responses").$type<Record<string, unknown>>().default({}).notNull(), findings: text("findings").default("").notNull(), deficiencies: text("deficiencies").default("").notNull(), recommendations: text("recommendations").default("").notNull(), preWorkAttachmentId: uuid("pre_work_attachment_id"), postWorkAttachmentId: uuid("post_work_attachment_id"), customerSignerName: text("customer_signer_name"), customerSignatureHash: text("customer_signature_hash"), customerAcknowledgedAt: timestamp("customer_acknowledged_at", { withTimezone: true }), technicianUserId: uuid("technician_user_id").notNull(), submittedAt: timestamp("submitted_at", { withTimezone: true }), submittedBy: uuid("submitted_by").references(() => users.id, { onDelete: "set null" }), rowVersion: integer("row_version").default(0).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_report_job_unique").on(t.organizationId, t.jobId), uniqueIndex("maintenance_reports_org_id_unique").on(t.organizationId, t.id), index("maintenance_reports_membership_idx").on(t.organizationId, t.membershipId, t.status), foreignKey({ columns: [t.organizationId, t.jobId], foreignColumns: [jobs.organizationId, jobs.id], name: "maintenance_report_job_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.agreementId], foreignColumns: [maintenanceAgreements.organizationId, maintenanceAgreements.id], name: "maintenance_report_agreement_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.agreementVersionId], foreignColumns: [maintenanceAgreementVersions.organizationId, maintenanceAgreementVersions.id], name: "maintenance_report_version_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.membershipId], foreignColumns: [maintenanceMemberships.organizationId, maintenanceMemberships.id], name: "maintenance_report_membership_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.occurrenceId], foreignColumns: [maintenanceOccurrences.organizationId, maintenanceOccurrences.id], name: "maintenance_report_occurrence_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.assetId], foreignColumns: [assets.organizationId, assets.id], name: "maintenance_report_asset_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.checklistVersionId], foreignColumns: [maintenanceChecklistVersions.organizationId, maintenanceChecklistVersions.id], name: "maintenance_report_checklist_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.preWorkAttachmentId], foreignColumns: [attachments.organizationId, attachments.id], name: "maintenance_report_pre_attachment_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.postWorkAttachmentId], foreignColumns: [attachments.organizationId, attachments.id], name: "maintenance_report_post_attachment_tenant_fk" }).onDelete("restrict"), check("maintenance_report_submission_valid", sql`(${t.status} = 'draft' and ${t.submittedAt} is null) or (${t.status} = 'submitted' and ${t.submittedAt} is not null and ${t.customerAcknowledgedAt} is not null and ${t.preWorkAttachmentId} is not null and ${t.postWorkAttachmentId} is not null)`)]);

export const maintenanceSignedArtifacts = pgTable("maintenance_signed_artifacts", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull(), agreementId: uuid("agreement_id").notNull(), agreementVersionId: uuid("agreement_version_id").notNull(), objectKey: text("object_key").notNull(), sha256: text("sha256").notNull(), sizeBytes: integer("size_bytes").notNull(), contentType: text("content_type").default("application/pdf").notNull(), retainedAt: timestamp("retained_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_artifact_version_unique").on(t.organizationId, t.agreementVersionId), uniqueIndex("maintenance_artifact_object_key_unique").on(t.objectKey), foreignKey({ columns: [t.organizationId, t.agreementId], foreignColumns: [maintenanceAgreements.organizationId, maintenanceAgreements.id], name: "maintenance_artifact_agreement_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.agreementVersionId], foreignColumns: [maintenanceAgreementVersions.organizationId, maintenanceAgreementVersions.id], name: "maintenance_artifact_version_tenant_fk" }).onDelete("restrict"), check("maintenance_artifact_valid", sql`${t.sizeBytes} > 0 and ${t.sha256} ~ '^[0-9a-f]{64}$'`)]);

export const maintenanceOutbox = pgTable("maintenance_outbox", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), reminderIntentId: uuid("reminder_intent_id").notNull(), channel: text("channel").notNull(), eventType: text("event_type").notNull(), recipientSnapshot: jsonb("recipient_snapshot").notNull(), payload: jsonb("payload").notNull(), status: outboxStatus("status").default("pending").notNull(), attemptCount: integer("attempt_count").default(0).notNull(), lastError: text("last_error"), deliveredAt: timestamp("delivered_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_outbox_intent_channel_unique").on(t.organizationId, t.reminderIntentId, t.channel), index("maintenance_outbox_pending_idx").on(t.organizationId, t.status, t.createdAt), foreignKey({ columns: [t.organizationId, t.reminderIntentId], foreignColumns: [maintenanceReminderIntents.organizationId, maintenanceReminderIntents.id], name: "maintenance_outbox_reminder_tenant_fk" }).onDelete("restrict"), check("maintenance_outbox_attempt_valid", sql`${t.attemptCount} >= 0`)]);

export const maintenanceBenefitApplications = pgTable("maintenance_benefit_applications", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull(), membershipId: uuid("membership_id").notNull(), planId: uuid("plan_id").notNull(), quoteId: uuid("quote_id"), quoteOptionId: uuid("quote_option_id"), benefitSnapshot: jsonb("benefit_snapshot").notNull(), discountCents: bigint("discount_cents", { mode: "number" }).notNull(), idempotencyKey: text("idempotency_key").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("maintenance_benefit_idempotency_unique").on(t.organizationId, t.idempotencyKey), index("maintenance_benefit_membership_idx").on(t.organizationId, t.membershipId, t.createdAt), foreignKey({ columns: [t.organizationId, t.membershipId], foreignColumns: [maintenanceMemberships.organizationId, maintenanceMemberships.id], name: "maintenance_benefit_membership_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.planId], foreignColumns: [maintenancePlans.organizationId, maintenancePlans.id], name: "maintenance_benefit_plan_tenant_fk" }).onDelete("restrict"), check("maintenance_benefit_discount_valid", sql`${t.discountCents} >= 0`)]);
