import { sql } from "drizzle-orm";
import { bigint, boolean, check, date, foreignKey, index, integer, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { customers } from "./customers";
import { organizations, users } from "./identity";
import { jobs } from "./jobs";

export const maintenancePlanStatus=pgEnum("maintenance_plan_status",["active","inactive"]);
export const maintenanceAgreementStatus=pgEnum("maintenance_agreement_status",["draft","sent","viewed","active","cancelled","expired","superseded"]);
export const maintenanceRenewalPreference=pgEnum("maintenance_renewal_preference",["none","manual","auto"]);
export const maintenanceSignatureStatus=pgEnum("maintenance_signature_status",["pending","signed","revoked","expired"]);
export const maintenanceMembershipStatus=pgEnum("maintenance_membership_status",["active","cancelled","expired","superseded"]);
export const maintenanceScheduleStatus=pgEnum("maintenance_schedule_status",["active","paused","cancelled"]);
export const maintenanceRecurrence=pgEnum("maintenance_recurrence",["annual","semi_annual","quarterly","custom_days"]);
export const maintenanceOccurrenceStatus=pgEnum("maintenance_occurrence_status",["claimed","job_generated","skipped","cancelled"]);
export const maintenanceEntitlementEventType=pgEnum("maintenance_entitlement_event_type",["grant","consume","adjust"]);
export const maintenanceReminderStatus=pgEnum("maintenance_reminder_status",["pending","cancelled"]);

export const maintenancePlans=pgTable("maintenance_plans",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>organizations.id,{onDelete:"cascade"}),code:text("code").notNull(),name:text("name").notNull(),description:text("description").default("").notNull(),tier:text("tier").default("CUSTOM").notNull(),status:maintenancePlanStatus("status").default("active").notNull(),priceCents:bigint("price_cents",{mode:"number"}).default(0).notNull(),currency:text("currency").default("CAD").notNull(),taxable:boolean("taxable").default(true).notNull(),visitEntitlementCount:integer("visit_entitlement_count"),frequencyDescription:text("frequency_description").default("").notNull(),priorityBenefit:text("priority_benefit").default("").notNull(),discountType:text("discount_type").default("none").notNull(),discountBasisPoints:integer("discount_basis_points"),discountFixedCents:bigint("discount_fixed_cents",{mode:"number"}),includedServices:text("included_services").default("[]").notNull(),excludedServices:text("excluded_services").default("[]").notNull(),otherBenefits:text("other_benefits").default("[]").notNull(),equipmentEligibility:text("equipment_eligibility").default("[]").notNull(),effectiveFrom:date("effective_from"),effectiveUntil:date("effective_until"),sortOrder:integer("sort_order").default(0).notNull(),rowVersion:integer("row_version").default(0).notNull(),createdBy:uuid("created_by").references(()=>users.id,{onDelete:"set null"}),updatedBy:uuid("updated_by").references(()=>users.id,{onDelete:"set null"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_plans_org_id_unique").on(t.organizationId,t.id),uniqueIndex("maintenance_plans_org_code_unique").on(t.organizationId,t.code),index("maintenance_plans_org_status_idx").on(t.organizationId,t.status,t.sortOrder),check("maintenance_plan_money_valid",sql`${t.priceCents}>=0 and (${t.discountFixedCents} is null or ${t.discountFixedCents}>=0) and (${t.discountBasisPoints} is null or (${t.discountBasisPoints}>=0 and ${t.discountBasisPoints}<=10000))`),check("maintenance_plan_visits_valid",sql`${t.visitEntitlementCount} is null or ${t.visitEntitlementCount}>0`),check("maintenance_plan_currency_valid",sql`${t.currency} ~ '^[A-Z]{3}$'`),check("maintenance_plan_row_version_valid",sql`${t.rowVersion}>=0`)]);

export const maintenanceAgreements=pgTable("maintenance_agreements",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>organizations.id,{onDelete:"cascade"}),sequenceNumber:integer("sequence_number").notNull(),identifier:text("identifier").notNull(),customerId:uuid("customer_id").notNull(),planId:uuid("plan_id").notNull(),status:maintenanceAgreementStatus("status").default("draft").notNull(),currentVersionId:uuid("current_version_id"),supersedesAgreementId:uuid("supersedes_agreement_id"),supersededByAgreementId:uuid("superseded_by_agreement_id"),cancelledAt:timestamp("cancelled_at",{withTimezone:true}),cancelReason:text("cancel_reason"),rowVersion:integer("row_version").default(0).notNull(),createdBy:uuid("created_by").references(()=>users.id,{onDelete:"set null"}),updatedBy:uuid("updated_by").references(()=>users.id,{onDelete:"set null"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_agreements_org_id_unique").on(t.organizationId,t.id),uniqueIndex("maintenance_agreements_org_sequence_unique").on(t.organizationId,t.sequenceNumber),uniqueIndex("maintenance_agreements_org_identifier_unique").on(t.organizationId,t.identifier),index("maintenance_agreements_org_status_idx").on(t.organizationId,t.status,t.updatedAt),index("maintenance_agreements_customer_idx").on(t.organizationId,t.customerId),foreignKey({columns:[t.organizationId,t.customerId],foreignColumns:[customers.organizationId,customers.id],name:"maintenance_agreement_customer_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.planId],foreignColumns:[maintenancePlans.organizationId,maintenancePlans.id],name:"maintenance_agreement_plan_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.supersedesAgreementId],foreignColumns:[t.organizationId,t.id],name:"maintenance_agreement_supersedes_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.supersededByAgreementId],foreignColumns:[t.organizationId,t.id],name:"maintenance_agreement_superseded_by_tenant_fk"}).onDelete("restrict"),check("maintenance_agreement_row_version_valid",sql`${t.rowVersion}>=0`)]);

export const maintenanceAgreementVersions=pgTable("maintenance_agreement_versions",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),agreementId:uuid("agreement_id").notNull(),versionNumber:integer("version_number").default(1).notNull(),planSnapshot:text("plan_snapshot").notNull(),customerSnapshot:text("customer_snapshot").notNull(),serviceLocationSnapshot:text("service_location_snapshot").notNull(),termsSnapshot:text("terms_snapshot").default("").notNull(),effectiveDate:date("effective_date").notNull(),expiresOn:date("expires_on").notNull(),renewalPreference:maintenanceRenewalPreference("renewal_preference").default("none").notNull(),autoRenewConsent:text("auto_renew_consent").default("{}").notNull(),totalPriceCents:bigint("total_price_cents",{mode:"number"}).notNull(),currency:text("currency").notNull(),documentHash:text("document_hash"),signedAt:timestamp("signed_at",{withTimezone:true}),signatureMethod:text("signature_method"),activationProvenance:text("activation_provenance"),createdBy:uuid("created_by").references(()=>users.id,{onDelete:"set null"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_agreement_versions_org_id_unique").on(t.organizationId,t.id),uniqueIndex("maintenance_agreement_version_unique").on(t.organizationId,t.agreementId,t.versionNumber),index("maintenance_agreement_versions_agreement_idx").on(t.organizationId,t.agreementId),foreignKey({columns:[t.organizationId,t.agreementId],foreignColumns:[maintenanceAgreements.organizationId,maintenanceAgreements.id],name:"maintenance_version_agreement_tenant_fk"}).onDelete("cascade"),check("maintenance_version_term_valid",sql`${t.expiresOn}>=${t.effectiveDate} and ${t.totalPriceCents}>=0 and ${t.currency} ~ '^[A-Z]{3}$'`)]);

export const maintenanceSignatureRequests=pgTable("maintenance_signature_requests",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),agreementId:uuid("agreement_id").notNull(),agreementVersionId:uuid("agreement_version_id").notNull(),status:maintenanceSignatureStatus("status").default("pending").notNull(),tokenHash:text("token_hash").notNull(),signerName:text("signer_name").notNull(),signerEmail:text("signer_email").notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),consentAt:timestamp("consent_at",{withTimezone:true}),signedAt:timestamp("signed_at",{withTimezone:true}),signatureMethod:text("signature_method"),signerIp:text("signer_ip"),signerUserAgent:text("signer_user_agent"),autoRenewEnabled:boolean("auto_renew_enabled"),rowVersion:integer("row_version").default(0).notNull(),createdBy:uuid("created_by").references(()=>users.id,{onDelete:"set null"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_signature_token_unique").on(t.tokenHash),uniqueIndex("maintenance_signature_live_agreement_unique").on(t.organizationId,t.agreementId).where(sql`${t.status}='pending'`),index("maintenance_signature_agreement_idx").on(t.organizationId,t.agreementId),foreignKey({columns:[t.organizationId,t.agreementId],foreignColumns:[maintenanceAgreements.organizationId,maintenanceAgreements.id],name:"maintenance_signature_agreement_tenant_fk"}).onDelete("cascade"),foreignKey({columns:[t.organizationId,t.agreementVersionId],foreignColumns:[maintenanceAgreementVersions.organizationId,maintenanceAgreementVersions.id],name:"maintenance_signature_version_tenant_fk"}).onDelete("restrict"),check("maintenance_signature_completion_valid",sql`(${t.status}<>'signed') or (${t.signedAt} is not null and ${t.consentAt} is not null and ${t.autoRenewEnabled} is not null)`)]);

export const maintenanceMemberships=pgTable("maintenance_memberships",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),agreementId:uuid("agreement_id").notNull(),customerId:uuid("customer_id").notNull(),planId:uuid("plan_id").notNull(),status:maintenanceMembershipStatus("status").default("active").notNull(),effectiveStart:date("effective_start").notNull(),effectiveEnd:date("effective_end").notNull(),visitsIncluded:integer("visits_included"),cancelledAt:timestamp("cancelled_at",{withTimezone:true}),cancelReason:text("cancel_reason"),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_membership_agreement_unique").on(t.organizationId,t.agreementId),uniqueIndex("maintenance_memberships_org_id_unique").on(t.organizationId,t.id),index("maintenance_membership_customer_idx").on(t.organizationId,t.customerId,t.status),foreignKey({columns:[t.organizationId,t.agreementId],foreignColumns:[maintenanceAgreements.organizationId,maintenanceAgreements.id],name:"maintenance_membership_agreement_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.customerId],foreignColumns:[customers.organizationId,customers.id],name:"maintenance_membership_customer_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.planId],foreignColumns:[maintenancePlans.organizationId,maintenancePlans.id],name:"maintenance_membership_plan_tenant_fk"}).onDelete("restrict"),check("maintenance_membership_term_valid",sql`${t.effectiveEnd}>=${t.effectiveStart} and (${t.visitsIncluded} is null or ${t.visitsIncluded}>0)`)]);

export const maintenanceEntitlementEvents=pgTable("maintenance_entitlement_events",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),membershipId:uuid("membership_id").notNull(),eventType:maintenanceEntitlementEventType("event_type").notNull(),visitDelta:integer("visit_delta").notNull(),idempotencyKey:text("idempotency_key").notNull(),reason:text("reason").default("").notNull(),actorUserId:uuid("actor_user_id").references(()=>users.id,{onDelete:"set null"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_entitlement_idempotency_unique").on(t.organizationId,t.idempotencyKey),index("maintenance_entitlement_membership_idx").on(t.organizationId,t.membershipId,t.createdAt),foreignKey({columns:[t.organizationId,t.membershipId],foreignColumns:[maintenanceMemberships.organizationId,maintenanceMemberships.id],name:"maintenance_entitlement_membership_tenant_fk"}).onDelete("restrict"),check("maintenance_entitlement_delta_valid",sql`${t.visitDelta}<>0`)]);

export const maintenanceSchedules=pgTable("maintenance_schedules",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),membershipId:uuid("membership_id").notNull(),recurrence:maintenanceRecurrence("recurrence").notNull(),customIntervalDays:integer("custom_interval_days"),status:maintenanceScheduleStatus("status").default("active").notNull(),nextDueDate:date("next_due_date").notNull(),cyclesGenerated:integer("cycles_generated").default(0).notNull(),automationEnabled:boolean("automation_enabled").default(true).notNull(),pauseReason:text("pause_reason"),createdBy:uuid("created_by").references(()=>users.id,{onDelete:"set null"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_schedule_membership_unique").on(t.organizationId,t.membershipId),uniqueIndex("maintenance_schedules_org_id_unique").on(t.organizationId,t.id),index("maintenance_schedule_due_idx").on(t.organizationId,t.status,t.nextDueDate),foreignKey({columns:[t.organizationId,t.membershipId],foreignColumns:[maintenanceMemberships.organizationId,maintenanceMemberships.id],name:"maintenance_schedule_membership_tenant_fk"}).onDelete("restrict"),check("maintenance_schedule_interval_valid",sql`(${t.recurrence}='custom_days' and ${t.customIntervalDays} between 1 and 3650) or (${t.recurrence}<>'custom_days' and ${t.customIntervalDays} is null)`),check("maintenance_schedule_cycles_valid",sql`${t.cyclesGenerated}>=0`)]);

export const maintenanceOccurrences=pgTable("maintenance_occurrences",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),scheduleId:uuid("schedule_id").notNull(),membershipId:uuid("membership_id").notNull(),cycleNumber:integer("cycle_number").notNull(),dueDate:date("due_date").notNull(),status:maintenanceOccurrenceStatus("status").default("claimed").notNull(),jobId:uuid("job_id"),skipReason:text("skip_reason"),generatedAt:timestamp("generated_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_occurrences_org_id_unique").on(t.organizationId,t.id),uniqueIndex("maintenance_occurrence_cycle_unique").on(t.organizationId,t.scheduleId,t.cycleNumber),uniqueIndex("maintenance_occurrence_job_unique").on(t.organizationId,t.jobId).where(sql`${t.jobId} is not null`),index("maintenance_occurrence_due_idx").on(t.organizationId,t.status,t.dueDate),foreignKey({columns:[t.organizationId,t.scheduleId],foreignColumns:[maintenanceSchedules.organizationId,maintenanceSchedules.id],name:"maintenance_occurrence_schedule_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.membershipId],foreignColumns:[maintenanceMemberships.organizationId,maintenanceMemberships.id],name:"maintenance_occurrence_membership_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.jobId],foreignColumns:[jobs.organizationId,jobs.id],name:"maintenance_occurrence_job_tenant_fk"}).onDelete("restrict"),check("maintenance_occurrence_cycle_valid",sql`${t.cycleNumber}>0`)]);

export const maintenanceReminderIntents=pgTable("maintenance_reminder_intents",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),agreementId:uuid("agreement_id").notNull(),agreementVersionId:uuid("agreement_version_id").notNull(),milestoneDays:integer("milestone_days").notNull(),status:maintenanceReminderStatus("status").default("pending").notNull(),recipientSnapshot:text("recipient_snapshot").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("maintenance_reminders_org_id_unique").on(t.organizationId,t.id),uniqueIndex("maintenance_reminder_milestone_unique").on(t.organizationId,t.agreementVersionId,t.milestoneDays),index("maintenance_reminder_org_idx").on(t.organizationId,t.status,t.createdAt),foreignKey({columns:[t.organizationId,t.agreementId],foreignColumns:[maintenanceAgreements.organizationId,maintenanceAgreements.id],name:"maintenance_reminder_agreement_tenant_fk"}).onDelete("restrict"),foreignKey({columns:[t.organizationId,t.agreementVersionId],foreignColumns:[maintenanceAgreementVersions.organizationId,maintenanceAgreementVersions.id],name:"maintenance_reminder_version_tenant_fk"}).onDelete("restrict"),check("maintenance_reminder_milestone_valid",sql`${t.milestoneDays} in (60,30,14)`)]);

export const maintenanceAgreementStatusHistory=pgTable("maintenance_agreement_status_history",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),agreementId:uuid("agreement_id").notNull(),fromStatus:maintenanceAgreementStatus("from_status"),toStatus:maintenanceAgreementStatus("to_status").notNull(),actorUserId:uuid("actor_user_id").references(()=>users.id,{onDelete:"set null"}),reason:text("reason"),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[index("maintenance_agreement_history_idx").on(t.organizationId,t.agreementId,t.createdAt),foreignKey({columns:[t.organizationId,t.agreementId],foreignColumns:[maintenanceAgreements.organizationId,maintenanceAgreements.id],name:"maintenance_history_agreement_tenant_fk"}).onDelete("cascade")]);

export const maintenanceAutomationRuns=pgTable("maintenance_automation_runs",{id:uuid("id").defaultRandom().primaryKey(),organizationId:uuid("organization_id").notNull(),triggeredBy:text("triggered_by").notNull(),actorUserId:uuid("actor_user_id").references(()=>users.id,{onDelete:"set null"}),occurrencesProcessed:integer("occurrences_processed").default(0).notNull(),jobsGenerated:integer("jobs_generated").default(0).notNull(),renewalsProcessed:integer("renewals_processed").default(0).notNull(),remindersCreated:integer("reminders_created").default(0).notNull(),erroredCount:integer("errored_count").default(0).notNull(),errorSummary:text("error_summary").default("").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[index("maintenance_automation_runs_org_idx").on(t.organizationId,t.createdAt)]);
