import { sql } from "drizzle-orm";
import { boolean, check, foreignKey, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { customers } from "./customers";
import { organizationMembers, organizations, users } from "./identity";
import { jobs } from "./jobs";
import { leads } from "./leads";
import { tasks } from "./interactions";

export const phoneOperatingMode = pgEnum("phone_operating_mode", ["active", "paused", "maintenance", "disabled", "emergency_stop"]);
export const phoneNumberStatus = pgEnum("phone_number_status", ["active", "inactive"]);
export const phoneCallDirection = pgEnum("phone_call_direction", ["inbound", "outbound"]);
export const phoneCallStatus = pgEnum("phone_call_status", ["queued", "ringing", "in_progress", "completed", "failed", "no_answer", "busy", "canceled"]);
export const phoneMatchConfidence = pgEnum("phone_match_confidence", ["unknown", "exact_phone", "manual"]);
export const phoneInvocationStatus = pgEnum("phone_invocation_status", ["pending", "succeeded", "failed"]);

export const phoneOperationSettings = pgTable("phone_operation_settings", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), version: integer("version").notNull(), operatingMode: phoneOperatingMode("operating_mode").default("disabled").notNull(), inboundEnabled: boolean("inbound_enabled").default(false).notNull(), outboundEnabled: boolean("outbound_enabled").default(false).notNull(), maxConcurrentCalls: integer("max_concurrent_calls").default(1).notNull(), dailyCallCap: integer("daily_call_cap").default(25).notNull(), voiceRuntimeUrl: text("voice_runtime_url"), effectiveFrom: timestamp("effective_from", { withTimezone: true }).defaultNow().notNull(), effectiveUntil: timestamp("effective_until", { withTimezone: true }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_settings_org_version_uq").on(t.organizationId, t.version), uniqueIndex("phone_settings_one_current_uq").on(t.organizationId).where(sql`${t.effectiveUntil} is null`), check("phone_settings_caps_positive", sql`${t.maxConcurrentCalls} > 0 and ${t.dailyCallCap} > 0`)]);

export const phoneProviderCredentials = pgTable("phone_provider_credentials", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), provider: text("provider").default("twilio").notNull(), accountSid: text("account_sid").notNull(), authTokenCiphertext: text("auth_token_ciphertext").notNull(), authTokenIv: text("auth_token_iv").notNull(), authTokenTag: text("auth_token_tag").notNull(), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_provider_credentials_org_provider_uq").on(t.organizationId, t.provider)]);

export const phoneRuntimeCredentials = pgTable("phone_runtime_credentials", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), tokenHash: text("token_hash").notNull(), tokenPrefix: text("token_prefix").notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_runtime_token_hash_uq").on(t.tokenHash), index("phone_runtime_org_idx").on(t.organizationId, t.revokedAt)]);

export const voiceAgents = pgTable("voice_agents", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), logicalName: text("logical_name").notNull(), version: integer("version").notNull(), status: phoneNumberStatus("status").default("active").notNull(), isDefault: boolean("is_default").default(false).notNull(), prompt: text("prompt").notNull(), voice: text("voice").notNull(), toolPolicy: jsonb("tool_policy").$type<string[]>().default([]).notNull(), effectiveFrom: timestamp("effective_from", { withTimezone: true }).defaultNow().notNull(), effectiveUntil: timestamp("effective_until", { withTimezone: true }), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("voice_agents_org_name_version_uq").on(t.organizationId, t.logicalName, t.version), uniqueIndex("voice_agents_org_id_uq").on(t.organizationId, t.id), index("voice_agents_current_idx").on(t.organizationId, t.logicalName, t.effectiveUntil)]);

export const phoneNumbers = pgTable("phone_numbers", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), provider: text("provider").default("twilio").notNull(), providerNumberId: text("provider_number_id").notNull(), e164: text("e164").notNull(), label: text("label"), status: phoneNumberStatus("status").default("active").notNull(), inboundEnabled: boolean("inbound_enabled").default(true).notNull(), outboundEnabled: boolean("outbound_enabled").default(true).notNull(), voiceAgentId: uuid("voice_agent_id"), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_numbers_provider_e164_uq").on(t.provider, t.e164), uniqueIndex("phone_numbers_org_id_uq").on(t.organizationId, t.id), index("phone_numbers_org_status_idx").on(t.organizationId, t.status), foreignKey({ columns: [t.organizationId, t.voiceAgentId], foreignColumns: [voiceAgents.organizationId, voiceAgents.id], name: "phone_numbers_agent_tenant_fk" }).onDelete("restrict"), check("phone_numbers_e164_check", sql`${t.e164} ~ '^\\+[1-9][0-9]{7,14}$'`)]);

export const phoneCalls = pgTable("phone_calls", {
  clientRequestId: text("client_request_id").unique(),
  placementStartedAt: timestamp("placement_started_at", { withTimezone: true }),
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), provider: text("provider").default("twilio").notNull(), providerCallId: text("provider_call_id").notNull(), direction: phoneCallDirection("direction").notNull(), status: phoneCallStatus("status").default("queued").notNull(), phoneNumberId: uuid("phone_number_id").notNull(), normalizedFrom: text("normalized_from").notNull(), normalizedTo: text("normalized_to").notNull(), customerId: uuid("customer_id"), leadId: uuid("lead_id"), jobId: uuid("job_id"), matchConfidence: phoneMatchConfidence("match_confidence").default("unknown").notNull(), matchSource: text("match_source").notNull(), assignedUserId: uuid("assigned_user_id"), disposition: text("disposition"), notes: text("notes"), agentSnapshot: jsonb("agent_snapshot").$type<{ agentId: string; version: number; prompt: string; voice: string; toolPolicy: string[] }>(), startedAt: timestamp("started_at", { withTimezone: true }), answeredAt: timestamp("answered_at", { withTimezone: true }), endedAt: timestamp("ended_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_calls_provider_identity_uq").on(t.provider, t.providerCallId), uniqueIndex("phone_calls_org_id_uq").on(t.organizationId, t.id), index("phone_calls_org_created_idx").on(t.organizationId, t.createdAt), index("phone_calls_org_status_idx").on(t.organizationId, t.status, t.createdAt), index("phone_calls_org_from_idx").on(t.organizationId, t.normalizedFrom), foreignKey({ columns: [t.organizationId, t.phoneNumberId], foreignColumns: [phoneNumbers.organizationId, phoneNumbers.id], name: "phone_calls_number_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "phone_calls_customer_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.leadId], foreignColumns: [leads.organizationId, leads.id], name: "phone_calls_lead_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.jobId], foreignColumns: [jobs.organizationId, jobs.id], name: "phone_calls_job_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.assignedUserId], foreignColumns: [organizationMembers.organizationId, organizationMembers.userId], name: "phone_calls_assignee_tenant_fk" }).onDelete("restrict"), check("phone_calls_one_crm_subject", sql`num_nonnulls(${t.customerId}, ${t.leadId}) <= 1`)]);

export const phoneCallEvents = pgTable("phone_call_events", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), callId: uuid("call_id").notNull(), providerEventId: text("provider_event_id").notNull(), providerStatus: text("provider_status").notNull(), mappedStatus: phoneCallStatus("mapped_status").notNull(), providerOccurredAt: timestamp("provider_occurred_at", { withTimezone: true }).notNull(), accepted: boolean("accepted").notNull(), rejectionReason: text("rejection_reason"), metadata: jsonb("metadata").$type<Record<string, string>>().default({}).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_call_events_provider_uq").on(t.organizationId, t.providerEventId), index("phone_call_events_call_idx").on(t.organizationId, t.callId, t.providerOccurredAt), foreignKey({ columns: [t.organizationId, t.callId], foreignColumns: [phoneCalls.organizationId, phoneCalls.id], name: "phone_call_events_call_tenant_fk" }).onDelete("cascade")]);

export const phoneCallTranscripts = pgTable("phone_call_transcripts", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), callId: uuid("call_id").notNull(), sequence: integer("sequence").notNull(), speaker: text("speaker").notNull(), content: text("content").notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_transcripts_call_sequence_uq").on(t.organizationId, t.callId, t.sequence), foreignKey({ columns: [t.organizationId, t.callId], foreignColumns: [phoneCalls.organizationId, phoneCalls.id], name: "phone_transcripts_call_tenant_fk" }).onDelete("cascade"), check("phone_transcripts_sequence_nonnegative", sql`${t.sequence} >= 0`)]);

export const phoneCallOutcomes = pgTable("phone_call_outcomes", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), callId: uuid("call_id").notNull(), summary: text("summary").notNull(), disposition: text("disposition").notNull(), capturedBy: uuid("captured_by"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_outcomes_call_uq").on(t.organizationId, t.callId), foreignKey({ columns: [t.organizationId, t.callId], foreignColumns: [phoneCalls.organizationId, phoneCalls.id], name: "phone_outcomes_call_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.capturedBy], foreignColumns: [organizationMembers.organizationId, organizationMembers.userId], name: "phone_outcomes_actor_tenant_fk" }).onDelete("restrict")]);

export const phoneToolInvocations = pgTable("phone_tool_invocations", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), callId: uuid("call_id").notNull(), idempotencyKey: text("idempotency_key").notNull(), toolName: text("tool_name").notNull(), payloadHash: text("payload_hash").notNull(), status: phoneInvocationStatus("status").default("pending").notNull(), result: jsonb("result").$type<Record<string, unknown>>(), errorCode: text("error_code"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completed_at", { withTimezone: true }),
}, t => [uniqueIndex("phone_tool_invocations_key_uq").on(t.organizationId, t.callId, t.idempotencyKey), foreignKey({ columns: [t.organizationId, t.callId], foreignColumns: [phoneCalls.organizationId, phoneCalls.id], name: "phone_tool_invocations_call_tenant_fk" }).onDelete("cascade")]);

export const phoneCallTaskLinks = pgTable("phone_call_task_links", {
  organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), callId: uuid("call_id").notNull(), taskId: uuid("task_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("phone_call_task_links_task_uq").on(t.organizationId, t.taskId), index("phone_call_task_links_call_idx").on(t.organizationId, t.callId), foreignKey({ columns: [t.organizationId, t.callId], foreignColumns: [phoneCalls.organizationId, phoneCalls.id], name: "phone_call_task_links_call_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.taskId], foreignColumns: [tasks.organizationId, tasks.id], name: "phone_call_task_links_task_tenant_fk" }).onDelete("cascade")]);
