import { sql } from "drizzle-orm";
import { bigint, boolean, check, date, foreignKey, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { customers } from "./customers";
import { organizations, users } from "./identity";
import { invoices } from "./invoices";
import { jobs } from "./jobs";
import { leads } from "./leads";

export const followUpStatus = pgEnum("retention_follow_up_status", ["pending", "sent", "satisfied", "needs_attention", "closed", "failed", "suppressed"]);
export const referralStatus = pgEnum("retention_referral_status", ["pending", "qualified", "rewarded", "expired", "rejected"]);
export const creditStatus = pgEnum("retention_credit_status", ["issued", "voided", "redeemed"]);
export const campaignStatus = pgEnum("retention_campaign_status", ["draft", "scheduled", "running", "paused", "completed", "cancelled", "failed"]);
export const campaignChannel = pgEnum("retention_campaign_channel", ["email", "sms", "both"]);
export const recipientStatus = pgEnum("retention_recipient_status", ["queued", "pending", "suppressed", "cancelled"]);

export const retentionSettings = pgTable("retention_settings", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), followUpDelayDays: integer("follow_up_delay_days").default(7).notNull(), publicBaseUrl: text("public_base_url"), reviewUrl: text("review_url"), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("retention_settings_org_unique").on(t.organizationId), uniqueIndex("retention_settings_org_id_unique").on(t.organizationId, t.id), check("retention_settings_delay_valid", sql`${t.followUpDelayDays} between 0 and 365`)]);

export const retentionPreferences = pgTable("retention_preferences", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), customerId: uuid("customer_id").notNull(),
  marketingEmailOptIn: boolean("marketing_email_opt_in").default(false).notNull(), marketingSmsOptIn: boolean("marketing_sms_opt_in").default(false).notNull(), marketingEmailConsentAt: timestamp("marketing_email_consent_at", { withTimezone: true }), marketingEmailConsentSource: text("marketing_email_consent_source"), marketingSmsConsentAt: timestamp("marketing_sms_consent_at", { withTimezone: true }), marketingSmsConsentSource: text("marketing_sms_consent_source"), doNotContact: boolean("do_not_contact").default(false).notNull(), unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true }), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("retention_preferences_customer_unique").on(t.organizationId, t.customerId), uniqueIndex("retention_preferences_org_id_unique").on(t.organizationId, t.id), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "retention_preferences_customer_tenant_fk" }).onDelete("cascade"), check("retention_preferences_consent_valid", sql`((${t.marketingEmailOptIn}=false) or (${t.marketingEmailConsentAt} is not null and length(trim(${t.marketingEmailConsentSource}))>0)) and ((${t.marketingSmsOptIn}=false) or (${t.marketingSmsConsentAt} is not null and length(trim(${t.marketingSmsConsentSource}))>0))`)]);

export const retentionFollowUps = pgTable("retention_follow_ups", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), jobId: uuid("job_id").notNull(), customerId: uuid("customer_id").notNull(), status: followUpStatus("status").default("pending").notNull(), dueDate: date("due_date").notNull(), sentAt: timestamp("sent_at", { withTimezone: true }), response: text("response"), responseNotes: text("response_notes").default("").notNull(), respondedAt: timestamp("responded_at", { withTimezone: true }), reviewEligible: boolean("review_eligible").default(false).notNull(), reviewUrlSnapshot: text("review_url_snapshot"), reviewClickedAt: timestamp("review_clicked_at", { withTimezone: true }), maintenanceOfferShown: boolean("maintenance_offer_shown").default(false).notNull(), maintenanceOfferSnapshot: jsonb("maintenance_offer_snapshot"), closedAt: timestamp("closed_at", { withTimezone: true }), closedBy: uuid("closed_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("retention_follow_up_job_unique").on(t.organizationId, t.jobId), uniqueIndex("retention_follow_up_org_id_unique").on(t.organizationId, t.id), index("retention_follow_up_due_idx").on(t.organizationId, t.status, t.dueDate), foreignKey({ columns: [t.organizationId, t.jobId], foreignColumns: [jobs.organizationId, jobs.id], name: "retention_follow_up_job_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "retention_follow_up_customer_tenant_fk" }).onDelete("cascade")]);

export const retentionPublicCapabilities = pgTable("retention_public_capabilities", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), customerId: uuid("customer_id").notNull(), purpose: text("purpose").notNull(), resourceId: uuid("resource_id").notNull(), tokenHash: text("token_hash").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }), consumedAt: timestamp("consumed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("retention_public_capability_token_unique").on(t.tokenHash), uniqueIndex("retention_public_capability_resource_unique").on(t.organizationId, t.purpose, t.resourceId), index("retention_public_capability_customer_idx").on(t.organizationId, t.customerId, t.purpose), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "retention_public_capability_customer_tenant_fk" }).onDelete("cascade"), check("retention_public_capability_purpose_valid", sql`${t.purpose} in ('follow_up_response','marketing_unsubscribe')`)]);

export const referralPrograms = pgTable("referral_programs", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), enabled: boolean("enabled").default(false).notNull(), rewardType: text("reward_type").default("account_credit").notNull(), rewardValueCents: bigint("reward_value_cents", { mode: "number" }), rewardDescription: text("reward_description").default("").notNull(), qualificationRule: text("qualification_rule").default("first_completed_job").notNull(), updatedBy: uuid("updated_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("referral_program_org_unique").on(t.organizationId), uniqueIndex("referral_program_org_id_unique").on(t.organizationId, t.id), check("referral_program_reward_valid", sql`${t.rewardValueCents} is null or ${t.rewardValueCents}>=0`)]);

export const customerReferrals = pgTable("customer_referrals", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), referrerCustomerId: uuid("referrer_customer_id").notNull(), referredCustomerId: uuid("referred_customer_id"), referredLeadId: uuid("referred_lead_id"), referralCode: text("referral_code").notNull(), status: referralStatus("status").default("pending").notNull(), qualifyingJobId: uuid("qualifying_job_id"), qualifyingInvoiceId: uuid("qualifying_invoice_id"), qualifiedAt: timestamp("qualified_at", { withTimezone: true }), rejectedReason: text("rejected_reason").default("").notNull(), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("customer_referrals_org_id_unique").on(t.organizationId, t.id), uniqueIndex("customer_referral_code_unique").on(t.referralCode), uniqueIndex("customer_referral_referred_customer_unique").on(t.organizationId, t.referredCustomerId).where(sql`${t.referredCustomerId} is not null`), uniqueIndex("customer_referral_referred_lead_unique").on(t.organizationId, t.referredLeadId).where(sql`${t.referredLeadId} is not null`), index("customer_referrals_status_idx").on(t.organizationId, t.status, t.createdAt), foreignKey({ columns: [t.organizationId, t.referrerCustomerId], foreignColumns: [customers.organizationId, customers.id], name: "customer_referral_referrer_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.referredCustomerId], foreignColumns: [customers.organizationId, customers.id], name: "customer_referral_referred_customer_tenant_fk" }).onDelete("set null"), foreignKey({ columns: [t.organizationId, t.referredLeadId], foreignColumns: [leads.organizationId, leads.id], name: "customer_referral_lead_tenant_fk" }).onDelete("set null"), foreignKey({ columns: [t.organizationId, t.qualifyingJobId], foreignColumns: [jobs.organizationId, jobs.id], name: "customer_referral_job_tenant_fk" }).onDelete("set null"), foreignKey({ columns: [t.organizationId, t.qualifyingInvoiceId], foreignColumns: [invoices.organizationId, invoices.id], name: "customer_referral_invoice_tenant_fk" }).onDelete("set null")]);

export const customerCreditLedger = pgTable("customer_credit_ledger", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), customerId: uuid("customer_id").notNull(), sourceType: text("source_type").notNull(), sourceId: uuid("source_id"), amountCents: bigint("amount_cents", { mode: "number" }), valueDescription: text("value_description").default("").notNull(), status: creditStatus("status").default("issued").notNull(), reason: text("reason").default("").notNull(), issuedAt: timestamp("issued_at", { withTimezone: true }).defaultNow().notNull(), voidedAt: timestamp("voided_at", { withTimezone: true }), voidReason: text("void_reason"), redeemedAt: timestamp("redeemed_at", { withTimezone: true }), redeemedReason: text("redeemed_reason"), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("customer_credit_org_id_unique").on(t.organizationId, t.id), uniqueIndex("customer_credit_source_unique").on(t.organizationId, t.sourceType, t.sourceId).where(sql`${t.sourceId} is not null`), index("customer_credit_balance_idx").on(t.organizationId, t.customerId, t.status), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "customer_credit_customer_tenant_fk" }).onDelete("cascade"), check("customer_credit_amount_valid", sql`${t.amountCents} is null or ${t.amountCents}>0`)]);

export type RetentionAudienceFilter = { city?: string; membership?: "active" | "inactive" | "any"; minDaysSinceLastJob?: number; maxDaysSinceLastJob?: number };
export const campaigns = pgTable("campaigns", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: text("name").notNull(), campaignType: text("campaign_type").default("seasonal").notNull(), status: campaignStatus("status").default("draft").notNull(), channel: campaignChannel("channel").default("email").notNull(), subject: text("subject").default("").notNull(), body: text("body").default("").notNull(), ctaLink: text("cta_link").default("").notNull(), audienceFilter: jsonb("audience_filter").$type<RetentionAudienceFilter>().default({}).notNull(), scheduledFor: timestamp("scheduled_for", { withTimezone: true }), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), cancelledAt: timestamp("cancelled_at", { withTimezone: true }), cancelReason: text("cancel_reason"), createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("campaigns_org_id_unique").on(t.organizationId, t.id), index("campaigns_due_idx").on(t.organizationId, t.status, t.scheduledFor), check("campaign_schedule_valid", sql`${t.status}='draft' or ${t.scheduledFor} is not null or ${t.status} in ('cancelled','failed')`)]);

export const notificationOutbox = pgTable("notification_outbox", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), customerId: uuid("customer_id").notNull(), channel: text("channel").notNull(), eventType: text("event_type").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), dedupeKey: text("dedupe_key").notNull(), recipientSnapshot: jsonb("recipient_snapshot").notNull(), payload: jsonb("payload").notNull(), status: text("status").default("pending").notNull(), availableAt: timestamp("available_at", { withTimezone: true }).defaultNow().notNull(), attemptCount: integer("attempt_count").default(0).notNull(), lastError: text("last_error"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("notification_outbox_dedupe_unique").on(t.organizationId, t.dedupeKey), uniqueIndex("notification_outbox_org_id_unique").on(t.organizationId, t.id), index("notification_outbox_pending_idx").on(t.organizationId, t.status, t.createdAt), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "notification_outbox_customer_tenant_fk" }).onDelete("restrict"), check("notification_outbox_state_valid", sql`${t.status} in ('pending','processing','delivered','failed','cancelled') and ${t.attemptCount}>=0`)]);

export const campaignRecipients = pgTable("campaign_recipients", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull(), campaignId: uuid("campaign_id").notNull(), customerId: uuid("customer_id").notNull(), channel: text("channel").notNull(), status: recipientStatus("status").default("queued").notNull(), outboxId: uuid("outbox_id"), suppressionReason: text("suppression_reason"), recipientSnapshot: jsonb("recipient_snapshot").notNull(), finalizedAt: timestamp("finalized_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex("campaign_recipient_unique").on(t.organizationId, t.campaignId, t.customerId, t.channel), uniqueIndex("campaign_recipient_org_id_unique").on(t.organizationId, t.id), index("campaign_recipient_status_idx").on(t.organizationId, t.campaignId, t.status), foreignKey({ columns: [t.organizationId, t.campaignId], foreignColumns: [campaigns.organizationId, campaigns.id], name: "campaign_recipient_campaign_tenant_fk" }).onDelete("cascade"), foreignKey({ columns: [t.organizationId, t.customerId], foreignColumns: [customers.organizationId, customers.id], name: "campaign_recipient_customer_tenant_fk" }).onDelete("restrict"), foreignKey({ columns: [t.organizationId, t.outboxId], foreignColumns: [notificationOutbox.organizationId, notificationOutbox.id], name: "campaign_recipient_outbox_tenant_fk" }).onDelete("restrict")]);

export const retentionAutomationRuns = pgTable("retention_automation_runs", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), triggeredBy: text("triggered_by").notNull(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), followUpsCreated: integer("follow_ups_created").default(0).notNull(), referralsQualified: integer("referrals_qualified").default(0).notNull(), rewardsIssued: integer("rewards_issued").default(0).notNull(), campaignsExecuted: integer("campaigns_executed").default(0).notNull(), recipientsFinalized: integer("recipients_finalized").default(0).notNull(), erroredCount: integer("errored_count").default(0).notNull(), errorSummary: text("error_summary").default("").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, t => [index("retention_automation_runs_idx").on(t.organizationId, t.createdAt)]);
