import "server-only";
import { randomUUID } from "node:crypto";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { getServerEnv } from "@/lib/env";
export const MAX_UPLOAD_BYTES = 15 * 1024 * 1024;
export const DOWNLOAD_URL_TTL_SECONDS = 300;
export const ALLOWED_MIME_TYPES = ["image/jpeg", "image/png", "image/webp", "image/heic", "image/heif", "image/gif", "application/pdf"] as const;
const allowed = new Set<string>(ALLOWED_MIME_TYPES);
export interface ObjectStorage { put(key: string, body: Uint8Array, contentType: string): Promise<void>; get?(key: string): Promise<Uint8Array>; delete(key: string): Promise<void>; signedDownloadUrl(key: string, expiresIn?: number): Promise<string>; }
let client: S3Client | undefined;
function configuredStorage() { const env = getServerEnv(); if (!env.R2_ENDPOINT || !env.R2_ACCESS_KEY_ID || !env.R2_SECRET_ACCESS_KEY || !env.R2_BUCKET) throw new Error("R2 is not configured"); client ??= new S3Client({ region: "auto", endpoint: env.R2_ENDPOINT, credentials: { accessKeyId: env.R2_ACCESS_KEY_ID, secretAccessKey: env.R2_SECRET_ACCESS_KEY } }); return { client, bucket: env.R2_BUCKET }; }
export function createObjectKey(organizationId: string, entityType: string, entityId: string): string { if (!/^[0-9a-f-]{36}$/i.test(organizationId) || !/^[0-9a-f-]{36}$/i.test(entityId) || !/^[a-z][a-z0-9_-]{0,31}$/.test(entityType)) throw new Error("Invalid storage key scope"); return `organizations/${organizationId}/${entityType}/${entityId}/${randomUUID()}`; }
export function safeDisplayFilename(filename: string): string { const name = filename.replace(/[\u0000-\u001f\u007f]/g, "").replace(/\\/g, "/").split("/").pop()?.trim() ?? ""; if (!name || name === "." || name === "..") throw new Error("Invalid filename"); return name.slice(0, 255); }
export function assertFileAllowed(size: number, contentType: string): void { if (!Number.isSafeInteger(size) || size <= 0 || size > MAX_UPLOAD_BYTES) throw new Error("File size is not allowed"); if (!allowed.has(contentType)) throw new Error("File type is not allowed"); }
export function assertFileSignature(body: Uint8Array, contentType: string): void { assertFileAllowed(body.byteLength, contentType); const ascii = (start: number, end: number) => String.fromCharCode(...body.slice(start, end)); const matches = contentType === "image/jpeg" ? body[0] === 0xff && body[1] === 0xd8 && body[2] === 0xff : contentType === "image/png" ? body.slice(0, 8).every((v, i) => v === [137,80,78,71,13,10,26,10][i]) : contentType === "image/gif" ? ["GIF87a","GIF89a"].includes(ascii(0,6)) : contentType === "image/webp" ? ascii(0,4) === "RIFF" && ascii(8,12) === "WEBP" : contentType === "application/pdf" ? ascii(0,5) === "%PDF-" : ["image/heic","image/heif"].includes(contentType) ? ascii(4,8) === "ftyp" && ["heic","heix","hevc","hevx","mif1","msf1"].includes(ascii(8,12)) : false; if (!matches) throw new Error("File contents do not match the declared type"); }
export const r2Storage: ObjectStorage = { async put(key, body, contentType) { assertFileSignature(body, contentType); const { client: s3, bucket } = configuredStorage(); await s3.send(new PutObjectCommand({ Bucket: bucket, Key: key, Body: body, ContentType: contentType, ContentLength: body.byteLength })); }, async get(key) { const { client: s3, bucket } = configuredStorage(); const result = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key })); if (!result.Body) throw new Error("Object body missing"); return result.Body.transformToByteArray(); }, async delete(key) { const { client: s3, bucket } = configuredStorage(); await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key })); }, async signedDownloadUrl(key, expiresIn = DOWNLOAD_URL_TTL_SECONDS) { if (!Number.isInteger(expiresIn) || expiresIn < 30 || expiresIn > 900) throw new Error("Signed URL lifetime is not allowed"); const { client: s3, bucket } = configuredStorage(); return getSignedUrl(s3, new GetObjectCommand({ Bucket: bucket, Key: key }), { expiresIn }); } };
export const uploadFile = r2Storage.put.bind(r2Storage); export const deleteFile = r2Storage.delete.bind(r2Storage); export const getSignedDownloadUrl = r2Storage.signedDownloadUrl.bind(r2Storage);
